### ISSUE TITLE
Fix assessment family / subject data

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/416.

**Comment by alexsoble** [comment]
__First step__

What are all the assessment names (`assessment_definition.ASD_NAME`) in Somerville's Aspen X2?

__Answer__

https://gist.github.com/alexsoble/46145ce3e1370932fe1c

**Comment by alexsoble** [comment]
__Next step__

What are all the assessment names that meet our whitelist criteria for importing, i.e.

`Regexp.union(/ACCESS/, /WIDA-ACCESS/, /DIBELS/, /MCAS/, /MAP/, /MELA-O/, /MEPA/, /STAR/)`

__Answer__

https://gist.github.com/alexsoble/3fdf6d1120b9af007334

**Comment by alexsoble** [comment]
__Next question__

How is this assessment schema manifesting itself in our database after being:

1. exported from Aspen X2 to CSV with `assessment_export.sql` and,
2. imported into the Postgres database with `StudentAssessmentImporter`?

**Comment by alexsoble** [comment]
## Assessment families, subjects, counts:

Family | Subject | Database count
--- | --- | ---
ACCESS | ELL | 235
ACCESS | Composite | 135
ACCESS | Comprehension | 228
ACCESS | Literacy | 228
ACCESS | Oral | 229
ACCESS | Listening | 229
ACCESS | Reading | 229
ACCESS | Speaking | 228
ACCESS | Writing | 229
ACCESS | Overall | 95
DIBELS | DIBELS | 1102
DIBELS | #1 | 1025
DIBELS | #2 | 708
DIBELS | #3 | 691
MAP | Language | 593
MAP | Math | 1813
MAP | Reading | 1821
MAP | Usage | 579
MAP | Mathematics | 1777
MCAS | ELA | 472
MCAS | Math | 472
MCAS | Science | 95
MCAS | Arts | 704
MCAS | Mathematics | 704
MCAS | Technology | 141
MELA-O | ELL | 208
MELA-O | Spring | 173
MELA-O | Fall | 35
MEPA | ELL | 177
MEPA | Spring | 169
MEPA | Fall | 8
STAR | Math | 2199
STAR | Reading | 2532
STAR | Mathematics | 764

## Problems

+ MCAS: "Math" VS. "Mathematics"
+ STAR
: "Math" VS. "Mathematics"
+ DIBELS: subjects not meaningful
+ ACCESS: subjects include "Overall" and "Composite"
  + Should be treated differently; not subjects in the same way as "Comprehension" and "Literacy"

### Important and urgent:

+ Merge MCAS subject strings: "Math" and "Mathematics"
+ Merge STAR subject strings: "Math" and "Mathematics"
+ Clarify ACCESS subjects, handle "Overall" / "Composite"

### Good to do, not urgent:

+ Fix DIBELS subjects: DIBELS is queried by `family` only, so `subject`
 does not matter
+ Stop importing MAP, MELA-O, MEPA since we are not surfacing them in the interface
+ Stop importing MCAS Technology, Science, and Arts since we are not surfacing them in the interface
+ Simplify `assessment_export.sql`
  + `ASD_NAME`, `ASD_TEST` logic makes assumptions about assessment name strings that just don't hold
  + Nonsense DIBELS 'subjects' are a clear example

**Comment by kevinrobinson** [comment]
@alexsoble these are great summaries!

**Comment by alexsoble** [comment]
@kevinrobinson Thanks! Very important to get this right, thankfully not hard to fix :blush:

**Comment by alexsoble** [comment]
Assessments in database look much cleaner now. :blush: 

## Assessment families, subjects, counts:

From Student Insights, 2/26

Family | Subject | Count
--- | --- | ---
ACCESS | ELL | 235
ACCESS | Composite | 135
ACCESS | Comprehension | 228
ACCESS | Literacy | 228
ACCESS | Oral | 229
ACCESS | Listening | 229
ACCESS | Reading | 229
ACCESS | Speaking | 228
ACCESS | Writing | 229
ACCESS | Overall | 95
DIBELS |  | 3716
MCAS | ELA | 705
MCAS | Mathematics | 704
STAR | Reading | 2532
STAR | Mathematics | 2199

**Comment by alexsoble** [comment]
### Resolution

+ Closing this issue because the data quality issues are now under control: the database contains the assessment families and subjects we expect, and the import task succeeds on a fresh database.

+ We now have more reporting ability around assessments, i.e. `rake report:assessments`.

+ We also have data integrity checks to try to hold the data in place: #147, #183.

+ Future goal that came out of this work: move Assessment table to be generated during seeding, not importing (#176).

+ Remaining, more specific issue: integrate ACCESS data (#16). This is not time-sensitive because ACCESS information has been removed from the latest student profile version, so we have time to dig deeper into ACCESS, understand the data structure fully and surface it usefully.

  + As you can see in the table above, some of the ACCESS subject names are a bit cryptic. What is the difference between "Composite" and "Overall"? What does the "ELL" subject mean, since all ACCESS assessments are meant for ELL speakers? 

  + We'll find the answers by talking to Somerville ELL teachers, admins, and the IT team that maintains Somerville's X2 instance. 

+ Remaining, more specific issue: refine DIBELS information (#23). This is not time-sensitive because DIBELS has been removed from the latest student profile version just like ACCESS.

  + From Mari's research — https://github.com/codeforamerica/somerville-teacher-tool/issues/299#issue-110294185 — there appear to be subjects within DIBELS results, but those don't appear in X2. (At least not in the X2 columns we're currently inspecting.)

**Comment by kevinrobinson** [comment]
@alexsoble awesome, great work on taming all this complexity! :)
