### ISSUE TITLE
Numeric Sorts broken for IE11

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#1011]
The sorting helper code shared by all of our rosters (school, homeroom, and section) uses Number.isInteger as it sorts numeric fields (attendance count, test score, etc). 

[Number.isInteger isn't supported in IE11](https://docs.microsoft.com/en-us/scripting/javascript/reference/number-isinteger-function-number-javascript)

Not sure what our preference is on polyfill vs. change the code.

Any thoughts @alexsoble or @kevinrobinson ?

**Comment by kevinrobinson** [comment]
@jhilde Nice report!  That probably means that each of these Rollbar messages means a user is clicking on those headers and it's not sorting.

If this isn't supported IE, then https://lodash.com/docs/4.17.4#isInteger should do the trick.

**Comment by jhilde** [comment]
When in doubt, lodash! 😆

**Comment by jhilde** [comment]
Fixed with #1013
