### ISSUE TITLE
Expand student demographic field import

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#1012]
Rather than adding student information on a one-off basis, it seems reasonable to pool several attributes together for the import.

Here's a current list of fields and their likely Aspen mappings:

Year of Graduation: (STUDENT.STD_YOG)
Student’s House: (STUDENT.STD_FIELDB_008) [SHS specific]
Student’s Counselor: (STUDENT.STD_FIELDB_027) [SHS specific, I believe]
Home Phone: (PERSON.PSN_PHONE_01)
Parent Email (1): (PERSON.PSN_EMAIL_01)

Wonder if we should bring in the other phone numbers (emergency and cell) and the other email address (email2)?

**Comment by alexsoble** [comment]
Hey @jhilde! From conversation with Uri the other week about #1087, he mentioned just sticking to primary phone/email for now, so those would be the two PERSON data fields you listed. We can always come back for more data if we need it, and I like to try to follow Datensparsamkeit when possible: https://martinfowler.com/bliki/Datensparsamkeit.html

**Comment by jhilde** [comment]
Agreed, was just thinking about batching effort and asks for John Breslin.

Nice word @alexsoble! When I got my first email (1991), I decided to look in the German - English dictionary we had on the shelf. I chose freudestrahlend which was translated as joy.

**Comment by jhilde** [comment]
Looks like most of this is currently in the ui. 

The only piece is the year of graduation. Closing, open a new one to add year of graduation? @snoopyuri, seems like that's a lower priority.
