### ISSUE TITLE
Tests should fail if Uglifier can't compress JS in production 

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1029]
Tests can be green, local environment app can run smoothly, but if Uglifier can't compress our JS in production then we can't push to Heroku and the state of our code isn't good.

Example: https://github.com/studentinsights/studentinsights/pull/1028/commits/fe63ace0c3969a35e777caed8f850f4091e53ca4

**Comment by kevinrobinson** [comment]
@alexsoble FWIW, a small distinction is that Uglifier was succeeding in doing just what we asked it to :)  We just happened to be asking it to compile down to Harmony, which IE11 can't understand.

**Comment by alexsoble** [comment]
@kevinrobinson That's true but there was actually one step before that, where Uglifier failed to compress the JS. The JS worked great locally and the tests passed but the production compression was broken. Maybe this is a minor edge case but it violated my intuitions that everything in dev+test was green and happy but couldn't be deployed to prod successfully.

**Comment by alexsoble** [comment]
OK, talking about issues out loud with Uri -- this is a really minor edge case and probably won't help us help educators/admins in the near term so we should close.
