### ISSUE TITLE
Student Profile for High School Students

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#1038]
When high school educators log into Student Insights, their homepage is the section view. From there they can click a student in a section which takes them to the student profile.

Some reworking is needed to show relevant information.

The largest addition will be an area that shows a student's sections. The current feedback from Jodi Remington is to have the table list include (section number, schedule, educator name, current numeric grade). I'd imagine the section number would be clickable if the educator logged in has permission to that section.

The biggest question is, where should this information go on the student profile? I know we've been talking about student photos. Has anyone given any thought to redesigning the profile page? (@alexsoble @kevinrobinson)

If not, I'll go ahead and add it where it makes sense but I do think the student profile warrants another design pass.

**Comment by kevinrobinson** [comment]
@jhilde Yeah I'd vote for shipping minimal first, and redesigning after.  I'm happy to brainstorm on mockups or share feedback if that's helpful.  An initial thought would be to put it in the "Overview" panel truncated as the top 4 sections or something, and then have the table be the first thing within the overview details section.

re: photos, I'd punt on that here.  But I'd start with trying an iteration on the "bar" with student name, grade etc. into a card or panel that includes the picture when that time comes.

Another good forcing function for some redesign is if we pull the principal dashboard features - that'll need a little more design love, and maybe a good opportunity for time on a tightly scoped global redesign.  I'm always a bit worried about redesign scope creep, but if we've batched up a bit of design debt on the new section pages, profile changes for high school students, and minimal function new principal dashboard, maybe a good opportunity for it then.  That's just my two cents.

**Comment by jhilde** [comment]
Forgot I had already entered this issue. Just entered a new issue for my conversation with Uri #1078 so I'm going to close this one.
