### ISSUE TITLE
Jasmine tests time out in CI

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1053]
Like this: https://travis-ci.org/studentinsights/studentinsights/builds/276496239#L2384 for this PR: https://github.com/studentinsights/studentinsights/pull/1052

In the short term, restarting the build manually gets it working, but we should see if there's anything we could do to make this more reliable; it happened twice for me yesterday too.

Running the tests in Chrome locally takes ~2 seconds for me, so we could benchmark via command-line Teaspoon & phantomjs locally to see how slow it can get there and then profile / simplify / optimize.  Especially with the tests exercising the full UI, there's a lot happening.

**Comment by kevinrobinson** [comment]
Looking at https://travis-ci.org/studentinsights/studentinsights/builds/276342264#L2380 and the history [here](https://travis-ci.org/studentinsights/studentinsights/builds).  Doesn't seem like we can adjust Travis' "kill the job if there's no output" timeout to be more aggressive.

Seems like some other folks have had similar problems with teaspoon on CircleCI: https://github.com/jejacks0n/teaspoon/issues/312 and https://github.com/jejacks0n/teaspoon/issues/303.  I started pulling down the Travis container to try to reproduce locally but it's too slow so will have to try again another time.

**Comment by alexsoble** [comment]
Hmmm, looks like both of the builds you linked to are passing though?

**Comment by kevinrobinson** [comment]
@alexsoble Yeah I had to restart them.  You can see this if you scroll back through the build history - most builds are ~6m but then the failed ones all take ~16m, they're just sitting on the Jasmines doing nothing until the Travis "I haven't seen any output for 10 minutes" timeout hits.

**Comment by alexsoble** [comment]
@kevinrobinson Yep I've been getting this too now and @Jngai is reporting the same kind of bug.

**Comment by jhilde** [comment]
I don't want to blame everything on browserify but there are times when I run teaspoon locally and it gets into some browserify funk. Takes forever and just seems to be browserifying a ton of files.

**Comment by alexsoble** [comment]
Have we had this error since we switched over to Jest?

**Comment by kevinrobinson** [comment]
looks like nope! https://travis-ci.org/studentinsights/studentinsights/builds

**Comment by alexsoble** [comment]
Closing since we haven't seen this issue since we switched over to Jest!
