### ISSUE TITLE
Allow null state_id for students and educators

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#1056]
Both educators and students have an associated state_id. While this id is included in many of our imports, it doesn't appear to be used as a key. It seems local_id is universally used as a key in our imports.

Currently the query that exports students and educators from X2 limits the output to where ID_STATE is not null. Unfortunately, this means that some students in courses and educators assigned to courses are not in the Student Insights. 

This causes the import for section assignments (student and educator) and section grades to log an error for that row. It doesn't blow up, just logs. It also causes teachers to have a student missing from their section roster and prevents some (particularly new) educators from logging into Student Insights.

Any thoughts @alexsoble or @kevinrobinson?

**Comment by alexsoble** [comment]
Hey @jhilde! This is a really interesting point. You're right that `state_id` isn't being used as a key right now. We should think about when we add a second and a third district to the app — I could see `state_id` being really useful by allowing us to accurately share data about students between districts, for example, when a student moves from one to another. I don't think that happens very frequently between Somerville and Fall River, but I know that Uri has been in conversation with a few districts near Somerville about adopting Insights. And from what I've heard, families do move often between Somerville, Malden, Medford, Chelsea and Revere. 

So I think that enforcing a `state_id` could potentially serve us well down the line. That said, if students are missing from section rosters, that's a problem. Could we find out why some students are missing state IDs? Who assigns them and how do they flow from the state to Somerville? Understanding the data flow will help us figure out if there's a solution beyond removing the enforcement. 

Educators not being able to log in is a huge problem. Did a principal or teacher mention this issue to you? I can't see why it would be important to have educator state IDs enforced in the database, so if removing the enforcement would make it easier for educators to log in I'm all for it. 

@kevinrobinson, curious to hear your thoughts when you have a moment!

**Comment by kevinrobinson** [comment]
If we're not using it, I'd vote for just removing it.  If we want to do other things with this field later, we can dig into the data quality then and pay for it when it'll provide some tangible value.

**Comment by alexsoble** [comment]
Hey all! @jhilde @kevinrobinson 

This PR changes the students export SQL file to allow for students with null State IDs: https://github.com/studentinsights/studentinsights/pull/1125

I looked through `educators_export.sql`, didn't see any line of SQL that was excluding educators with null state ID.

**Comment by alexsoble** [comment]
Verified that educators with null State ID are imported into Insight without a problem:

```
irb(main):003:0> Educator.where(state_id: nil).count
=> 197
```

**Comment by alexsoble** [comment]
Woohoo, now we have students with null state ID in the DB too! 

```
Loading production environment (Rails 5.1.3)
irb(main):001:0> Student.where(state_id: nil).count
=> 3
```
