### ISSUE TITLE
Fix bug in student risk level update during import process

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1057]
```
undefined method `school_type' for nil:NilClass
```

@jhilde, looks like this is related to new HS code. If you could take a look at it that would be great! Or if you're slammed just let me know and I'll tackle it.

**Comment by jhilde** [comment]
@kevinrobinson was kind enough to log it and fix it. #1054 

Looks like some students don't have a school?

**Comment by alexsoble** [comment]
Woah! Fast!
