### ISSUE TITLE
Add warning for admins to use IE!

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1067]
Note from me:

> I'm trying to think of ways to make it more difficult for us devs to develop on Chrome or at least give us big flashing warnings about it. Like maybe a big red banner on the top when you're logged in as the admin user reminding you that "this site is meant to use in IE"?

**Comment by karllhughes** [comment]
Maybe the warning could be shown only if `RAILS_ENV=development` since it's wanted for development purposes? Unless you want to show the warning to school administrators too.

**Comment by alexsoble** [comment]
I don't think we need this anymore because it's built into the PR checklist now (see #1289).

 Just different ways of reminding devs to do the same thing!
