### ISSUE TITLE
School Administrator Dashboard (built from Power BI)

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1082]
We mocked up a dashboard based on feedback from principals and based on PowerBI mock-ups that Uri and Jill did with Microsoft fellow.  Eric will be working on the initial stage of this by starting with attendance graphs.  PPT and screenshots attached.

# Example graph: Attendance
![screen shot 2017-09-22 at 9 44 29 am](https://user-images.githubusercontent.com/3209501/30749961-b4c6edde-9f7a-11e7-83cc-86d7de25f881.png)

**Comment by alexsoble** [comment]
👍 👍 

Uri's second issue on GitHub!

**Comment by kevinrobinson** [comment]
we made some of these!
