### ISSUE TITLE
Change Rollbar pricing to free

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1096]
It looks like Rollbar costs $19/month.  I think we could use the free plan instead, which lets you send up to 5k events a month (weirdly, if you do the Heroku addon it only lets you send 3k).  But either should be plenty for us!

**Comment by alexsoble** [comment]
Done! Good catch @kevinrobinson! Saved the district some money!

**Comment by kevinrobinson** [comment]
@alexsoble I didn't actually do this yet :\

**Comment by alexsoble** [comment]
@kevinrobinson I did it though. In the Heroku UI.
![screen shot 2017-10-01 at 3 48 07 pm](https://user-images.githubusercontent.com/3209501/31058814-f1024284-a6bf-11e7-85d7-fb142fd5c29e.png)

**Comment by kevinrobinson** [comment]
@alexsoble awesome, thanks!
