### ISSUE TITLE
Remove Low Income Status from Teacher View

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1099]
In speaking the school lawyer, he stated there was not enough of a compelling interest for teachers to have this information, like they would need around contact information, home language, or disability.  He recommended that we remove this column from the Class Roster and from the Student Profile.  The information should still remain in the School Overview filter page for people with school-wide access.

**Comment by jhilde** [comment]
Hey @snoopyuri, I've removed free & reduced lunch info from the following places:

- student profile
- student report (pdf)
- homeroom
- section

I'm wondering if it might make sense to leave it in student profile but only for people with districtwide or schoolwide access?

Let me know you thoughts.

**Comment by snoopyuri** [comment]
That's great.  Much appreciated.  I actually don't think it's needed in the student profile anymore.  I think it's information that's more needed by principals and district admin in the aggregate view rather than individual.

**Comment by jhilde** [comment]
Excellent, will push to prod soon.

**Comment by jhilde** [comment]
In prod, looks good.
