### ISSUE TITLE
Fix Grade Sorting in section and student section rosters

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#1108]
Looks like grade sorting doesn't like sparsely populated grades (e.g. a student doesn't have grades in several sections). This is likely caused by the comparison with nulls in the sort. 

Currently doesn't throw any errors, just sorts weird and non-deterministically if there are several nulls. Don't think an immediate patch or rollback is required.

**Comment by alexsoble** [comment]
@jhilde We've had issues in this area before, maybe it's time for a `sort_helper_spec.js`!

**Comment by jhilde** [comment]
@alexsoble 😃 I added one when I created the FlexibleRoster. Unfortunately I didn't have "" as any numbers in that test. Fixed that up.

Looks like it was the switch from _.isInteger to _.isNumber had a bit of a side effect. isInteger(NaN) is false while isNumber(NaN) is true. 

I think there may also have been a logic issue so I made it a little simpler as well.

**Comment by jhilde** [comment]
Fixed with #1110, will be deployed with some other little fixes.

**Comment by jhilde** [comment]
In prod, looks good.
