### ISSUE TITLE
Delete StudentServiceImporter

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1116]
It's been (see https://github.com/studentinsights/studentinsights/pull/1091), and per @alexsoble in https://github.com/studentinsights/studentinsights/pull/1090#issuecomment-331895526 there's an admin UI feature for this now, so we can just delete this class and related code (eg., rake or thor calls into it, specs).

**Comment by alexsoble** [comment]
@kevinrobinson On it! I built 'em so I'll delete 'em.
