### ISSUE TITLE
Idea: UI for educators to confirm Service end dates

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1117]
# Notes 

+ Now that we've landed #1105, we're asking educators about future end dates for services. Suggestion from @kevinrobinson: a UI that shows educators Services (for example, services that have been active the longest) and asks them to confirm if they're still active, discontinued, etc. so that we have some UI prompting to keep the data fresh and accurate

**Comment by kevinrobinson** [comment]
We did this!  There's a page to look at services overall (eg, for project leads to audit this as suggested), and the default end date is the end of the current school year now too.
