### ISSUE TITLE
Sequences of integer codes after a student name is confusing.

### ISSUE THREAD

**Issue by sentientmachine** [studentinsights/studentinsights#112]
On this page: students/8/profile?column=attendance

After the students name, it has two integers.  After you click on it, you can figure out later that it's the room number.  But hovering over that link should give me an idea of what this will tell me if I go there.

**Comment by kevinrobinson** [comment]
This should be addressed by the awesome work @BWieber is doing in https://github.com/studentinsights/studentinsights/pull/113 and https://github.com/studentinsights/studentinsights/pull/108!

**Comment by kevinrobinson** [comment]
@sentientmachine Thanks!  I'm closing this issue since the work is tracked in those pull requests and the umbrella issue https://github.com/studentinsights/studentinsights/issues/93.  Please comment or re-open if you have any other input!
