### ISSUE TITLE
Improve performance of Educator.save_student_searchbar_json

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#1120]
It looks like the component of the nightly imports taking the longest time is likely caching the json of students available in the student_searchbar.

Likely strategy to decrease the time a bit without taking the authorization logic out of Educator#is_authorized_for_student will be to limit the initial query of students to the educator's school (unless the educator is a districtwide_admin). 

See #1118.

**Comment by alexsoble** [comment]
Sounds good! 

I think another improvement we can make would be storing a variable with the JSON for all students in the system so we don't have to compute it for each districtwide admin.

**Comment by jhilde** [comment]
This was improved with #1127. Closing.
