### ISSUE TITLE
Beef up logging from imports

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#1121]
Plan to:

-- Use ImportRecord as a record of the overall import run, as it is currently.

-- Add ImportRecordDetail as a record of each importer (or job) that the import runs. This will have number of rows processed, rejected, and deleted. For most importers only the rows processed will be populated. For the new sections related importers, they will have the number of rejected rows. Eventually, they will also have the number of deleted rows once I change the way stale data is deleted from student_section_assignment and educator_section_assignment.

-- Add low level performance data for generating the searchbar json since we suspect that is causing the timing issue. (Turned on with an environment variable, so we can profile in production).

**Comment by alexsoble** [comment]
Hey, this sounds great @jhilde. Really thorough and well-thought-out. 

I had a branch in my local codebase that tackles this issue in a quick-and-dirty way: https://github.com/studentinsights/studentinsights/pull/1123

It stores some JSON in the database about import timing and prints it in the ErrorReport email.

If you don't mind, we could merge this first for some quick-and-dirty easier-to-access info about timing and then you can implement your more comprehensive solution, which I think will serve us really well especially as we add more districts. Let me know what you think!

**Comment by jhilde** [comment]
Sounds great!

On Sun, Oct 01, 2017 at 4:40 PM Alex Soble

<
mailto:Alex Soble <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hey, this sounds great
https://github.com/jhilde
. Really thorough and well-thought-out.

I had a branch in my local codebase that tackles this issue in a quick-and-dirty way:
https://github.com/studentinsights/studentinsights/pull/1123

It stores some JSON in the database about import timing and prints it in the ErrorReport email.

If you don't mind, we could merge this first for some quick-and-dirty easier-to-access info about timing and then you can implement your more comprehensive solution, which I think will serve us really well especially as we add more districts. Let me know what you think!

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/studentinsights/studentinsights/issues/1121#issuecomment-333405117
, or

**Comment by alexsoble** [comment]
OK, merging the ugly thing now! @jhilde

**Comment by kevinrobinson** [comment]
we did this!
