### ISSUE TITLE
Disabling Old Insights Link But Still Google-Able

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1133]
Tracked down the source of a few users who haven't been able to log in in the last couple of weeks.  Instead of going to Favorites or using our link, they Google "Student Insights" and come up with the old site that looks just the current site:

https://somerville-teacher-tool-demo.herokuapp.com/

Can we disable this?

**Comment by kevinrobinson** [comment]
Wow, good catch!  That's the demo site, with fake data used to show people the product.

We can look at hinting to Google about search rankings, which would probably be best.  In the short term, it might also be good to put a big button at the top of the demo site that says "Looking for Somerville or Fall River?"  We don't really want folks mistakenly typing their passwords into the demo site.

Search ranking is another consideration for multiple schools too, with search and discoverability benefits being for a single multi-tenant domain.

**Comment by kevinrobinson** [comment]
Another improvement here would be to add JS code that runs only on the demo site, checking that the entered username/password are the whitelisted demo accounts.  If not, it prompts the user to go somewhere else (eg., somerville.studentinsights.org) before ever sending anything to the demo server.  Another tiny guard against folks mistakenly entering their password into the demo site if they do end up there.

**Comment by alexsoble** [comment]
@kevinrobinson @snoopyuri How does this look? 

![screen shot 2017-10-05 at 10 23 13 am](https://user-images.githubusercontent.com/3209501/31235491-47bddee0-a9b7-11e7-9fc0-b9bf8494d198.png)

**Comment by snoopyuri** [comment]
That’s perfect to me!

Thanks

**Comment by alexsoble** [comment]
@snoopyuri Great, opened up a pull request to implement the new warning on the demo site: #1141.
