### ISSUE TITLE
Profile v2 - Allow saving services to the database and rendering them

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#115]
This is a part of https://github.com/studentinsights/studentinsights/issues/5.

Rough steps, using https://github.com/studentinsights/studentinsights/pull/51 and https://github.com/studentinsights/studentinsights/pull/54 as models.

In Rails:
- [x] https://github.com/studentinsights/studentinsights/pull/132 - Make migrations and models (for `services` and `service_types`), test in Rails console (@BWieber)
- [x] https://github.com/studentinsights/studentinsights/pull/158 - Read path for services in students_controller#profile
- [x] https://github.com/studentinsights/studentinsights/pull/158 - Add new controller action to enable saving, update specs

In React (@kevinrobinson):
- [x] https://github.com/studentinsights/studentinsights/pull/124 - Factor out `RecordService` component
- [x] https://github.com/studentinsights/studentinsights/pull/125, https://github.com/studentinsights/studentinsights/pull/131 - Update read path to show list of services
- [x] https://github.com/studentinsights/studentinsights/pull/131 - Update read path for "notes" to show older interventions and progress notes
- [x] https://github.com/studentinsights/studentinsights/pull/136 - Add `actions` and `api` to the UI code to enable saving
- [ ] Render custom intervention type in UI
- [ ] Fix UI bug on IE with note button width (see fix note button width: https://github.com/studentinsights/studentinsights/pull/126#issuecomment-188940902)

**Comment by kevinrobinson** [comment]
@BWieber I've got some time today and tomorrow, so am going to grab the next Rails tasks here to try to get this feature fully shipped this week.  Thanks so much for your help starting this off!  :+1:

**Comment by BWieber** [comment]
No problem thanks Kevin! I wish I had more time to dedicate 😼

**Comment by kevinrobinson** [comment]
@BWieber no worries, I'm thankful for all the help you've been able to give!  I'm just taking advantage of time I have while I do :)

**Comment by alexsoble** [comment]
"Allow saving services to the database and rendering them" . . . this we've got in production!
