### ISSUE TITLE
Document "How do I add Student Insights?" for district IT staff

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1157]

**Comment by snoopyuri** [comment]
Just saw this looking back at issues @alexsoble 

Looks like we've got a few district staff that can't get into Insights because they are not assigned to a specific school.  In the past, we'd just assign them to Healey and then give them district-wide access.

Two in particular, Christine Trevisone (SPED director) and Sarah Davila (ELL director) are looking to gain access, but can't.  Should I just change their school name in Aspen or is it the right time to make a change to bring in all staff regardless of school? @alexsoble

**Comment by alexsoble** [comment]
Hey @snoopyuri! This issue actually had a typo in its title, should say "Document "How do I add Student Insights?" for district IT staff". The idea is to provide a guide to John Breslin-type staff at other districts. 

That said, to answer your question — the way the system's set up right now, all folks with roles like Data Analyst, Superintendent, Assistant Superintendent, are assigned to the PIC. Do you think that would be a good solution for Christine and Sarah?

**Comment by snoopyuri** [comment]
That would work….shall I assign them to PIC and then it’ll pick them up?

**Comment by alexsoble** [comment]
Yep!

**Comment by snoopyuri** [comment]
Ok, they’re now assigned to PIC.  Hopefully, they’ll get picked up this afternoon.

**Comment by snoopyuri** [comment]
It seems that PIC people aren’t getting picked up.   I tried checking on a few of them including Sarah Davila again and they’re not showing up in my permissions page.  Can you check it out?

From: Harel, Uri
Sent: Wednesday, November 8, 2017 9:02 AM
To: 'studentinsights/studentinsights'; studentinsights/studentinsights
Cc: Mention
Subject: RE: [studentinsights/studentinsights] Document "How do I add Student Insights?" for district IT staff (#1157)

Ok, they’re now assigned to PIC.  Hopefully, they’ll get picked up this afternoon.

**Comment by alexsoble** [comment]
@snoopyuri Checking it out now! You're right, it looks like the PIC is not included in the default data import list — fixing that now. My mistake.

**Comment by alexsoble** [comment]
@snoopyuri The data for students/educators associated with the PIC is pretty interesting! I'll send around an email summary with details.

**Comment by snoopyuri** [comment]
Awesome, thanks!

**Comment by kevinrobinson** [comment]
some of the mechanics have changed since then, but we addressed the specific user issues, and have docs describing onboarding work.
