### ISSUE TITLE
Backfill IEP data gap

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1167]
# Notes

There was about a month in between our bulk IEP download and when we started the nightly IEP download process. This left a gap of missing IEPs in Insights. Data-wise, we need a fresh recent bulk download from EasyIEP. Code-wise, this will probably require re-visiting the bulk IEP import code, parts of which were changed in writing the nightly import path.

**Comment by alexsoble** [comment]
Got a fresh set of data this morning. The file name is `10-24-2017.zip`. Since we get a week's worth of IEP data flowing through to the app at any one time, and one week from 10/24 puts us at 10/30, this backfill will need to be shipped before Monday 10/30 in order to avoid creating another backfill. I'm going to aim to ship this on 10/29 in order to give one day's worth of wiggle room. I'm also going to add the "critical" tag because of the time urgency and the importance of not having gaps in this data source.

**Comment by alexsoble** [comment]
The task ran successfully. Of the two students @snoopyuri identified as missing IEPs, one now has an IEP in the system and the other might be a case of mistaken identity. Once I hear back from Uri will know if we're good or if we still have some work to do here.

**Comment by snoopyuri** [comment]
Just checked a bunch of students and they look great!

Sorry about the mistaken identity….it was the sister that was missing and she’s in now.

Way to go everyone and thanks!
