### ISSUE TITLE
Improvements to profile newsfeed

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#117]
@erose Here are our initial notes from talking in person at Code for Boston:
+[ ] 10% -> 10th percentile for STAR

**Comment by erose** [comment]
TODO:
  * find a student with discipline incidents
  * table-ize newsfeed

**Comment by erose** [comment]
- Add badges to newsfeed bubbles, make not so colorful
- Add title = "Full Case History" ???

**Comment by erose** [comment]
This has branched out into #217 #218 #219 and so should be closed. (I can't do this right now, I think I need the permissions).

**Comment by kevinrobinson** [comment]
:+1: I gotcha
