### ISSUE TITLE
Revised 2017 MCAS Scaled Scores & Level Names

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1171]
The State just released the MCAS results for 2017 in grades 3-8 and they look very different.  They got into Insights this morning with a few kinks:

+ SGP: Good news is that this is the same and is showing up in student graphs.  Yes (Thought I'd start with good stuff first :)

+ Proficiency Levels in grades 3-8:   Advanced (Old) = Exceeding Expectations (New): Proficient (Old) = Meeting Expectations (New); Needs Improvement (Old) = Partially Meeting (New); Warning (Old) = Not Meeting Expectations (New).    It seems that this would affect the y axis of the graphs in the student profile.  Hopefully, this can just be dealt with by renaming them.

+ Scaled Score - "The Biggie": Old MCAS is scaled 200 to 270.  New MCAS is in the 400 to 600 range.  I'm working on getting some conversion tables, which I'll attach here when I get them.  So when you look at a graph in the student profile, you'll see a student who has been hovering in the 200 range for years and then shooting up to the top of the axis.    Not sure how to tackle.  Do we make it a whole new graph?  Do we convert the new score to its old score equivalent so it fits on the graph?  Also is complicated by the fact that high school is staying the same, so those graphs don't change.

**Comment by alexsoble** [comment]
Thanks for investigating the impact of this change and writing up a detailed summary @snoopyuri! Hmmmm yeah that's some "off the charts" growth!
![screen shot 2017-10-19 at 1 16 18 pm](https://user-images.githubusercontent.com/3209501/31786987-ea4ee938-b4cf-11e7-9b03-c0699d8d7762.png)

My preferred approach would be to make a whole new graph for 2017-and-beyond-MCAS, and a whole new database model. Converting obscures the original data point which puts us into murky territory. I can start tackling this.

**Comment by alexsoble** [comment]
@snoopyuri How would you describe this new MCAS score? "New MCAS"? "2017 MCAS"? Is there an official name for this change?

**Comment by snoopyuri** [comment]
Here they’re calling it MCAS 2.0 or Next Generation MCAS.

**Comment by alexsoble** [comment]
@snoopyuri Thanks Uri! Helpful. Naming things is weirdly one of the hardest things in programming...

**Comment by alexsoble** [comment]
@kevinrobinson @jhilde Let me know if you think I'm traveling down a solid path with #1173 and if you have any suggestions or comments! Thanks!

**Comment by alexsoble** [comment]
@snoopyuri Could you post the mappings between scale scores and Exceeding Expectations, Meeting Expectations, Partially Meeting, Not Meeting Expectations? Are they four equal bands?

**Comment by alexsoble** [comment]
Did some digging into the data. One interesting thing I noticed: plenty of High School students have `most_recent_mcas_math_scaled` values that are using the "Next Gen" MCAS scales:

=> [202, 204, 206, 208, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 446, 456, 460, 464, 467, 469, 472, 474, 476, 478, 479, 480, 481, 482, 484, 486, 487, 489, 490, 492, 494, 495, 497, 498, 499, 501, 503, 504, 505, 507, 508, 510, 511, 513, 515, 516, 518, 520, 522, 524, 526, 528, 531, 533, 537, 540, 545, 552, 560]

Looks like these are 9th graders who took the test last May when they were 8th graders, so it makes sense that their latest MCAS scores would be in "Next Gen" format. 

```
# Script:

$ hs = Student.where(school_id: shs_id, enrollment_status: 'Active')
$ tests = hs.pluck(:most_recent_mcas_math_scaled)
$ tests.compact.uniq.sort
```

**Comment by alexsoble** [comment]
@snoopyuri Uri, one question we have: how familiar are teachers with the "Next Gen" MCAS format? If a teacher sees an MCAS score with a value of 500, for example, would they immediately recognize it as a "Next Gen" value? Or would there be confusion/surprise at seeing a value outside the range they've seen in past years? (cc @kevinrobinson) 📊

**Comment by snoopyuri** [comment]
Crazy Idea: What if we did very little....
1) Leave the graphs as is and not include any scores above 270 (that graph remains the old MCAS)
2) On the student profile, show the most current MCAS score whether it's the 250 or 450 scale, which it does now.  The only thing to add on the student profile would be the new label if it's a MCAS 2.0 score (ex. Exceeding, Meeting, Partially, or Not Meeting)
3) SGP remains the same, nothing to do
4) Student overview page remains the same, since it just shows a number score
5) Next summer, once the 2nd data point for MCAS 2.0 comes on board, we then replace the graph in the student profile to reflect new scores.  If people want to see the old scores, they can just go into the student overview and scroll through history.

Thoughts?

**Comment by alexsoble** [comment]
@snoopyuri Yeah, in some ways I was thinking something very similar! I did most of the coding to have two sets of graphs yesterday, which I think is important so that teachers can see a full MCAS history in graphs. But I was thinking something similar about just showing the most current MCAS score whether it's the 250 or 450 scale and leaning on teachers to tell the difference. In my mind the most important question there is if teachers might be surprised/confused by the new scale or if they'll recognize it automatically.

**Comment by snoopyuri** [comment]
I think they’ll recognize pretty quickly, especially since they’re seeing rosters in their buildings now.

The important thing will be showing them the 450 score alongside the performance level “Meeting expectations”, etc.

**Comment by alexsoble** [comment]
Moving work over to #1178.
