### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#1177]
In #1161 we were contemplating some larger architectural changes. One piece we'll eventually need to do is migrate to React 16. So I've created this issue to track that effort.

Details of the migrations required are in [this blog post from React](https://reactjs.org/blog/2017/04/07/react-v15.5.0.html).

Essentially, two gating items:

- PropTypes - we need to move our `PropTypes` from the core `react` library to the new `prop-types` library. 
- Component creation - we need to move from `React.createClass` to classes that extend `React.Component`. This also changes lifecycle methods and bind of `this`.

I took a quick look at `react-codemod` but it seemed that it had trouble picking up our classes. Perhaps I was missing something or perhaps it was confused by our use of `window.shared`.

**Comment by alexsoble** [comment]
I'd like to close this since we're already doing a major Javascript refactor with @Jngai's ES6 work and there's no immediate need to upgrade to React 16. We can re-open when this becomes a higher priority.
