### ISSUE TITLE
Use ES6 modules and import/export everywhere to create single entrypoint to JS

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1180]
# Notes

+ Currently our JS uses a mix of `import`/`export` and stuffing JS definitions into `window.shared`.
+ To move to a more modern JS tooling like webpacker or create-react-app, we'll need to create a single point of entry to our JS using modern ES6 `import`/`export`.
+ This is a dependency to unblock #1161.

# What does this look like?

+ See #974 as an example of how to move a JS file away from `window.shared` and into an ES6 module. 

# Files to convert to ES6 modules with import/export
**top level:**
+ [x] datepicker_config.js (https://github.com/studentinsights/studentinsights/pull/1182)
+ [x] session_timeout_warning.js (https://github.com/studentinsights/studentinsights/pull/1182)
+ [x] student_searchbar.js (https://github.com/studentinsights/studentinsights/pull/1182)

**components:**
+ [x] collapsable_table.jsx (https://github.com/studentinsights/studentinsights/pull/1224)
+ [x] fixed_table.jsx (https://github.com/studentinsights/studentinsights/pull/1224)
+ [x] flexible_roster.jsx (https://github.com/studentinsights/studentinsights/pull/1224)
+ [x] slice_buttons.jsx (https://github.com/studentinsights/studentinsights/pull/1224)
+ [x] slice_panels.jsx (https://github.com/studentinsights/studentinsights/pull/1224)
+ [x] star_charts_page.jsx ( (https://github.com/studentinsights/studentinsights/pull/1224 and https://github.com/studentinsights/studentinsights/pull/1223)
+ [x] students_table.jsx (https://github.com/studentinsights/studentinsights/pull/1224)

**helpers:**
+ [x] feed_helpers.jsx (https://github.com/studentinsights/studentinsights/pull/1483)
+ [x] filters.jsx (https://github.com/studentinsights/studentinsights/pull/1224)
+ [x] from_pair.jsx (https://github.com/studentinsights/studentinsights/pull/1483)
+ [x] graph_helpers.js (https://github.com/studentinsights/studentinsights/pull/1483)
+ [x] mixpanel_utils.jsx
+ [x] profile_details_style.jsx (https://github.com/studentinsights/studentinsights/pull/1564)
+ [x] prop_types.jsx (https://github.com/studentinsights/studentinsights/pull/1608)
+ [x] react_helpers.jsx (https://github.com/studentinsights/studentinsights/pull/1608)
+ [x] routes.jsx (https://github.com/studentinsights/studentinsights/pull/1224, https://github.com/studentinsights/studentinsights/pull/1564)
+ [x] sort_helpers.jsx (https://github.com/studentinsights/studentinsights/pull/1564)
+ [x] theme.jsx (https://github.com/studentinsights/studentinsights/pull/1224, https://github.com/studentinsights/studentinsights/pull/1564)

**homeroom_table:**
+ [x] homeroom_table.jsx (https://github.com/studentinsights/studentinsights/pull/1292)
+ [x] main.jsx (https://github.com/studentinsights/studentinsights/pull/1182)

**restricted_notes:**
+ [x] main.jsx (https://github.com/studentinsights/studentinsights/pull/1182)
+ [x] restricted_notes_page_container.jsx

**school_overview:**
+ [x] main.jsx (https://github.com/studentinsights/studentinsights/pull/1182)
+ [x] school_overview_page.jsx

**section:**
+ [x] main.jsx (https://github.com/studentinsights/studentinsights/pull/1182)
+ [x] section_header.jsx
+ [x] section_page.jsx

**service_uploads:**
+ [x] main.jsx (https://github.com/studentinsights/studentinsights/pull/1182)
+ [x] new_service_upload.jsx
+ [x] service_type_dropdown.jsx
+ [x] service_upload_detail.jsx
+ [x] service_uploads_page.jsx

**star_math:**
+ [x] main.jsx (https://github.com/studentinsights/studentinsights/pull/1182)

**star_reading:**
+ [x] main.jsx (https://github.com/studentinsights/studentinsights/pull/1182)

**student_profile:**
+ [x] academic_summary.jsx
+ [x] api.jsx
+ [x] attendance_details.jsx
+ [x] bar_chart_sparkline.jsx
+ [x] editable_text_component.jsx
+ [x] educator.jsx
+ [x] ela_details.jsx
+ [x] help_bubble.jsx
+ [x] highcharts_wrapper.jsx
+ [x] main.jsx (https://github.com/studentinsights/studentinsights/pull/1182)
+ [x] math_details.jsx
+ [x] note_card.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] notes_details.jsx
+ [x] notes_list.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] page_container.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] parse_query_string.jsx
+ [x] pdf/student_profile_pdf.js (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] profile_bar_chart.jsx
+ [x] profile_chart.jsx
+ [x] profile_chart_settings.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] profile_details.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] provided_by_educator_dropdown.jsx (https://github.com/studentinsights/studentinsights/pull/1567)
+ [x] quad_converter.jsx (https://github.com/studentinsights/studentinsights/pull/1567)
+ [x] record_service.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] risk_bubble.jsx
+ [x] scales.jsx
+ [x] service_color.jsx
+ [x] services_details.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] services_list.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] sparkline.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] student_profile_header.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] student_profile_page.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] student_sections_roster.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] summary_list.jsx (https://github.com/studentinsights/studentinsights/pull/1739)
+ [x] take_notes.jsx (https://github.com/studentinsights/studentinsights/pull/1735)

### Final step!
When we're done, we can remove:
+ [x] legacyHelpers (https://github.com/studentinsights/studentinsights/pull/1608)
+ [x] legacyVendor (https://github.com/studentinsights/studentinsights/pull/1757)
+ [x] check spec files (eg, rename filenames, move next to code) (https://github.com/studentinsights/studentinsights/pull/1757, https://github.com/studentinsights/studentinsights/pull/1739)

Here's related work that's been split out to smaller pieces for later:
- https://github.com/studentinsights/studentinsights/issues/1760
- https://github.com/studentinsights/studentinsights/issues/1759
- https://github.com/studentinsights/studentinsights/issues/1758
- https://github.com/studentinsights/studentinsights/issues/1761

**Comment by kevinrobinson** [comment]
@alexsoble also these ones are weird and so I took them off this list:
```
 application.js
 env.js.erb
 react-compatibility.js
```

**Comment by kevinrobinson** [comment]
One suggestion is that the real goal is not "ES6 modules" per se, but ES6 modules that don't have side effects when you import them, and just expose values and functions.

That will be simple for most files (components or classes or functions), but there's a few places where this is strange.  One is code like `datepicker_config.js` that runs globally and other product feature depend on.  The other is the bits that check the "body" classes.

For those, if we modulify them we can call them all in the bottom of application.js like this:
```
import datepickerConfig from './datepicker_config.js';
import homeroomMain from './homeroom/main.jsx';
import schoolOverviewMain from './school/main.jsx';

datepickerConfig();
if ($('body').hasClass('homerooms') && $('body').hasClass('show')) return homeroomMain();
if ($('body').hasClass('schools') && $('body').hasClass('show')) return schoolOverviewMain();
```

That keeps everything how it's working now, and is mostly a mechanical change.  But it would remove all the side-effects from the modules and make explicit what's happening - on load we run a bunch of stuff.

**Comment by kevinrobinson** [comment]
@alexsoble I did the top level and "main" files in https://github.com/studentinsights/studentinsights/pull/1182/commits/dfd6db7d87b09bc4dc7dbea231bb28f5ee44d553 within https://github.com/studentinsights/studentinsights/pull/1182.

**Comment by alexsoble** [comment]
Closing because this ended up not being a blocker to deploying webpack thanks to @kevinrobinson's workaround.

**Comment by kevinrobinson** [comment]
@alexsoble Let's still do this!  It'd be great to be in a world where we can just import/export code, and this can also enable tree shaking and some other good optimizations.

**Comment by alexsoble** [comment]
shake those 🌳 🌲 🎄 s

**Comment by Jngai** [comment]
@kevinrobinson @alexsoble this looks fun.

**Comment by Jngai** [comment]
@alexsoble Will you confirm that this is my next task? I will start working on this next week.

**Comment by gabivoicu** [comment]
This list is out of date, `student_profile` is the only one that still needs migrating.

**Comment by kevinrobinson** [comment]
@gabivoicu ah thanks!  If you went through and checked these, can you check them off from the list above?  You don't need to go through and link to the PRs.

Also, I check the first few, and noticed that there's some files that were converted to ES6, but are still listed in the `legacy.js`files (maybe for good reason, until the migration is done, not sure without looking more closely).  So I just added that to the issue description as a last step to close out this whole issue.  If it's mostly just the student profile components left, then we're almost there! :)

**Comment by gabivoicu** [comment]
@kevinrobinson I can't check them off, it's greyed out for me. I've finished `student_profile/academic_summary.jsx` last night and will pick another one tonight, I'll make a note of it here afterwards.

**Comment by kevinrobinson** [comment]
@gabivoicu ah cool I'll go update the checklist then, thanks!

**Comment by gabivoicu** [comment]
I've migrated `academic_summary`, `bar_chart_sparkline` and `profile_chart`; other ones in `student_profile` are already migrated (`api`, etc).

**Comment by kevinrobinson** [comment]
With https://github.com/studentinsights/studentinsights/pull/1739, going to consider this 🚢ed.  Related other JS simplification work is noted in the description and tracked on the backlog.
