### ISSUE TITLE
Labels in Student Profile (Services) & Restricted Notes (Student Name)

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1186]
I think these two are very easy:

+ Student Profile: The title of the right-most title still says "Interventions" which was our naming convention in V1.0.  It should be renamed to "Services/Notes" to match with what they see when they click. 

+ Restricted Notes: When an administrator opens up Restricted Notes, the name of the student doesn't appear.  I've seen a few cases where the admin has to click backwards to verify they're entering the notes for the right student.  Can we add the student name to it?

**Comment by alexsoble** [comment]
Meeting with @snoopyuri about this now — we've seen some mistakes where educators are entering restricted notes for the wrong student and have to go back and edit, so this is really important to change.

**Comment by kevinrobinson** [comment]
we did this!
