### ISSUE TITLE
Fix or remove STAR charts

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1192]
The changes to the overview page adding counselor and HS house filters in https://github.com/studentinsights/studentinsights/pull/1158 introduced changes that broke the STAR chart pages (specifically, requiring the school to be passed and expecting properties on it https://github.com/studentinsights/studentinsights/commit/bfbf9983d86db8af8b13edc67a76299e16cb61fc#diff-66cf517f6e4bb7cc45a680baba80ee1dR276).  (cc @jhilde, it's a good idea to grep and find all the call sites for a component when adding new required props)

Monitoring shows that no one tried to use these pages, and we caught this before it affected anyone.   Let's either fix this and add a smoke test for these charts, which is straightforward and would have caught the bug in https://github.com/studentinsights/studentinsights/pull/1158.  Or, since we haven't really been supporting these charts as first-class features, we could just remove them altogether if they're weight we have to carry that no educators benefit from.  The code is always in source control if we want to add them back.

@alexsoble @snoopyuri Any thoughts on this?

**Comment by snoopyuri** [comment]
Since there isn’t any usage, maybe we should pull out remove them for now and bring them back on another iteration (maybe with the dashboard where we’ll be training administrators to use this deeper level of data analysis)

**Comment by jhilde** [comment]
Ughhh...sorry about that. You'd think there would be an easy way to validate all component usage against the prop-types in eslint but I don't think there is.

Grepping it is.

**Comment by kevinrobinson** [comment]
@jhilde hehe sounds like you want a type system :)  Yeah no worries, it's a totally normal mistake and it's my fault there's not even any smoke tests to catch this.  Grepping won't be so bad here since the codebase isn't that big.  I don't know of linter rules to catch this (the linter would have to have global knowlege of all modules since you can't tell the required props without looking in the file) but one-line smoke tests catch changes like this this easily.  We could do a pass to add those in for every component now that tests are faster, which I'd be up for helping with.  Alternately, if you were excited about static typing you could experiment with https://flow.org/  In my limited experience, it's been more trouble then it's worth (maybe that's changed as it's matured), but its "weak mode" adds some level of type checking without any changes from developers.

For this issue, sounds like the consensus here is to remove, so let's do that then!

**Comment by jhilde** [comment]
@kevinrobinson this will be corrected with the #1212. I intentionally made the school is null simply return false (i.e. don't display this element).

Experimenting with Jest snapshots as a way to add basic coverage for React components without current tests. #1216.

**Comment by kevinrobinson** [comment]
we removed these in https://github.com/studentinsights/studentinsights/pull/1223
