### ISSUE TITLE
Columns aren't sorting on admin permissions page

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1194]
Headers look like they should sort, but don't work.

<img width="1216" alt="screen shot 2017-10-25 at 12 10 16 am" src="https://user-images.githubusercontent.com/1056957/31980240-1b1f9dda-b919-11e7-8283-a1ebf1b99291.png">

The URL updates with `sort_order` but `direction` doesn't.  Updating it manually in the URL doesn't work either.

**Comment by alexsoble** [comment]
Ah, looks like what happened is that I overwrote the `index` action of the administrate controller, then administrate's API introduced a breaking change that I missed.

I see a solution with lots of upvotes here: https://github.com/thoughtbot/administrate/issues/442 so I'll try introducing that.

**Comment by alexsoble** [comment]
Looks like there's a second problem here which is that administrate doesn't support sorting by `belongs_to` relationships out-of-the-box.

**Comment by alexsoble** [comment]
Sorting is now fixed for every column except the Homeroom column, so I'm going to close this issue and open a more specific one about Homeroom.
