### ISSUE TITLE
Reduce seed data for demo site

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1198]
Heroku says: `[warning] Database disruption imminent, row limit exceeded for hobby-dev database on Heroku app somerville-teacher-tool-demo`.  Here's the relevant Heroku docs: https://devcenter.heroku.com/articles/heroku-postgres-plans#hobby-tier

We don't need that much data in the demo site, let's just remove some students or schools or homerooms, etc.

**Comment by KaraAJC** [comment]
I could help with this, is that cool?

**Comment by jhilde** [comment]
Hey @KaraAJC. This is a great way to get to know our data model. I'd say go for it!

My only advice is to keep at least one elementary school (likely Healey) and Somerville High School.

Let us know if you have any questions!

**Comment by KaraAJC** [comment]
OK! sounds good! If there are any important representations I shouldn't remove, in terms of interesting homerooms or students that often get used as an example, let me know..

**Comment by kevinrobinson** [comment]
@KaraAJC awesome, and nice to meet you!  I updated the issue to have a link to the Heroku docs about these limits if that's helpful (so you know what the limit is and can check how many rows are in the database locally).  This will help the school district avoid having to pay more money each month for the demo site! 💰

**Comment by KaraAJC** [comment]
@kevinrobinson OMG you read my mind! I've been researching the error specifically, after doing a quick read of the seed file and thinking "doesn't look bad to me" 😸 
I'd like to be able to review the actual row counts by table, as [this blog post suggests](https://rvlasveld.github.io/blog/2013/09/30/heroku-database-size-warning-finding-the-problem/)
so THANKS! 
That will definitely help!

**Comment by alexsoble** [comment]
Oh hi there @KaraAJC! Nice to see you on here and thanks for tackling this issue! 🙌

**Comment by alexsoble** [comment]
@KaraAJC closed this last month! Nice job @KaraAJC! Closing this issue.
