### ISSUE TITLE
Improve layout of school overview and STAR filters for smaller screens

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#12]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/437.

The layout doesn't look quite right on older IE browsers that have smaller screens.  We only saw this in one user testing session and don't have great info on how to reproduce, so this might take some poking around in something like https://www.browserstack.com/.

**Comment by kevinrobinson** [comment]
The layout doesn't look quite right on older IE browsers that have smaller screens.  We only saw this in one user testing session and don't have great info on how to reproduce, so this might take some poking around in something like https://www.browserstack.com/.

**Comment by kevinrobinson** [comment]
Reproducing the problem on browserstack for:
- Windows 7, IE11 at 1270x768
- Windows 8.1, Metro 11 at 1024x68

<img width="1272" alt="screen shot 2016-02-25 at 2 22 50 pm" src="https://cloud.githubusercontent.com/assets/1056957/13331505/c2559960-dbcb-11e5-9717-390023fac09a.png">
<img width="1143" alt="screen shot 2016-02-25 at 2 24 21 pm" src="https://cloud.githubusercontent.com/assets/1056957/13331504/c254eae2-dbcb-11e5-8688-846b2a1bf311.png">

**Comment by kevinrobinson** [comment]
Can reproduce on Windows 7, IE11 at 1329x737.

**Comment by kevinrobinson** [comment]
Also reported by @jgeiser this morning.

**Comment by kevinrobinson** [comment]
Fixed in https://github.com/studentinsights/studentinsights/pull/225.
