### ISSUE TITLE
Fix 10/26 monitoring fail

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1205]
This morning educators were blocked from accessing Insights. Somerville's physical LDAP server was down because of a power outage. Educators were not able to log in for around 3 hours because the offline LDAP server could not authenticate them.

One aspect of this issue is that the dev team didn't get clear or urgent enough monitoring messages about this failure. I got alert emails from Logentries — did you @jhilde @kevinrobinson? — but I get frequent emails from Logentries and many of them are about less urgent issues, so I didn't realize these were critical. 

In particular it would be good to have alerts distinguish absolutely critical failures (educator cannot login) from bad but less critical failures (a slow JSON endpoint times out).

This issues is open ended right now and could go in a couple of directions. I'd like to surface a couple of possibilities for how to address this: 

## 1. Improve Logentries settings

This is something @kevinrobinson and I have looked at before. Logentries has an error tagging system, and we dug into it before in order to turn off alerts for some of the Memory Errors that made Heroku unhappy but weren't blocking user experience and weren't immediately addressable: 

![screen shot 2017-10-26 at 11 29 58 am](https://user-images.githubusercontent.com/3209501/32065016-29770214-ba41-11e7-8a2d-e226b6735c29.png)

A couple of limitations to this strategy. "Request timeout" can mean very different things if it's a login request versus a JSON endpoint request — that can be the difference between "educator can't login" and "educator's experience on a specific page is disrupted." So that's a very blunt category. 

Another issue is that Logentries doesn't have some of the bug-fix-collaboration features that Rollbar does, like including all collaborators on the same email and allowing collaborators to mark bugs as fixed.

## 2. Move away from Logentries and toward Rollbar for backend error monitoring

Currently we use Rollbar for client-side error monitoring and reporting and Logentries for server-side monitoring and reporting. Rollbar has some good bug-fix-collaboration features that I mentioned above, like including all devs on error reporting emails instead of messaging devs separately. 

Here's the Rollbar ruby gem: https://github.com/rollbar/rollbar-gem. It was last updated 2 months ago. It's CI build on the README is listed as "cancelled", which is unfortunate. 

## 3. Use a different backend error monitoring service

If we're wary of leaning all the way into Rollbar for backend error monitoring and folks have had great experiences with other error monitoring systems, we could go with a totally different option. I've had good experiences using Airbrake for backend (and front-end) error monitoring. 

##  4. Write more custom error monitoring emails (and/or texts)

For me, the custom error mailer we wrote for the nightly data import process has provided a good dev experience. The email subjects it uses are clear and instantly recognizable, we can customize it to send exactly the data we want about the process, and it's free / never tries to upsell us. 

We could write another custom error monitoring service that emails/texts us when Somerville's LDAP server throws an unexpected response. Downside to this: it's another code surface to maintain, if we ship a bug in our own error monitoring we have to go fix that bug in addition to fixing the bug in the service we were trying to monitor.

## Thoughts?

Feedback/reactions from @kevinrobinson, @jhilde, other folks with background/experience in error monitoring? @gabivoicu? 

After writing this up, my preference would be to first try switching to Rollbar for our backend error monitoring and see what that dev experience is like for a month or two.

**Comment by alexsoble** [comment]
Adding one more thing to an already long Issue: I think adding SMS or push notification alerts for true critical issues would be helpful, at least for me. I was walking to work when these login failures started happening and wasn't checking my email. If we got SMS pushes on login failures I would have known to check my email and find out what was going on. In the case of a bad PR blocking logon, I could have swerved into a cafe to revert.

**Comment by kevinrobinson** [comment]
we did a lot of this!
