### ISSUE TITLE
Risk Levels Need Re-Calculating with New MCAS

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1207]
Just got a heads up from a teacher that the Risk Levels might be off because of the new MCAS levels, since we're not using Proficient, Needs Improvement, and Warning anymore.  And I think that is the same for the tool-tips that Paul Mitchell created that still refer to those categories.

**Comment by jhilde** [comment]
Started to look at this a bit @snoopyuri. Doesn't look like the risk levels were changed to the new levels. Happy to take a look unless @alexsoble wants to continue since you've been doing the Next Gen MCAS work.

**Comment by alexsoble** [comment]
Go for it @jhilde! 👍

**Comment by alexsoble** [comment]
@jhilde is going to dive into the current state of risk levels for students with "Next Gen" scores + think about ways we can start to extract some of this as patterns!

**Comment by jhilde** [comment]
🚢 with #1225
