### ISSUE TITLE
Remove Docker setup

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1209]
Based on looking at this for https://github.com/studentinsights/studentinsights/pull/1182#issuecomment-339659601 it seems like no one must have been using this since it would have required changes to the `database.yml` in order for the Rails container to connect to the database (ie, `postgres` username and `postgres` host).

**Comment by kevinrobinson** [comment]
Are folks using Docker?  Please 👍 or 👎 on this comment.  Thanks!

@alexsoble @jhilde @Jngai @gabivoicu @KaraAJC @edavidsonsawyer

**Comment by jhilde** [comment]
I stopped using docker in an attempt to see if it improved the speed of browserily, it didn't. But since I cleaned up my machine, I haven't used it. I think I did something to fix the database.yml issue early on. 

I'd say, unless one of us is actively using docker, don't worry about it.

**Comment by kevinrobinson** [comment]
hmm looking through the Docker for Mac issues it seems like it's a hot mess: https://github.com/docker/for-mac/issues/1358, https://github.com/docker/for-mac/issues/77, https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/158.  The last one in particular does not sound optimistic about any uses cases watching lots of files for changes.

**Comment by gabivoicu** [comment]
Not using Docker, and having worked w/ Docker for Mac before I could add that it's not as stable as would be ideal for production so removing it would probably be a good idea (especially since it appears people aren't using it).
