### ISSUE TITLE
Consolidate risk level bubble styling

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#121]
This is done in `.warning-bubble`, `#risk-pill` and in the `student_profile_header` component (with https://github.com/studentinsights/studentinsights/pull/108).  Let's pull this out this styling into a single SCSS file defining these classnames so it's defined in one place.

**Comment by kevinrobinson** [comment]
As a separate improvement, it'd be great to have the React component implementation optionally show the explanation text we have on the profile v1 page on hover.

**Comment by BWieber** [comment]
Hi Kevin, 

I took a look at these stylings, and they all have their own particular flavor. For instance the `padding` and `border-radius` are different for each of them. They do however share many elements. How would you best proceed to take the similar qualities into a `.bubble`? My initial feeling is that it would lead into the creation of two more classes.

**Comment by kevinrobinson** [comment]
@BWieber Awesome, thanks for taking a look at this!  I think the overall goal is to simplify the code here, since we have three different implementations of what is essentially the same feature :)

So I think the work here would involve:
- Pick which risk bubble implementation looks the best and has the simplest code
- Add a new SCSS file (maybe `risk_bubble.scss`)
- Define any rules for the risk bubble within that file using a single root class name, and nesting any other related styling within that.  This might be as simple as moving the code from somewhere else into here.
- Updating the other places that show risk bubbles to use this new class name
- Remove the old styles

The React code would also be updated to remove the related inline styles, and just use the shared CSS class.

Does that help, or anything else I can clarify?  You should definitely feel free to just jump in and try this too :)

**Comment by kevinrobinson** [comment]
see also https://github.com/studentinsights/studentinsights/issues/151#issuecomment-204855879

**Comment by erose** [comment]
@kevinrobinson @BWieber What's the status of this?

**Comment by BWieber** [comment]
I thought this was finished, actually! If not, I'll get on it tonight :)

**Comment by erose** [comment]
@BWieber I think you're the person most qualified to know that :}, so if you think it's finished it's finished! (I'll give you permissions to close the issue.)
