### ISSUE TITLE
Assessment 4 year charts not displaying properly

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#1217]
Taking a look at Next Gen MCAS in production data for Somerville. It looks like the assessment 4 year charts are not properly rendering. No errors are thrown by the datapoints are missing.

@alexsoble @kevinrobinson I'm unlikely to have time to take a look at this soon. It's the weekend, but seems to be across students and schools.

**Comment by kevinrobinson** [comment]
This looks like it's related to Highcharts, the STAR charts don't have the data you'd expect either (compared to the sparklines above).  Locally this doesn't look right either, but haven't looked more closely yet.

**Comment by jhilde** [comment]
Thank you @kevinrobinson!!!!
