### ISSUE TITLE
Update development data or UI code to handle no next-gen MCAS data

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1219]
This is what comes up locally clicking into an academic details page on the student profile page:
<img width="558" alt="screen shot 2017-10-28 at 9 27 05 am" src="https://user-images.githubusercontent.com/1056957/32134770-33c718b2-bbc2-11e7-85c4-0ab4c7f55922.png">

Not sure whether best to handle this in: data generators for local development, querying in Rails, or in the UI.

Related to https://github.com/studentinsights/studentinsights/pull/1178.

**Comment by alexsoble** [comment]
@kevinrobinson Some students will have both types of MCAS data, some will have next gen-only (this year's 3rd graders) and some will have old-only (this year's 10th-12th graders), and some will have neither (PK through 2nd graders). I think the right thing to do here is remove `isRequired` from both old MCAS and next gen MCAS prop types.
