### ISSUE TITLE
Catch-and-handle errors thrown by external LDAP when users try to log in

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1227]
This is part of the same incident recovery as #1205.

On 10/26 a power outage at one of the schools in Somerville caused Somerville's LDAP system to go down, which meant that users couldn't authorize and log in to Insights. 

Once we catch-and-handle errors thrown by LDAP, we can make two distinct improvements: 

+ [ ] Surface a message to the educator telling her/him why login has failed. 
+ [ ] Send a high-priority alert to devs about the issue.

**Comment by alexsoble** [comment]
Best way to test this would probably be to make our own LDAP server to test with and have it just hang and never respond when it gets a request to simulate the power outage situation.

**Comment by kevinrobinson** [comment]
We alert on this through Rollbar, but don't want to surface internals about login failures to end users.  In the case of incidents, we can set `STATUS_MESSAGE` to share updates with folks about what's going on.
