### ISSUE TITLE
Sections missing for most high school students

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#1229]
Educator texted @snoopyuri today indicating high school students were missing sections. 

Upon investigation, I realized that when the `StudentSectionAssignmentImporter` and `EducatorSectionAssignmentImporter` are run with a school scope, all assignments for other schools are deleted as being stale.

@alexsoble ran the imports to bring in the data for Capuano which inadvertently caused the assignment data for all other schools to be deleted.

As a stopgap, @alexsoble ran the full import to restore the assignment data. Thank you!

**Comment by alexsoble** [comment]
This is healed so I'm going to close the issue.

**Comment by jhilde** [comment]
🚢 the permanent change with #1230.
