### ISSUE TITLE
Fix slowness on absence dashboard

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1244]
@edavidsonsawyer, wanted to leave some ideas and notes here before our call this afternoon! 

The first step should be to gather baseline data on how long this page takes to load using demo data or semi-anonymized data. 

Check out the `log_timing` method in `application_controller.rb`, useful tool for gathering some baseline data on how long the queries run before we optimize them. Without baseline data there's no way to know if the optimizing worked! You can change the demo scripts to make more absences if you feel that would get you slightly more dense data to work with.

Looks like we have N+1 issues to optimize. These lines in particular look an N+1 problem to me:

```
dashboard_students = active_students.map { |student| individual_student_dashboard_data(student) }

def individual_student_dashboard_data(student)
  HashWithIndifferentAccess.new({
    first_name: student.first_name,
    last_name: student.last_name,
    homeroom: student.try(:homeroom).try(:name),
    absences: student.absences.order(occurred_at: :desc)
    }
  )
end

```

Check out the Rails Guides to solving N+1 problems by using eager loading: http://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations

**Comment by alexsoble** [comment]
Suggestion: maybe add 450 demo students to the fake school as you record baseline speeds to simulate the ~450 Healey students in this view.

**Comment by edavidsonsawyer** [comment]
@alexsoble #1246 should help. Locally that has the query 300% faster using 500 students. Which makes sense because it's using 1/3 the queries.

**Comment by edavidsonsawyer** [comment]
#1254 is the biggest gain that can easily be made on the client side, since it was just an oversight. Locally I have a bunch of changes that slightly improve performance, but they require some extensive rework of the dashboard component. Let's see how this change plays first.

**Comment by edavidsonsawyer** [comment]
@alexsoble, can you give this a look when you get the chance?

**Comment by alexsoble** [comment]
Heyyyy we fixed the slowness and now the page is loading pretty normally, so time to close this issue and have a mini online party @edavidsonsawyer! 🎉 🎉 🎉 🎉
