### ISSUE TITLE
Best way to view Student Report PDF in VM?

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1248]
I'm working on verifying the Student Report PDF in an Internet Explorer system. I'm having a problem with the VirtualBox VM (IE 11, Windows 7) where I get stuck in a circular loop and the VM refuses to display the PDF: 

![stuck](https://user-images.githubusercontent.com/3209501/32579349-25e280d2-c4a6-11e7-83ca-7d884147c91a.png)

Are other folks getting stuck here as well? Or are you able to see PDFs in your VM?

**Comment by jhilde** [comment]
Hmmm, I use VMWare Fusion with Windows 10. IE11 prompts me to open or save the download. Both work properly. Unfortunately VMWare Fusion isn't free.

**Comment by alexsoble** [comment]
Answered this one with @kevinrobinson!

1. Launch a Windows VM with the targeted OS/IE version 
2. Go to get.adobe.com/reader in the VM
3. Install Adobe Acrobat in the VM
4. Try opening some PDFs in your VM!
5. If PDFs are openable, save a "Snapshot" so that you can access this VM state easily
6. Make sure you are logged out of Insights in your Snapshot state and that no student report PDFs are lying around your Downloads folder 

TOOD: Document in README

**Comment by alexsoble** [comment]
closed by #1364!
