### ISSUE TITLE
Handle educators who are authorized by LDAP but not in Aspen/X2

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1249]
Extracting this from #1242:

Let's surface a useful error message to the educator trying to log in who are authorized by LDAP but don't have a database record in the system sent down to us from Aspen/X2. 

The message could include some next-steps text like "Contact your school secretary to check on whether your data has been added to Aspen/X2. If your data has been entered into Aspen, try again tomorrow since Student Insights syncs with Aspen/X2 nightly."

**Comment by kevinrobinson** [comment]
We've done other work on this since, but all login failure error messages are still uniform and that's good, we don't want to leak anything about discrepancies between parts of the login system.
