### ISSUE TITLE
Verify explanation about DiscontinuedService records with no service_id

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1251]
We think they're in the database because of `ServiceUploads `that were then deleted. Deleting a `ServiceUpload` deletes its services through a cascade, but there's no cascade down to discontinued services.

Best way to verify this is to match up all the dates of the discontinued services with deleted service uploads.

We should do this before we blow up all the discontinued service records to finish the work of #1165.

**Comment by alexsoble** [comment]
# Overall scope of problem 

```
irb(main):014:0> Service.count
=> 2352
irb(main):015:0> Service.last.id
=> 4397
irb(main):016:0> 4397 - 2352
=> 2045
```

There are 2045 service ID records that were deleted from the database.

**Comment by alexsoble** [comment]
# Ranges of missing Service IDs

I used this script to locate ranges of missing IDs:

```
irb(main):017:0> (0..4397).step(1).each do |n|
irb(main):018:1* puts Service.find_by_id(n) || "missing service id=#{n}"
irb(main):019:1> end
```

Here are the ranges of missing IDs I found: 

```
missing service id=0...missing service id=1

missing service id=52...missing service id=83

missing service id=118...missing service id=505

missing service id=539...missing service id=773

missing service id=779...missing service id=810

missing service id=814...missing service id=1271

missing service id=1275...missing service id=2120

missing service id=3229...missing service id=3281
```

**Comment by alexsoble** [comment]
# When do these service ID gaps occur?

```
irb(main):080:0> puts Service.find_by_id(52 - 1).created_at
2016-08-30 13:40:59 UTC
irb(main):081:0> puts Service.find_by_id(83 + 1).created_at
2016-09-09 13:12:03 UTC

irb(main):082:0> puts Service.find_by_id(118 - 1).created_at
2016-10-07 13:31:57 UTC
irb(main):083:0> puts Service.find_by_id(505 + 1).created_at
2016-10-11 18:09:08 UTC

irb(main):084:0> puts Service.find_by_id(539 - 1).created_at
2016-10-25 15:35:17 UTC
irb(main):085:0> puts Service.find_by_id(773 + 1).created_at
2016-10-28 13:52:08 UTC

irb(main):086:0> puts Service.find_by_id(779 - 1).created_at
2016-11-01 18:19:26 UTC
irb(main):087:0> puts Service.find_by_id(810 + 1).created_at
2016-11-04 13:30:39 UTC

irb(main):088:0> puts Service.find_by_id(814 - 1).created_at
2016-11-18 14:24:43 UTC
irb(main):089:0> puts Service.find_by_id(1271 + 1).created_at
2016-11-30 13:32:43 UTC

irb(main):090:0> puts Service.find_by_id(1275 - 1).created_at
2016-11-30 13:36:20 UTC
irb(main):091:0> puts Service.find_by_id(2120 + 1).created_at
2016-12-01 15:57:28 UTC

irb(main):092:0> puts Service.find_by_id(3229 - 1).created_at
2017-01-27 14:46:24 UTC
irb(main):093:0> puts Service.find_by_id(3281 + 1).created_at
2017-02-01 23:35:45 UTC
```

From August 2016 through February 2017, about a 6-month period.

**Comment by alexsoble** [comment]
Ran this by @snoopyuri and showed him the Service Upload UI with the "Delete" button — he says he's never used the "Delete" button to destroy a Service Upload, so that rules out that hypothesis for why some of these IDs are missing.

**Comment by alexsoble** [comment]
# What do the Service Upload IDs say?

```
irb(main):001:0> ServiceUpload.pluck(:id)
=> [8, 9, 10, 11, 13, 14, 15, 16, 17]
```

They say Service Uploads 1-7 and 12 were deleted.

And since the Service Upload code says:

```
  has_many :services, dependent: :destroy
```

... that means Service Uploads 1-7 were deleted and deleted all their associated services with them in a cascade. 

Since Uri didn't delete them, that means I must have deleted them. Feeling very https://twitter.com/leahbannon/status/930529620910157824 — more work to do to verify and confirm this deletion story right now.

**Comment by alexsoble** [comment]
# When were existing Service Uploads uploaded?

```
irb(main):005:0> puts ServiceUpload.pluck(:id, :created_at)
8
2016-12-22 23:32:02 UTC
9
2016-12-22 23:32:10 UTC
10
2016-12-22 23:32:23 UTC
11
2016-12-22 23:32:30 UTC
13
2017-02-01 23:35:45 UTC
14
2017-03-24 15:15:38 UTC
15
2017-09-06 20:07:51 UTC
16
2017-09-12 13:34:22 UTC
17
2017-10-11 10:33:10 UTC
```

**Comment by alexsoble** [comment]
The dates above line up with the missing Service ID ranges.

Service Upload id=12 was deleted sometime in the last week of 2016 or the first two months of 2017. 

That corresponds to the dates in this range:

```
missing service id=3229...missing service id=3281

irb(main):092:0> puts Service.find_by_id(3229 - 1).created_at
2017-01-27 14:46:24 UTC
irb(main):093:0> puts Service.find_by_id(3281 + 1).created_at
2017-02-01 23:35:45 UTC
```

Service Uploads 1-7 were deleted before December 22, 2017. That lines up with the dates of all the other missing Service IDs:

```
missing service id=0...missing service id=1

missing service id=52...missing service id=83

missing service id=118...missing service id=505

missing service id=539...missing service id=773

missing service id=779...missing service id=810

missing service id=814...missing service id=1271

missing service id=1275...missing service id=2120
```

**Comment by alexsoble** [comment]
I started digging into the GitHub record to try to match up database records to code changes. 

Here's the PR I'm looking at: https://github.com/studentinsights/studentinsights/pull/728/files.

**Comment by alexsoble** [comment]
#728 was merged in Oct 7, 2016. It adds a code path for creating and destroying service uploads with `dependent: destroy`, meaning that it can destroy services and create gaps in the IDs. It adds an API but no UI, meaning that I used it to test out the functionality but @snoopyuri couldn't have used it.

Oct 7, 2016 is the same day we see our second services ID gap start:

```
irb(main):082:0> puts Service.find_by_id(118 - 1).created_at
2016-10-07 13:31:57 UTC
irb(main):083:0> puts Service.find_by_id(505 + 1).created_at
2016-10-11 18:09:08 UTC
```

**Comment by alexsoble** [comment]
Another data point: September 23 2016 was the first date Uri sent me services spreadsheet data to upload using the service upload path.

**Comment by alexsoble** [comment]
More related PRs: 

+ #817 — January 2017 — first step toward a Service Upload UI
+ #875 — March 2017 — fixed Windows bug with the Service Upload UI, as I recall this unblocked the feature for Uri and was the last improvement to the Service Upload UI to date

**Comment by alexsoble** [comment]
Okay, this is enough data points to make a timeline.

# Timeline

+ March 2016 — First service record created.
+ August 30-September 9 2016 — First gap somewhere within this range. 
+ September 23 2016 — Uri sends services spreadsheet to upload.
+ Oct 7 2016 — Code path added for creating and destroying service uploads via the command line/console (#728), `dependent: :destroy` means that this can create gaps in the ID sequence. 
+ October 7-11 2016 — Second ID gap somewhere in this range. 
+ October 25-28 2016 — Third ID gap somewhere in this range. 
+ November 1-4 2016 — Fourth ID gap somewhere in this range. 
+ November 18-30 2016 — Fifth ID gap somewhere in this range. 
+ November 30-December 1 2016 — Sixth ID gap somewhere in this range.
+ December 12 2016 — First ServiceUpload currently in database was created, ID=8. Service Upload IDs 1-7 are missing. 
+ December 12 2016 - February 1 2017 — ServiceUpload deleted sometime in this range. ID=12.
+ January 27 2017 - February 2 2017 — Seventh ID gap somewhere in this range.
+ March 10 2017 — Service Upload UI finalized.

**Comment by alexsoble** [comment]
# Conclusion? 

@kevinrobinson / anyone else who wants to review this and weigh in:

The above timeline looks like reasonably good verification that the missing service IDs are attributable to me creating and destroying `ServiceUpload` objects, which deleted service records via a `dependent: :destroy` cascade. 

This happened because I didn't realize that the `Service` model was meant to be insert-only, and I didn't realize we needed to create a database-level log object for when deleting service records via a `dependent: :destroy` relationship. 

The strongest evidence here is that the counts and the timelines add up well. There are eight service ID gaps and eight deleted ServiceUpload records. The first seven service ID gaps all occur in the same time range as the first seven deleted ServiceUploads. The last gap occurs around the same time as the last deleted ServiceUpload (ID=12). 

The only element that still leaves questions for me is the size of the final Service ID gap, `missing service id=1275...missing service id=2120`. This is really large, weighing in at 845 IDs. I dug back into my email history and couldn't find any mention of a bulk upload around that time with 800+ services involved. But it's possible that I manually created a ServiceUpload with ~100-200 associated IDs, and if there were data issues or errors involved, deleted the services and re-added them several times? Hard to say what this extra-large ID gap means. 

I'd appreciate feedback here. I feel comfortable with the conclusions described in this comment, but am open to other perspectives and opinions.

**Comment by alexsoble** [comment]
Alright, I found the explanation for the 844-wide ID gap. 

The gap for these IDs is between November 30-December 1 2016. Last year I got a file of Afterschool Tutoring Program data from Uri with 400-something rows. On 28/11/2016 I wrote to Uri with subject like "ATP data uploaded"! 

But Uri wrote back saying he didn't see the data in Insights. I wrote back saying:

```
Hi Uri, 

I fixed this issue — check out the School Overview page for WHCS. 

[STUDENT]'s service count is updated and and you'll see filters for Afterschool Tutoring and SomerSession now.

I caused this error by making a typo — I bulk uploaded these services as ending summer 2016 instead of 2017. Now fixed! 

I'll also add some stricter validations making this kind of typo mistake impossible in the future. 

Thanks for catching this Uri! We still have some work to do getting the app all caught up with the correct logic for bulk uploads, but we're making progress! 
```

If I used the ServiceUpload command line API to create/destroy two services files with ~400 services each around the end of November/beginning of December 2016, that explains the 844-wide ID gap perfectly.

**Comment by kevinrobinson** [comment]
@alexsoble  🕵️ 🎉

**Comment by alexsoble** [comment]
@kevinrobinson 😆 👍
