### ISSUE TITLE
Enforce foreign key constraints everywhere

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1252]
That would have prevented this awkward situation: https://github.com/studentinsights/studentinsights/pull/1165#issuecomment-343319396

Right now we have Discontinued Services in our database with no associated service records, and that's not great.

**Comment by alexsoble** [comment]
Might be as straightforward as using https://github.com/jenseng/immigrant — we need to double check and make sure it doesn't have any side effects on the database.

**Comment by gabivoicu** [comment]
@alexsoble Is [this](https://github.com/studentinsights/studentinsights/pull/1256) what you had in mind?

What would be a good way to test for side effects?

**Comment by alexsoble** [comment]
@gabivoicu I left some notes in the PR conversation, let me know if those make sense to you or if you have more questions!

**Comment by gabivoicu** [comment]
@alexsoble I saw them but haven't had time to answer yet, hopefully tonight or tomorrow morning

**Comment by alexsoble** [comment]
Fixed by @gabivoicu in #1256!
