### ISSUE TITLE
User testing feedback from Absences Dashboard [Winter Hill Community School]

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1264]
@edavidsonsawyer — Today we got the chance to user test the absences dashboard with the principal at Winter Hill Community School. @snoopyuri introduced him to the dashboard and asked him to explore, narrate out loud, and explain what he would do with the data he saw. 👍 

The data loaded up great and the principal thought the charts were really useful! He said he would use this to identify homerooms that could improve their attendance and to create a "call list" of students with attendance issues so that he could sit down and call parents to urge better attendance.

We also spotted a few areas for improvement during the user testing session, which I'll document here. We can break these out into separate issues, but for now I'll put all the feedback / areas for refinement that we saw here for discussion and prioritization: 

+ [ ] **Principal thought that the date boxes on either side of the range were editable and tried to type into them to set the dates.** He didn't see them as labels. Lots of ways to address this issue. Personally, this made me think maybe users would find it more intuitive to use two datepickers instead of a sliding range here since we use datepickers in other places in Student Insights?
+ [x] **When principal clicked on the bar for each homeroom, he expected the students table to populate with the students in that homeroom.** This is essentially the same paradigm as the School Overview Page. In some ways the School Overview Page is training users to expect this! 
+ [ ] **Principal wanted to see bar charts default to start at beginning of school year instead of 1 calendar year back.** @edavidsonsawyer, you intuited this in your initial version of this feature! Based on what we've learned from our last iteration, I think we should implement this on the client side rather than the server side. 
+ [x] **Principal would use the students table as a "call list" to call parents about attendance issues.** To me this suggested hyperlinking the names in the students table to student profile pages, so that users can easily find contact info for students and make calls home when attendance issues bubble up.

**Comment by edavidsonsawyer** [comment]
Great stuff, @alexsoble and @snoopyuri! I'll try to follow up with one or both of you by phone to talk through a couple of these points.

**Comment by alexsoble** [comment]
@edavidsonsawyer We can also talk about it on the call today if you can join!

**Comment by edavidsonsawyer** [comment]
Hey @alexsoble and @snoopyuri , I haven't had a lot of time to work on this but #1272 will change the student list to reflect the selected homeroom. I'm still thinking over the appropriate way to switch back to the school view. Right now that's done by clicking on the monthly attendance chart, or clicking on background space in the homeroom attendance chart. It might be better to add a button to make that switch explicit.

**Comment by alexsoble** [comment]
@edavidsonsawyer Updated the checklist for this "epic" issue — we're two down, two to go!

**Comment by kevinrobinson** [comment]
@edavidsonsawyer I think these are all updated and no longer relevant but am not sure.  What do you think, is there anything in here that we want to take forward or is this just stale and this is basically closed now?

**Comment by edavidsonsawyer** [comment]
I totally lost track of this. Yes, all these have been implemented in subsequent updates

**Comment by kevinrobinson** [comment]
👍 no worries, thanks!

**Comment by kevinrobinson** [comment]
this was done!
