### ISSUE TITLE
Import all educators in educators_export.txt regardless of school filters?

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1266]
The deeper @snoopyuri and I dig into educators import, the more we're finding educators who need to be imported but aren't in the school filters. For example, SPED educators are assigned to school SPED. So maybe we should import the whole `educators_export.txt` regardless of school filters. (Or just add "SPED" as a school in our app to move more incrementally? Might be an easier approach since it wouldn't involve changing import logic.)

**Comment by snoopyuri** [comment]
Agree, let’s do it and it would make life easier as we bring on new districts and don’t quite know how they classify certain ancillary people.

**Comment by alexsoble** [comment]
@snoopyuri I think this could be a good long term change — when we have data dumps to look at for a second school district, I'll review their `educators_export.txt` and see how educators are associated. For now I want to make sure we get Christine access to Insights with relatively quick turnaround, I think adding a school called SPED will be the most direct and fast way (#1269). Changing the way the importer code handles filtering is a sensitive change and would require time and testing to implement, so it's not as quick of a turnaround.

**Comment by alexsoble** [comment]
Closing for now since both of the educators Uri brought up have user roles and accounts in our system now.
