### ISSUE TITLE
Attendance/Tardy Graphs Not Populating

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1290]
Just got a call from a principal to let me know that in the Student Profile, the attendance, tardy, and discipline graphs have no data in them.  So even though it shows absences, tardies, and discipline in the color window, when you click and scroll down, there's nothing there.   Is this related to the memory issue that @alexsoble and @kevinrobinson were tackling earlier or did it not fully upload the data last night?

**Comment by alexsoble** [comment]
@snoopyuri Memory errors weren't the true cause of the issues earlier. And the nightly upload should not affect this. Mostly likely it's a JS error but I'm digging in now.

**Comment by alexsoble** [comment]
Not seeing any JS errors in the console so it's a "quiet" bug.

**Comment by alexsoble** [comment]
Looking at recent changes to JS. My first thought was #1285, bumping up moment JS. Experimented with reverting that change locally but data on the graphs was still missing. Next up is #1261.

**Comment by alexsoble** [comment]
Found the issue, it was in #1261. Fixing now.

**Comment by alexsoble** [comment]
@snoopyuri Production is fixed.

**Comment by Jngai** [comment]
@alexsoble I checked the demo site earlier and didn't see a console error. This built correctly in `yarn start` and the tests ran well. Lets be sure to click everything for my other pr.

**Comment by alexsoble** [comment]
@Jngai Yup, there was no console error here, it was a "quiet" error. The buggy function was:

```
export function eventsToMonthBuckets(monthKeys, events) {
  const eventsByMonth = _.groupBy(events, this.defaultMonthKey);  <<< removed call to `this`
  return monthKeys.map(function(monthKey) {
    return eventsByMonth[monthKey] || [];
  });
}
```

Note the `... || []` statement inside the iterator — this rescued us from `undefined` and just substituted in an empty array. 

One good change would be to make this code more sensitive to bad data coming in from upstream and throw errors in those cases.
