### ISSUE TITLE
Improve color mapping for lines on charts

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#133]
Across sparklines and details charts, particularly on the profile v2 page and the STAR charts, it'd be simpler for users if the colors for line charts had a consistent meaning.  The STAR charts encode the change across the visible range with color (eg., red is regression, blue is growth), so this might be a good starting point for all charts.

**Comment by kevinrobinson** [comment]
@sentientmachine started taking a look at this last night!

**Comment by sentientmachine** [comment]
Plan: Of the charts that show in the v2 student page, the color of the charts should be a smooth gradient between red and blue to indicate an overall assessment of how good this rise is relative to the rise of the other students.  That way if you see an increasing diagonal line that's green, you can know that this is the best of the group, if a decreasing diagonal line is green then that decline is the "smallest loser", otherwise if red it's the "worst of all users, who are also declining".

**Comment by sentientmachine** [comment]
The rest of the plan is simple, fly to the moon, shrink the moon, grab the moon....
![img_20160308_211318](https://cloud.githubusercontent.com/assets/330247/13623292/7decafdc-e573-11e5-9fbd-db36f9412c41.jpg)

**Comment by kevinrobinson** [comment]
:moon: :full_moon_with_face: :smile:

**Comment by sentientmachine** [comment]
I've got the date of the leftmost position.  I was able to get the indexes of the points to its left and right, and I was able to get the values of the points left and right.  Next is to get the percentage the date is between the two dates, and then apply that same ratio to the y values to get the final leftmost y value.  Then compare that to the rightmost value and apply a gradient between green and red for how much it goes up.

**Comment by kevinrobinson** [comment]
@sentientmachine nice!  :+1:

**Comment by sentientmachine** [comment]
I'm done with all the changes, I'm trying to do a git push to push my branch, but I get an authentication error:
fatal: unable to access 'https://github.com/studentinsights/studentinsights.git/
We'll get it sorted out tuesday.

**Comment by kevinrobinson** [comment]
@sentientmachine nice!  Yeah I think this is from trying to push to the main Student Insights repo.

So I think what you'll need to do is:
 1. Fork this repo, using the button in the upper right of the GitHub UI.
 2. Add your fork (eg., https://github.com/sentientmachine/studentinsights) as a new remote repository to  your local git repository, using the command line git commands on your machine.
 3. Push the work on the branch in your local repository to your GitHub fork.
 4. Then submit a pull request through the GitHub UI from your fork to the [main Student Insights repo](https://github.com/sentientmachine).

I can take a look at this with you on Tuesday too if you want.  Thanks for all your help!

**Comment by sentientmachine** [comment]
Need to improve the color schemes from red to gray and from gray to blue.   Don't color the discipline right charts.  
![img_20160322_205210](https://cloud.githubusercontent.com/assets/330247/13972588/5b89ee0c-f070-11e5-8874-12bb541c6226.jpg)
