### ISSUE TITLE
Deploy Insights New Bedford app

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1371]
Using this Issue as a thread to post updates and notes on the deployment process, will close when the app is successfully set up and notes are moved over to proper documentation. 💻 🏫

**Comment by alexsoble** [comment]
Couple of config notes:

```
DISTRICT_KEY: new_bedford
DISTRICT_NAME: New Bedford
SHOULD_USE_LDAP: false    # we're using database auth to start
USE_QUOTAGUARD: false    # quotaguard is only used to talk to somerville ldap
```

**Comment by alexsoble** [comment]
Need to set buildpacks in Heroku (can use UI) before first deploy:

```
heroku/nodejs
heroku/ruby
```

![screen shot 2018-01-10 at 1 16 08 pm](https://user-images.githubusercontent.com/3209501/34790776-74ca7216-f608-11e7-9951-aeb771f26f3e.png)

**Comment by alexsoble** [comment]
```
heroku run rake db:migrate
```

**Comment by alexsoble** [comment]
Running first data import process!

**Comment by alexsoble** [comment]
Students import ran without any errors, attendance import ran but then crashed with:

```
 🚨  🚨  🚨  🚨  🚨  Error! Couldn't find Student 
```

**Comment by alexsoble** [comment]
Precomputing all the overview pages because some of the bigger ones don't load.

**Comment by alexsoble** [comment]
Shipping #1373 to unbreak Educator Permissions Overview page for New Bedford.

**Comment by alexsoble** [comment]
Set up three critical tasks to run nightly in the background using Heroku Scheduler:

+ `rake precompute:school_overview`
+ `rake chores:import_data_in_background`
+ `rake chores:update_searchbar_data_for_educators_who_log_in`

I was wondering why the School Overview page performance seemed so poor on the New Bedford app. Then I looked at the logs and saw precomputed JSON wasn't being loaded. Then I looked at the code and remembered that precomputed school overview JSON is only loaded if the job has been run within the last day. So it's really critical to get these background processes up, because a one-off precomputing job for demo purposes gets stale before too long.

**Comment by alexsoble** [comment]
Next thing to do here in my mind is set up email integration so that we can get emailed error alerts when the nightly data import process fails.

**Comment by alexsoble** [comment]
Opening up #1376 to unblock setting up a mailer resource for New Bedford Insights.

**Comment by alexsoble** [comment]
Lesson learned: all mailer config must be set up properly in order to run the import process all the way through.

Why? We `rescue` any errors from the import process . . . and then send an email to devs about the error. If the email-sending itself throws an error, the entire import process stops and subsequent importers do not run.

**Comment by alexsoble** [comment]
Now that we have the two pilot schools from #1380, going to change the import job so that it only imports data for our pilot schools:

```
thor import:start --school '105' '115'
```

It's possible that some of the import issues will go away when we narrow our import because they involve records that the filter will skip over.

**Comment by alexsoble** [comment]
We hit the limit on our default Hobby Dev (Free) postgres database so it's time to upgrade it.

**Comment by alexsoble** [comment]
Upgraded to a higher-tier Heroku database that can take us up to 10,000,000 rows.

**Comment by alexsoble** [comment]
Note: changing the scheduled job to

```
thor import:start --school '123' '115'
```

now that #1407 is merged and deployed.

**Comment by alexsoble** [comment]
OK, learned two more important things about New Bedford's schools setup! 

## 1.

**`thor import:start --school '123' '115'` doesn't work for New Bedford**

Why? The attendance importer blows up. Some attendance event rows have school IDs of 123 or 115, but the associated student row has a different school ID, and so the attendance row throws an error saying `Couldn't find Student`.

My interpretation of this is that the absence or tardy happened while the student was at school 123 one or more years ago, but the student switched schools and is now at school ABCDEF. This never came up while working with school filters on Somerville data, but New Bedford is a 3X larger schol district. 

## 2.

**`thor import:start` doesn't work for New Bedford**

When I removed the school filter, the import process kept blowing up. I found that was because of an unimported student record with school=33. But there is no school 33 in our New Bedford config. Got this info from New Bedford IT:

> You can ignore all of the kids that are in these school numbers – they aren’t real schools.

![schools-new-bedford](https://user-images.githubusercontent.com/3209501/35408524-0e1c7c48-01d5-11e8-87cb-4d0eb4ab24be.png)

My hypothesis is that some students must have moved to schools that do exist to "schools" that are really placeholder codes for other things, like "Out of District." So they have attendance records that get imported while the student record does not.

**Comment by alexsoble** [comment]
Thinking through it a little more, I need to investigate case no. 2 in a little more depth. The Student and StudentRow classes were written to be tolerant of students not assigned to any schools. (The student class has a `self.with_school` method: `where.not(school: nil)`.

So my question to look into here is really why students with school IDs of 33 (for example) aren't being imported.

**Comment by alexsoble** [comment]
Okay, learned a lot about what's going on with some debugging! 

Here's the mismatch (illustrated with some silly made up CSV data):

```
# istudent.csv
"local_id","school_id","name"
100,33,"demo student"

# iattendance.csv
"local_id","school_id","absence","tardy","event_date"
100,123,1,0,"a long time ago"
```

Here's what happens:

1. Student import runs. Student=100 doesn't get imported because 33 isn't inside the default school filter.
2. Attendance import runs. Student=100 used to be at school 123 a long time ago, but transferred out of the district and got "transferred" to "school 33."
3. The attendance row is in the school filter, but because the student cannot be found, the importer blows up.

**Comment by alexsoble** [comment]
Updates on assessment import! 

Jen from New Bedford IT kindly switched around some of the column/header mappings in the Java export code they're running, which unblocked attendance import for New Bedford. 👍 👍 

I merged in #1441, which clarified the column names that had confused New Bedford's export script coder. Then I noticed that the "Next Gen" MCAS detection code wasn't running right for New Bedford, so I shipped/deployed #1449.

I think the next step should be to walk through the assessments that got imported and check assumptions manually, to make sure I'm not missing anything subtle about the import.

**Comment by alexsoble** [comment]
# New Bedford MCAS 
*(note: the only schools I've imported assessment data for so far are Parker and Pulaski, our New Bedford pilot schools)*

Looking at some record counts for our pilot schools:

```
$ Assessment.where(family: ['MCAS', 'Next Gen MCAS']).each do |a|
  puts "#{a.family} #{a.subject}"
  puts a.student_assessments.count
end ; nil

Next Gen MCAS Mathematics
250

Next Gen MCAS ELA
248

MCAS ELA
5

MCAS Mathematics
3
```

Almost all the records are Next Gen, which makes me think that the export file we're getting from New Bedford is most likely a "current snapshot" export and not a historical export. I'll reach out to New Bedford IT to confirm. 

How many 3rd through 8th graders are there in our pilot schools?

```
$ Student.where(school_id: 14, grade: ['3', '4', '5', '6', '7', '8']).count
 => 301 

$ Student.where(school_id: 13, grade: ['3', '4', '5', '6', '7', '8']).count
 => 117 
```

With ~418 students in grades that take MCAS, our assessment counts seem on the low side (~250 records for Math and for English). I can double check this with New Bedford and Uri.

**Comment by alexsoble** [comment]
# New Bedford MCAS (part 1)

Some more summary data via #1451:

```
require './lib/analysis/analyze_assessments_table'
a = AnalyzeAssessmentsTable.new('./data/iassessments.csv')

a.assessment_subject_summary
 => {"ELA"=>16645, 
"Mathematics"=>16796, 
"Science"=>16645, 
"Listening"=>7514, 
"Speaking"=>7514, 
"Reading"=>7514, 
"Writing"=>7514, 
"Comprehension"=>7514, 
"Oral"=>7514, 
"Literacy"=>7514, 
"Overall"=>7514, 
"ERW"=>151, 
"Total"=>151} 

a.assessment_test_summary
 => {"MCAS"=>49935, "ACCESS"=>60112, "PSAT"=>453} 
```

This adds some more info: of the assessments we surface in Insights, we have only MCAS and ACCESS in this export file. Crosstabs between assessment family and subject would be helpful, I'll do those next.

**Comment by alexsoble** [comment]
# New Bedford MCAS (part 3)

Crosstabs between assessment family and subject, via cd160a09f352670b6b2bc1ce29d217f392719048:

```
 => {"MCAS+ELA"=>16645, 
"MCAS+Mathematics"=>16645, 
"MCAS+Science"=>16645, 
"ACCESS+Listening"=>7514, 
"ACCESS+Speaking"=>7514, 
"ACCESS+Reading"=>7514, 
"ACCESS+Writing"=>7514, 
"ACCESS+Comprehension"=>7514, 
"ACCESS+Oral"=>7514, 
"ACCESS+Literacy"=>7514, 
"ACCESS+Overall"=>7514, 
"PSAT+Mathematics"=>151, 
"PSAT+ERW"=>151, 
"PSAT+Total"=>151} 
```

**Comment by kevinrobinson** [comment]
related: IEP document setup

**Comment by kevinrobinson** [comment]
Here's a stab at a list.  This is aiming close out "New Bedford is setup" and get a good-enough draft for "setting up a new instance" since we'll probably actually pull doing this work shortly.

This is pushed in https://github.com/studentinsights/studentinsights/pull/1881, and the goal would be to review that and merge it and then close this out.

**Comment by kevinrobinson** [comment]
https://github.com/studentinsights/studentinsights/issues/1880 is another critical piece of work here, but let's split that out from this big issue along with any other specific issues with importing or data validation.

**Comment by kevinrobinson** [comment]
Separately, I did some manual console cleanup to remove students, homerooms, and educators not in Parker or Pulaski.  Some of these had been imported in the last two weeks (I'm guessing I did this mistakenly) and some were a while ago (maybe in earlier imports like in this thread before we knew the initial scope).

**Comment by kevinrobinson** [comment]
Closed out with https://github.com/studentinsights/studentinsights/pull/1881 and https://github.com/studentinsights/studentinsights/issues/1880.  New work for the 2018-2019 school year is tracked on the work board right now.
