### ISSUE TITLE
Add label to Tardies administrator dashboard about 3-month range

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1378]

**Comment by kevinrobinson** [comment]
@alexsoble @edavidsonsawyer I think this was done in the awesome set of work last week, is that right?

**Comment by edavidsonsawyer** [comment]
@kevinrobinson more or less! Tardies now uses the same range buttons as the absence dashboard so we can probably close this.

**Comment by kevinrobinson** [comment]
👍
