### ISSUE TITLE
Look at anonymized results from Student Survey – what do students want their teachers to know about them?

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1379]
@snoopyuri — you mentioned really interesting survey results in our team meeting that covered what students want their teachers to know about them. When you're able, could you share some of the anonymized results with the team? Could be really useful for guiding the Student Voice work.

**Comment by kevinrobinson** [comment]
This is done separately, and part of this will be rolled into a PD workshop.
