### ISSUE TITLE
Dive into the role of student.registration_date

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1384]
New Bedford's Aspen/X2 instance models student registration/enrollment differently than Somerville's. 

We read a `registration_date` field from Somerville and use that in a couple places in the app. Here's what New Bedford's IT had to say when we talked about why their data export had nil values for `registration_date`:

> There are many dates including Active, First Enrolled, Yog change, Withdrawal. The most recent reg date is not necessarily the enrolled date. 

My first instinct says that the "First Enrolled" date would be the best match for registration date. But I want to confirm that by diving into where we use student.registration_date in the app and what we use it to do. That will let us see if "First Enrolled" can serve the same purpose.

**Comment by kevinrobinson** [comment]
Nice!

It’d be awesome if the outcome here ultimately makes it into
DistrictConfig, since sounds like these are meaningful differences (even if
the shape of the data is the same, the fields are used differently).

**Comment by alexsoble** [comment]
Alright! This turned out to be a fairly simple one. The only place `registration_date` is surfaced in the app is in the School Overview Page Filters section, to enable the user to filter by Years Enrolled. 

Based on that, I'm thinking that the "First Enrolled" column in New Bedford's X2/Aspen instance is likely the best match — I'll reach out to Jen from New Bedford and float that idea.
