### ISSUE TITLE
Investigate net-ldap update

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1397]
To try to tackle https://github.com/studentinsights/studentinsights/pull/1394, and understand more about how this works and how we could configure the updated version so that it works as we need.

**Comment by alexsoble** [comment]
The `devise_ldap_authenticatable` dependency was updated a few days ago: https://github.com/cschiewek/devise_ldap_authenticatable/pull/243

**Comment by kevinrobinson** [comment]
This is done.
