### ISSUE TITLE
Merge landing page and sign-in page

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#14]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/436

It'd be great if regular users could visit somerville.studentinsights.org and sign in without having to hop through the 'sign in' button. One approach could be just to put the content from the about page as-is below the login box.

**Comment by BWieber** [comment]
Hi Kevin, 

#198 handles this one - I believe it can be closed! 

_Brandon_

**Comment by erose** [comment]
Let's close it!

tip @BWieber you can always include the words "Fixes #14" in a PR, then that issue will be closed when the PR gets merged.
