### ISSUE TITLE
"My Notes" page for educators

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1405]
This feature spec came out of a great group discussion with @snoopyuri @gabivoicu @kevinrobinson! 

# What is the goal of the feature? 

Help an educator who's taken notes on Insights refresh their memory about all the notes they've taken by putting them all in one place. 

# How do we build it?

+ @snoopyuri: can be "down and dirty", simple visual design
+ @gabivoicu: like a twitter feed
+ we can mostly reuse the editable notes components from the student profile, except read-only
  + we'd also need to add more context about what student each note is about and what classroom or school they're in -- another card?
+ fetch last month or so of notes, and "click to load more"

# Timeline

Goal is to design this week, either in code or with a paint-type tool, get feedback on the initial design, and start build next week.

**Comment by gabivoicu** [comment]
@alexsoble Is there a spot where we have different logins for the different user types? Teacher, Admin, Principal, etc? I only have one and I need to add the link to the "My notes" page.

**Comment by alexsoble** [comment]
@gabivoicu Hm, check out the very top of the README. Are these what you're looking for?


  - District admin: `uri@demo.studentinsights.org`
  - K8 principal: `laura@demo.studentinsights.org`
  - Kindergarten teacher: `vivian@demo.studentinsights.org`
  - HS physics teacher: `hugo@demo.studentinsights.org`
  - 9th grade counselor: `sofia@demo.studentinsights.org`

All accounts use the password: `demo-password`

**Comment by gabivoicu** [comment]
@alexsoble Yup, that is exactly what I was looking for, I was only looking further down the page 🤦🏻‍♀️. Thank you!

**Comment by gabivoicu** [comment]
Mock for the My Notes Page

![my notes page](https://user-images.githubusercontent.com/8533377/35399691-77368c5c-01ba-11e8-985a-c477ffb40187.png)

**Comment by snoopyuri** [comment]
Gabi – I love it!  Very clean and allows a lot of notes to come up at once and flows well with the rest of our pages.

And it seems that it can be used for the later step of all notes about my students.

Thanks, thanks, thanks!

Uri

**Comment by alexsoble** [comment]
@gabivoicu ✨ ✨ ✨  great mockup! 

One small suggestion: when I read the copy saying "Your notes for the past 30 days," I realized someone could interpret "Your notes" as either "Notes for you to read" or "Notes that you created." Maybe we could make it a little more explicit if we say something like "Notes you created in the past 30 days."

**Comment by kevinrobinson** [comment]
@gabivoicu nice!  👍 

For HS students, I wonder if their grade is more important than their homeroom?  For the layout, this looks like it might be taller than the shortest notes.  And also that it might not fit for students with longer names.  Those might be good to check out and see how they all fit together when developing locally.

Small details that might not be relevant yet...  In the mock, these don't seem to line up vertically and the visual styles are different (eg, rounded borders vs. square) and it'd be good to make those the same.  I figure that's just an artifact of making the mock in some other tool but worth mentioning.

**Comment by gabivoicu** [comment]
@alexsoble I really like that suggestion, I think it's more explicit that way, I will use that when creating the page. (`Notes you created in the past 30 days.`)

@kevinrobinson Thank you for all the things you brought up, super useful!
- are you suggesting we use grade for HS students and homeroom for the other students? I think that shouldn't be to hard to implement
- I had not realized the note card height varies based on the length of the note, that is very interesting, I will think about a way to work with that
- long names could indeed be a problem. Would it be possible to get the length of the longest full name in our production data? It would be a useful number to have. I could make the student info card wider, there's plenty of space. If you have any other suggestions, let me know!
- yes, the lack of alignment is due to my "skill" w/ Sketch

**Comment by kevinrobinson** [comment]
@gabivoicu No problem!  This is great to iterate on and awesome you're working on this 👍

re: grade/homeroom, yep! that's what I was wondering about.  It's more a question for @snoopyuri and don't need to let that block anything we're doing, shipping homeroom is fine too.

re: names and height, you could try using a fifteen character first name and thirty character hyphenated last name and see what it looks like.  It doesn't need to be perfect or match production exactly that should be good enough to get a feel.

**Comment by kevinrobinson** [comment]
The first version of this shipped in https://github.com/studentinsights/studentinsights/pull/1443.
