### ISSUE TITLE
Only show "Years Enrolled" filters in Overview if district has registration date data? 

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1406]
New Bedford is having a hard time exporting its registration date data. Registration dates power this Filter section in the School Overview: 

![years enrolled](https://user-images.githubusercontent.com/3209501/35302423-0af2e08e-0054-11e8-93ab-edb226e209f8.png)

This doesn't seem like a critical filter. But if there's no registration date data in the system, it looks like this, which seems strange: 

![screen shot 2018-01-23 at 3 42 53 pm](https://user-images.githubusercontent.com/3209501/35302452-20fc6d64-0054-11e8-97c5-f6dfd2d3a4ad.png)

This makes me think it would be useful to only show Years Enrolled if we have registration date data in the system, i.e. if we have non-`null` values for registration dates. That will avoid having an awkward/strange filter on the New Bedford School Overview filters.

**Comment by kevinrobinson** [comment]
This was done!
