### ISSUE TITLE
Investigate slow Travis builds

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#142]
This is bad enough it's affecting my development workflow - https://travis-ci.org/studentinsights/studentinsights/builds/113123635 took 20 minutes to even start the build.

I'm not sure if there's anything we can do here to improve this, or if there are other free or cheap services that are better, but if someone knows about alternatives or can help investigate, it would be awesome.

**Comment by kevinrobinson** [comment]
I disabled building on pushes, only on pull requests and merges: https://travis-ci.org/studentinsights/studentinsights/settings  cc @alexsoble

**Comment by kevinrobinson** [comment]
Just taking notes - Travis is super speedy this morning, and builds are starting within seconds!  It's 7:30am EST.

**Comment by erose** [comment]
Seems like this hasn't been an issue in a while, so I'm going to close it. Please, anyone, reopen if you experience this.
