### ISSUE TITLE
Improve generator for behavior incidents in local development

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#145]
These aren't super realistic, which makes it tough to test product improvements like https://github.com/studentinsights/studentinsights/pull/139/files locally.

#### 1. Generate more realistic event distributions ([code](https://github.com/studentinsights/studentinsights/blob/master/app/demo_data/fake_student.rb#L140))
Current example:
<img width="174" alt="screen shot 2016-03-02 at 9 58 26 am" src="https://cloud.githubusercontent.com/assets/1056957/13464076/566d4e64-e05d-11e5-840b-ccb60d3f3e8a.png">

This is the real distribution on 3/2/16:
<img width="174" alt="screen shot 2016-03-02 at 9 53 05 am" src="https://cloud.githubusercontent.com/assets/1056957/13463935/989e00a4-e05c-11e5-9fe6-d08755057199.png">

We should update to match more closely.  There are also often an unrealistically high number of incidents for a few students (eg., in the 50s), which affects UX work on local development and the demo site.

#### 2. Generate realistic text instead of the placeholders there now ([code](https://github.com/studentinsights/studentinsights/blob/master/app/demo_data/fake_discipline_incident.rb#L3))
<img width="626" alt="screen shot 2016-03-02 at 9 59 49 am" src="https://cloud.githubusercontent.com/assets/1056957/13464107/8522ca0e-e05d-11e5-93d8-534dfe6efb0d.png">

These should be full sentences or paragraphs.  Looking at real production data, these are typically 2 - 4 sentences long.

**Comment by kevinrobinson** [comment]
This came up from @bw120's awesome work on https://github.com/studentinsights/studentinsights/pull/139 at Code for Boston last night.

**Comment by erose** [comment]
I'm interested in working on this. I've noticed some other data issues, let me know if they actually are issues:

 * Right now, absent/tardy events are all within the last six months. But other data extends back to 2010.

**Comment by erose** [comment]
What I've found out so far regarding discipline event distributions: the current thing we do is based on https://github.com/codeforamerica/somerville-teacher-tool/issues/94.

In that issue, the mean is given as `5.2` and the standard deviation as `8.3`. In the code, we use those numbers, but we also assume a normal distribution. That would mean that, of students with discipline events, the majority are clustered around `5.2`.

That doesn't resemble the chart Kevin just posted at all -- instead (of students with incidents) most have 1, then fewer have 2, fewer still have 3, etc. So I don't think we want a normal distribution. Not sure what we do want.

**Comment by kevinrobinson** [comment]
For those I'm guessing we want a Poisson distribution, but I think using a normal distribution and then just clamping any values that are below 0 to 0 is probably accurate enough for our needs here.

**Comment by erose** [comment]
I wasn't able to get a normal distribution to behave like this, even with clamping. (Part of this was I'm not sure how to shift/flatten/scale a distribution in Rubystats). So instead, I have an implementation takes in a mapping of outcomes to weights:

    $d = {
        0 => 0.83,
        1 => 0.10,
        2 => 0.03,
        (3..5) => 0.03,
        (6..15) => 0.01,
    }

and generates a random number depending on the weight. (If they key is a range, it samples uniformly from the range). `15` is a random choice here, it's just wherever we want to set the cap.

Happy to talk about this/demo it tonight!
