### ISSUE TITLE
Design - Improve profile columns

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#149]
From @johnrobbjr and Kemal in https://docs.google.com/presentation/d/1t7bXVaFCDU_1d0vxxnqnQ7lMBnXa8oRyYRyMLtwx0hU/edit#slide=id.g11c1c42e02_3_0.

Improve columns on the v2 profile page:
- they don't appear clickable
- left-aligning column titles can improve scanning
- adding titles to columns can help teach the organization.

<img width="983" alt="screen shot 2016-03-02 at 12 48 51 pm" src="https://cloud.githubusercontent.com/assets/1056957/13469395/3a2850c4-e075-11e5-9a8b-8140da5d2719.png">

**Comment by kevinrobinson** [comment]
This is great feedback, and I'd love to see a pull request with a mock of what this would like, particularly with adding titles to the columns.  This would also have to take into account the similar UI in the overview page too:

Combine these two sections into one column, Replace “Demographics” with “Student Details”
<img width="411" alt="screen shot 2016-03-02 at 12 45 21 pm" src="https://cloud.githubusercontent.com/assets/1056957/13469269/a52324c2-e074-11e5-9028-110d1356d361.png">

My only concern here is adding more noise to something that's effectively a teaching support for first-time users.  This is super important though, so striking a good visual balance here would be awesome. :+1:

**Comment by johnrobbjr** [comment]
@kevinrobinson the column design has changed since this point, seems like some of the points were already addressed in issue #199. Can we close this issue?

**Comment by kevinrobinson** [comment]
@johnrobbjr yeah thanks, closed!
