### ISSUE TITLE
Design - revise student header sizing and layout

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#151]
From @johnrobbjr and Kemal's great feedback [here](https://docs.google.com/presentation/d/1t7bXVaFCDU_1d0vxxnqnQ7lMBnXa8oRyYRyMLtwx0hU/edit#slide=id.g11c1c42e02_3_0).

In header, stack name, school, etc. and reduce font size
<img width="986" alt="screen shot 2016-03-02 at 12 46 02 pm" src="https://cloud.githubusercontent.com/assets/1056957/13469296/c3b29c88-e074-11e5-9dfb-3d3c071d0bf5.png">

**Comment by kevinrobinson** [comment]
@johnrobbjr Can you say more about what you're thinking this will help with?

I'd be concerned about using vertical real-estate for information that's background context and not super essential.  So reducing the font-size seems like a great idea.  Stacking the items vertically would use more vertical space and push other information below the fold on a projector, and I'm not sure what benefits there are.  Is the idea it helps with visual clarity?

**Comment by johnrobbjr** [comment]
I'll work on this one next, @kevinrobinson doesn't look like I can assign myself to this issue, do I need certain permissions to do so?

**Comment by kevinrobinson** [comment]
@johnrobbjr awesome, thanks for your help!  I'm not exactly sure to be honest, you're a member of the team but might not have access to tag yourself.  We should fix that! but for this moment right now I just added you as the assignee :)

**Comment by johnrobbjr** [comment]
![issue-151_01](https://cloud.githubusercontent.com/assets/9868315/13730214/61461774-e91f-11e5-9dd2-617d978bf429.png)

By using this design it can give some hierarchy to the title ("Donald Disney" is more relevant than "5th grade"). The first line is 24pt, the second and third lines are 14pt.

**Comment by kevinrobinson** [comment]
@johnrobbjr Thanks for the mock and explanation!  I think you're point about the hierarchy is great, and even with the horizontal layout I think the `(student, classroom, school)` hierarchy would be a good improvement.

One other element we'll need to consider here is where the "Risk level" floats.  This change also uses up slightly more vertical space than the current design (e.g., in https://github.com/studentinsights/studentinsights/pull/108#issuecomment-195579053).  I suspect I'm overthinking this a bit, but what do you think about the tradeoff where new users maybe benefit from a clearer hierarchy, but regular users get slightly less information density?

Also, sorry for the delay here, and thanks for your help and feedback! :+1:

**Comment by johnrobbjr** [comment]
@kevinrobinson I'll try implementing these changes at the next weekly hack night. Is there still work to be done on the Risk Bubble styling in [issue 108](https://github.com/studentinsights/studentinsights/pull/108#issuecomment-195579053)?

**Comment by kevinrobinson** [comment]
@johnrobbjr Awesome!  I think that's all wrapped up, although I just noted a bug and added https://github.com/studentinsights/studentinsights/issues/250.  @BWieber might have more input on #108 but as far as I can see I think we're good to start in on this.

Thanks for your help!

**Comment by kevinrobinson** [comment]
@johnrobbjr @BWieber just ran into a layout bug here, when the horizontal width isn't enough to hold that entire line, the `float: right` bumps down to the next line.  We should be able to fix that up with this work, and switching to all flexbox should make the layout simpler :)

from https://somerville-teacher-tool-demo.herokuapp.com/students/13/profile, with ~1000px width:
<img width="1076" alt="screen shot 2016-04-02 at 10 22 33 pm" src="https://cloud.githubusercontent.com/assets/1056957/14230372/a3ea1154-f921-11e5-9165-a16aacdc576f.png">

**Comment by kevinrobinson** [comment]
Split the bug aspect out into https://github.com/studentinsights/studentinsights/issues/302.

**Comment by erose** [comment]
Is this issue done?

**Comment by alexsoble** [comment]
@erose No, looks like this hasn't been implemented yet.
