### ISSUE TITLE
Design - Clarify that items are clickable in overview page

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#154]
From @johnrobbjr and Kemal's great feedback [here](
https://docs.google.com/presentation/d/1t7bXVaFCDU_1d0vxxnqnQ7lMBnXa8oRyYRyMLtwx0hU/edit#slide=id.g11c1c42e02_3_0).

It’s not clear that these are filter items at first glance, or whether they are clickable or not
<img width="515" alt="screen shot 2016-03-02 at 12 43 39 pm" src="https://cloud.githubusercontent.com/assets/1056957/13469223/66f871f2-e074-11e5-926a-ae9ee297fc62.png">

**Comment by kevinrobinson** [comment]
This would be a great improvement for onboarding and first-time users.  I'm less concerned once someone learns this for the first time, so I underlines or other visual affordances would probably have to be pretty subtle.

Maybe subtle underline on hover?

**Comment by lilybarrett** [comment]
Added an underline on hover effect to the table rows.

**Comment by kevinrobinson** [comment]
@lilybarrett awesomely addressed this in https://github.com/studentinsights/studentinsights/pull/168
