### ISSUE TITLE
Fixing column sorting on overview table and roster table

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#155]
Sorting by columns that have a logical order doesn't work right.

For example, "Disability" sorts alphabetically, leading to sort order like this:
<img width="80" alt="screen shot 2016-03-02 at 1 21 13 pm" src="https://cloud.githubusercontent.com/assets/1056957/13470330/ab9eb5c8-e079-11e5-9abb-a5a319b8c04b.png">

This probably affects columns like FLEP as well.

**Comment by kevinrobinson** [comment]
via Twitter, https://twitter.com/RonnyAlmog may take a look at helping with this, starting with the roster page sorting: https://github.com/studentinsights/studentinsights/blob/master/app/assets/javascripts/roster/roster_page.js#L16

**Comment by dsbader** [comment]
Thanks for the suggestion @kevinrobinson. Last night I was able to get the custom sort to work, but the column also still maintains the default alphabetical sorting too (so, it operates like: default ASC, default DESC, custom ASC, custom DESC...). Still... progress!

**Comment by kevinrobinson** [comment]
@dsbader nice, that's progress!  It's hard to help more without seeing the code, so if you want to push a branch I can take a look at some point.  Thanks for your help! :)

**Comment by dsbader** [comment]
Forked StudentInsights & pushed to a working branch.
https://github.com/studentinsights/studentinsights/compare/master...dsbader:disabilitysort

Not sure how you guys like to work - create a PR now for comments & updates or wait until the fix has been fleshed out more?

**Comment by kevinrobinson** [comment]
@dsbader awesome!  :)

Yeah, check out the [contributing](https://github.com/studentinsights/studentinsights#contributing) section in the repo, which has a link to the GitHub docs for how to submit a pull request.  And happy to walk through this with you Tuesday too.

Two quick bits of pre-feedback for you:
 1. By extending `Tablesort` itself, there's only an implicit link between the `disability` data attribute in https://github.com/studentinsights/studentinsights/compare/master...dsbader:disabilitysort#diff-b5e61b4a04c72ac5d54f453e62cba714R32 and the extension in the other file: https://github.com/studentinsights/studentinsights/compare/master...dsbader:disabilitysort#diff-7f5e1bed30021fcb0a05d32aa659aab6R1.  Ideally, we'd be able to make this more explicit (eg., by defining the sort function directly in the same file for now), or at least add a comment about the data attribute referencing a new sort method we added, since it might be difficult for future us to follow the chain. :)
 2. The new file isn't a React component, so let's move it out of the `components` folder and somewhere like: `app/assets/javascripts/helpers`

And thanks for your awesome help in diving run in to fix this bug! :)

**Comment by ronny2205** [comment]
@kevinrobinson, 
I looked at the roster page and I want to make sure what columns needs to be fixed, because I'm not familiar with all the terminology.
"Level of need" of course.
Are there others and according to what values they need to be sorted?
Thanks!

**Comment by kevinrobinson** [comment]
@ronny2205 Sure, here's some guidance on a starting point (this may be better to split out to a separate issue, but I'll leave it here for now).

Program assigned:
`Reg Ed, 2Way English, 2Way Spanish, Sp Ed`
(least supportive to most supportive)

Level of need:
`None, Low < 2, Low >= 2, Moderate, High`
(lowest need to highest need)

Fluency:
`Fluent, FLEP, FLEP-Transitioning`
(highest fluency to lowest - FLEP is a state term for "formerly limited-English proficient")

**Comment by ronny2205** [comment]
@kevinrobinson, thanks.
Much clearer now.

**Comment by kevinrobinson** [comment]
no problemo!

**Comment by ronny2205** [comment]
@kevinrobinson, I fixed 2 out of the 3 coloumns. 
I'll fix the third one soon, and push it.

**Comment by kevinrobinson** [comment]
awesome, sounds great @ronny2205!

**Comment by ronny2205** [comment]
@kevinrobinson,
I tried to push a branch to github and received an error code 403 fatal: HTTP request failed.

Do I need to get a permission or is it something else?

**Comment by kevinrobinson** [comment]
@ronny2205 If you are trying to push directly to this repository, you won't be able to.  You need to push to your fork and the submit a pull request.  Check out [this](https://help.github.com/articles/using-pull-requests/) link from the [CONTRIBUTING.md](https://github.com/studentinsights/studentinsights/blob/master/CONTRIBUTING.md), and let me know if that helps!

**Comment by ronny2205** [comment]
@kevinrobinson,
thanks. Just pushed the changes and created a pull request:
https://github.com/studentinsights/studentinsights/pull/252
