### ISSUE TITLE
Fix bug with randomness in Student when seeding local database

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#159]
This happens intermittently.  This example is from https://github.com/studentinsights/studentinsights/commit/5cad8c783fab9dd4957fcb09fba48dc5a8730140.

Re-running the seed task leads to the same error in other places in the stack, or a successful run.  I suspect there's some randomness in generating the base `Student` model.

```
Creating demo schools, homerooms, interventions...
Seeding constants...
Creating demo educators...
Creating students for homeroom #1...
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Student can't be blank
/Users/krobinson/Documents/github/studentinsights/app/demo_data/fake_student.rb:185:in `block in add_deprecated_notes'
/Users/krobinson/Documents/github/studentinsights/app/demo_data/fake_student.rb:185:in `times'
/Users/krobinson/Documents/github/studentinsights/app/demo_data/fake_student.rb:185:in `add_deprecated_notes'
/Users/krobinson/Documents/github/studentinsights/app/demo_data/fake_student.rb:8:in `initialize'
/Users/krobinson/Documents/github/studentinsights/db/seeds/demo/demo.seeds.rb:42:in `new'
/Users/krobinson/Documents/github/studentinsights/db/seeds/demo/demo.seeds.rb:42:in `block (2 levels) in define_seed_task'
/Users/krobinson/Documents/github/studentinsights/db/seeds/demo/demo.seeds.rb:41:in `times'
/Users/krobinson/Documents/github/studentinsights/db/seeds/demo/demo.seeds.rb:41:in `block in define_seed_task'
Tasks: TOP => db:seed:demo => db:seed:demo:demo
```

**Comment by kevinrobinson** [comment]
Think this is related, but didn't investigate: https://travis-ci.org/studentinsights/studentinsights/builds/113422806

**Comment by eudaimonious** [comment]
Sorry for the commit spam. I was rebasing stuff around and didn't realize github would link based on issue number. I've got a PR for you here: https://github.com/studentinsights/studentinsights/pull/167

**Comment by kevinrobinson** [comment]
@eudaimonious no worries!  It looks like https://github.com/studentinsights/studentinsights/pull/167 links to https://github.com/studentinsights/studentinsights/issues/15 earlier, so I just edited it to point back here too.  I think your work in https://github.com/studentinsights/studentinsights/pull/167 will awesomely fix the first issue here, but the second one still needs fixing.  I'll take a look tomorrow or Tuesday.

Thanks again for your help :)

**Comment by kevinrobinson** [comment]
Okay, we've got five consecutive successful runs:
- https://travis-ci.org/studentinsights/studentinsights/builds/114094540
- https://travis-ci.org/studentinsights/studentinsights/builds/114767267
- https://travis-ci.org/studentinsights/studentinsights/builds/114779107
- https://travis-ci.org/studentinsights/studentinsights/builds/114779113

So considering this fixed!
