### ISSUE TITLE
User manual for data integration and deployment 

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#17]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/417.

**Comment by erose** [comment]
This is what we've been working on, right?

**Comment by alexsoble** [comment]
Yes! We now have a [How It Works README section](https://github.com/studentinsights/studentinsights#how-it-works), [school-level onboarding doc](https://github.com/studentinsights/studentinsights/blob/master/docs/project/somerville_school_onboarding.md) and [Aspen / X2 notes](https://github.com/studentinsights/studentinsights/blob/master/docs/project/notes_on_x2_data.md).
