### ISSUE TITLE
Discipline: Student list doesn't match selection (eg, classroom)

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1708]
Related to https://github.com/studentinsights/studentinsights/issues/1660.

When clicking on a particular item like "grade 1", the student list table updates.  But this seems like it's only sorting and not actually filtering - if you scroll the list you see what looks like probably all other students at all other grade levels too.  It may be that there's some bug in how the table is updated, since the "total incidents" count seems to update but not reflect the number of students visible when scrolling through the table.

### 1. Select "grade" in dropdown
<img width="1018" alt="screen shot 2018-05-21 at 11 37 06 am" src="https://user-images.githubusercontent.com/1056957/40316248-b108f686-5ceb-11e8-9376-ad3f5f9c5ab0.png">

### 2. Click on 1st grade
It looks like the list has updated, and the total count is smaller.
<img width="1014" alt="screen shot 2018-05-21 at 11 31 31 am" src="https://user-images.githubusercontent.com/1056957/40316026-fbb1e9a0-5cea-11e8-8728-acfa6caa714c.png">

### 3. Scroll down table
There are many students in other grades that shouldn't be on the list.
<img width="996" alt="screen shot 2018-05-21 at 11 31 40 am" src="https://user-images.githubusercontent.com/1056957/40315999-ec9f2ffe-5cea-11e8-8fec-fdd0059b60bf.png">

**Comment by kevinrobinson** [comment]
@edavidsonsawyer FYI this came up looking at this with someone this morning.

**Comment by edavidsonsawyer** [comment]
@kevinrobinson Ah! Nope, this never worked. Fixing!

**Comment by kevinrobinson** [comment]
Closed by https://github.com/studentinsights/studentinsights/pull/1712.
