### ISSUE TITLE
Discipline: Total incidents and student incident counts don't update when changing time range

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1809]
This was definitely working before (see GIF in https://github.com/studentinsights/studentinsights/pull/1670), but seems to have regressed.

To reproduce:
- Load the page for any school and click on the time filter.
- I was expecting the "total incidents" at the bottom left to update, and the "incidents" for each student to update.
- They seem to be unchanged regardless of the time filter.

**Comment by edavidsonsawyer** [comment]
@kevinrobinson I ran into this while working on #1811. I should have a fix within a day or so.

**Comment by kevinrobinson** [comment]
@edavidsonsawyer awesome, sounds great! 👍

**Comment by edavidsonsawyer** [comment]
Should be all set with #1815
