### ISSUE TITLE
Improve login monitoring and safety

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1850]
Talk with @kevinrobinson and @alexsoble!

**Comment by alexsoble** [comment]
@kevinrobinson I did some digging into the authtrail gem to see if it could help us monitor login patterns: https://github.com/ankane/authtrail.

There's a lot to like about the library: "Battle-tested at Instacart" is a plus; the source code is small and easy to read; the author is responsive to issues.

I tried adding authtrail locally and confirmed that it works in the context of our custom `ldap_authenticable_tiny` auth strategy: it adds the right LoginActivity records on successful/unsuccessful login attempts. 

One data column that ***isn't*** set successfully by the authtrail gem is the "strategy" column on unsuccessful attempts. This is always set to `"database_authenticatable"`, which you can see in the authtrail codebase here: 

https://github.com/ankane/authtrail/blob/8eed87a390400f280994772d60b7481bbbef440f/lib/auth_trail/manager.rb#L32.

I'm not sure if this is a dealbreaker or not. It doesn't feel right to have a piece of software that's auditing logins to report incorrect information about the auth strategy being used -- this could be really confusing. We could add code comments explaining it or add some hack-y code to overwrite this column in the LoginAttempts table. 

Another approach would be to write our own custom code for this functionality but to look to authtrail for inspirations and patterns.

**Comment by kevinrobinson** [comment]
We did a bunch of things here; see the security and privacy audit docs.
