### ISSUE TITLE
Consolidate Ben & Eli's changes to attendance & behavior page

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#196]
- [x] Re-order graphs & sparklines to be: discipline incidents, absences, tardies.
 - [x] Add tabs and anchors to allow jumping to specific graphs on reading, math & attendance and behavior columns.
 - [ ] Implement jump-to-event on click feature in discipline incidents graph.
 - [x] Implement Ben's box styling changes.
 - [x] Add discipline incident feed to same frame as the graph.

Ben should make a branch to push his changes to the main repo.
Eli should pull down Ben's branch and merge these changes into his scroll_to_discipline_incident branch.

**Comment by kevinrobinson** [comment]
@erose and @bw120 this is awesome, thanks for working on this and talking it out in person!  There's some good identification of user problems here and ideas for improvements :)

Let's try this out for a process, and then we'll see if we can use this as a model going forward too!

1. Identify what problem we're trying to help the user with and why it matters.
2. What design or UX improvements can help the user with that problem?  What are the tradeoffs?
3. How to execute on sequencing or building it in code.

some other notes I took:
```
understanding the different sections
separate sections in details
discipline incidents after tardies and absences
top order -> bottom order
easier to see what happened in discipline incidents (summary in tooltip and take you down)
navigation down and up
``

**Comment by erose** [comment]
Edited the original issue post to reflect what Kevin, Ben and I talked about.

Pull request https://github.com/studentinsights/studentinsights/pull/199 will implement "Add tabs and anchors..." and "Ben's box styling changes", @bw120 check those off once the pull request is merged.

**Comment by kevinrobinson** [comment]
Awesome!  Please just @ me directly if there's anything you need a hand with or that I can review whenever it's ready to merge.

I'm excited about this line of work!
