### ISSUE TITLE
Add JS error reporting service

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#197]
Potentially https://rollbar.com/, https://airbrake.io/, or https://getsentry.com/welcome/

**Comment by alexsoble** [comment]
Will do later this week! :+1:

**Comment by alexsoble** [comment]
@kevinrobinson Invited you as a Rollbar collaborator! Join and I'll send a test JS error to confirm it's all up and running smooth.

**Comment by alexsoble** [comment]
Rollbar up, running, and notifying!
