### ISSUE TITLE
Improvements to "Development on OS X with Docker" tutorial

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#202]
These are some notes that I took last session, after helping Dave and running into some hiccups.

1. What to do after installing VirtualBox?
2. What is happening after the "Install Docker on OS X" tutorial?
3. Do you have to manually set up VirtualBox?
4. Docker-machine link should be highlighted as link

5. Add docker equivalent for bundle exec rake db:create db:migrate db:seed:demo
6. JUST THE IP from docker-machine env should go into /etc/hosts.
7. What rake tasks do we run from the cmd line here?

**Comment by kevinrobinson** [comment]
@erose awesome, thanks for capturing this! :+1:

**Comment by alexsoble** [comment]
@erose Looks like this is going along great! In your estimation, does #340 close this issue or is there still more work to be done on the docs here?

**Comment by erose** [comment]
I think we're done. Closed!
