### ISSUE TITLE
Improve ability to manually test authorization rules in demo environment

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#205]
There's good automated testing of this in https://github.com/studentinsights/studentinsights/blob/master/spec/controllers/students_controller_spec.rb, but since there's a fair bit of logic in these rules it might be useful to update the seed data to create some more students and educators so that we are regularly exercising these code paths in local development.  That might help get more manual coverage of these code paths for free.

**Comment by alexsoble** [comment]
Right now the seed files makes two classroom teachers at different schools and one district-wide admin . . . I think this addresses the issue for now? Closing but feel free to re-open.
