### ISSUE TITLE
Investigate adding foreign key constraints or validations

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#209]
There was a minor database-level data integrity bug I introduced in https://github.com/studentinsights/studentinsights/pull/206, and is now fixed.  I was mixed up about `validates_presence_of`, and it'd be great to tighten these all to foreign key constraints (or the Rails validation equivalent).

**Comment by eudaimonious** [comment]
working on this now

**Comment by erose** [comment]
Hey @eudaimonious, if you're still working on this, can you assign yourself? (If not, no pressure!) Helps people navigate the issues list to see what they can work on.

**Comment by eudaimonious** [comment]
Thanks Eli! Looks like I have access to do that sort of stuff with gh issues now. Yay! Well, I merged the change but I know that caused some failures due to production data. I'm closing this but @kevinrobinson might want to re-open or start a new issue if this did indeed get rolled back.

**Comment by erose** [comment]
@eudaimonious: Yup, I added you as a "collaborator" on Github (not sure if you get notified about that), so you now have full write access here.
