### ISSUE TITLE
Grade-level view for classroom teachers

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#21]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/123.

**Comment by Jrafalak** [comment]
Hey @alexsoble, I'm interested in working on this. Is there any more clarity on the ideal implementation for this? As in a version of the school overview dashboard scoped to their grade level vs. revising the roster page to allow grade-level access.

**Comment by kevinrobinson** [comment]
stale, this would need more explicit scoping (eg, we tried this for reading teams making groups).
