### ISSUE TITLE
Process for improving working with mutable data in staging

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#216]
Right now the staging environment doesn't have realistic values for mutable data that is owned by the production Student Insights instance.

This might be useful for testing, so it would be a nice-to-have feature to copy this from production each day as part of the staging workflow.  Concretely, this would be a rake task for production to dump the SQL for these tables, another rake task for staging to insert it, and a runner script to coordinate.

**Comment by kevinrobinson** [comment]
An initial sketch:

```
# Mutable data that are authoritatively owned by Student Insights
mutable_values = {
  event_notes: EventNote.all.as_json,
  services: Service.all.as_json,
  # discontinued_services: DiscontinuedService.all.as_json,
  interventions: Intervention.all.as_json,
  progress_notes: ProgressNote.all.as_json,
  student_notes: StudentNote.all.as_json,
  educators_usage: Educator.all.map do |educator|
    educator.slice(:sign_in_count, :current_sign_in_at, :last_sign_in_at, :state_id, :full_name)
  end
};nil

# Mappings between authoritative Aspen identifiers and instance-local Student Insights primary keys
identity_mappings = {
  student_school_years: StudentSchoolYear.all.as_json,
  students: Student.all.map do |student|
    student.slice(:id, :local_id, :state_id, :first_name, :last_name, :homeroom_id)
  end,
  homerooms: Homeroom.all.map do |homeroom|
    homeroom.slice(:id, :name, :slug, :grade, :educator_id)
  end,
  schools: School.all.as_json,
  educators: Educator.all.map do |educator|
    educator.slice(:id, :email, :local_id, :state_id, :full_name, :school_id)
  end
};nil


puts {
  mutable_values: mutable_values,
  identity_mappings: identity_mappings
}.to_json
```

**Comment by erose** [comment]
Clarifying question: is this talking about copying e.g. Notes + Services from production to staging? Wouldn't that be sensitive student information?

**Comment by alexsoble** [comment]
> Clarifying question: is this talking about copying e.g. Notes + Services from production to staging? 

Yes, exactly.

> Wouldn't that be sensitive student information?

Correct. But staging is private — just like production. It uses Somerville's LDAP system for authorization, just like production. The only public-facing website is the demo site. @erose

**Comment by alexsoble** [comment]
We don't have a staging site any more so this issue is closeable.
