### ISSUE TITLE
Discipline: Remove selection labels from table

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#2173]
In https://github.com/studentinsights/studentinsights/pull/2132, the selection for charts is now awesomely shown with color (orange).  This makes it obvious when something is selected, and shows the user where that selection is occurring (ie, it's from clicking on that bar on the chart itself).

Also, when adding more filters like in https://github.com/studentinsights/studentinsights/issues/1661, the label "All students" would become misleading and we'd have to update it if we kept it.  Instead, we can remove that and let the filters describe themselves, and any other selection in charts be expressed with color.

So one proposed solution is to remove the label and selection notice on the table.  In this screenshot, that's the text "Parking" and the orange "Reset students (ESC)":

<img width="1195" alt="screen shot 2018-10-11 at 11 56 50 am" src="https://user-images.githubusercontent.com/1056957/46817371-f9fb3a80-cd4c-11e8-9f34-e97a2e041580.png">

**Comment by edavidsonsawyer** [comment]
@kevinrobinson sorry I missed this! I was in the middle of modifying this for #2186 anyway.

One suggestion I have is that I'd like to keep some indication that ESC will reset the filters. Maybe as a static line that appears when any selection (dropdown, chart, whatever) is made. What do you think of that? It doesn't have to be orange - that will probably get tiresome since it seems like the normal case is for users to filter on something.

**Comment by kevinrobinson** [comment]
@edavidsonsawyer Yeah, I agree that orange is too salient, but am wondering about why teachinga bout the keyboard shortcut is important.  To me, the "escape clears the selection" is a small detail for power users, and something most people are unlikely to use.  So because of that, it doesn't seem like a good use of screen space for most people if we use that to explain about a keyboard shortcut.  If the user need is to "clear all filters quickly," we could add a "reset" text link that is to the right of the filters, and only shows when there are non-default filters.

That being said, the real issue is that the current labels will become misleading when adding new filters, so let's address that first (which maybe you already did in https://github.com/studentinsights/studentinsights/pull/2186 :)).

**Comment by kevinrobinson** [comment]
This is done!
