### ISSUE TITLE
Full case history - section breaks across school years

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#218]
This is with demo data, so it's not the best example, but with all the absence and tardy data it's hard to see milestone dates like the beginning of a new school year.

 <img width="600" alt="screen shot 2016-03-21 at 8 59 19 am" src="https://cloud.githubusercontent.com/assets/1056957/13919335/36248ca4-ef43-11e5-825b-b7d2f14acd71.png">

One idea might just be adding a heading for the start of each school year, or perhaps using the box styling for sections that @bw120 is awesomely trying out in https://github.com/studentinsights/studentinsights/pull/199.

**Comment by erose** [comment]
Good idea -- I'll make a new branch and try the different styling options out.

**Comment by vrogers** [comment]
spoke with @erose I'm taking a stab at this, in case anyone's curious
