### ISSUE TITLE
Profile page - Add grade-level equivalent to STAR scores for ELA and Math

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#229]
From talking with @jgeiser, she in particular prefers grade-level equivalents over percentiles, and other principals or teachers may as well.  We should be opinionated from an educational perspective about which should be used as the primary measure (percentiles, at the moment), but should show both perspectives in the details view or charts.

Split out from https://github.com/studentinsights/studentinsights/issues/5.

**Comment by erose** [comment]
Hey @kevinrobinson, I'm interested in working on this -- how do we get the percentile to grade-level-equivalent mapping?

**Comment by kevinrobinson** [comment]
@erose Awesome!  I don't quite know - this norming is specific to the particular STAR assessment, so we'll have to pull it in from that data.

For reading it looks like it might be `instructional_reading_level`, but I'm not entirely sure: https://github.com/studentinsights/studentinsights/blob/master/app/importers/file_importers/star_reading_importer.rb#L19.  For math it might be the same but not currently imported: https://github.com/studentinsights/studentinsights/blob/master/app/importers/file_importers/star_math_importer.rb#L19.

This investigation will likely require looking at the actual student data from STAR, so it might not be the simplest one to take end-to-end, but @alexsoble might have some good ideas about this.

**Comment by erose** [comment]
@alexsoble Do you know where the data for this lives?

**Comment by alexsoble** [comment]
Took a look at the STAR data. We've got this! 

STAR Math and Reading CSVs include a "GradeEquivalent" column. I quickly compared "GradeEquivalent" versus "CurrentGrade" for each row, it passes the sanity check.

To productionize, we'd do a migration and tweak the STAR import scripts to add new column. We should do some no-code design mockups for how we'd visualize before we pull in new data.

For STAR Reading, we have both "GradeEquivalent" and "InstructionalReadingLevel". A glance at the data shows them to be highly correlated, but not identical. We could look at STAR docs to learn about the difference between the two metrics.

@kevinrobinson @erose

**Comment by alexsoble** [comment]
Instructional Reading Level vs. Grade Equivalent: 

http://help.renaissance.com/sr/irl

http://help.renaissance.com/sr/ge

**Comment by erose** [comment]
Great. From the descriptions, looks like there's nothing that's *exactly* grade level in some absolute sense, but GradeEquivalent is performance relative to others in the grade nationally.

So that seems like the best bet. I'll think about a mockup and post it here when I've got it.

https://github.com/studentinsights/studentinsights/pull/427 also (may) require importing new stuff, so maybe we should do them together?

**Comment by kevinrobinson** [comment]
We did this, it's shown on the chart.  For various reasons, percentile rank is still the overall value used.
