### ISSUE TITLE
Refine DIBELS information in profile

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#23]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/299.

**Comment by kevinrobinson** [comment]
Part of https://github.com/studentinsights/studentinsights/issues/5

**Comment by kevinrobinson** [comment]
Let's close this, we got more specific today with https://github.com/studentinsights/studentinsights/issues/23 that can replace this issue.
