### ISSUE TITLE
STAR charts - Design, UX and visualization feedback

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#232]
This is feedback from Dimos at Code for Boston about the prototype STAR charts, and is part of https://github.com/studentinsights/studentinsights/issues/2.

1) on the graph 'Group quartiles each period, all-time', instead of the current histogram representation for each point in the time series use something like seaborn's violinplot (python library). https://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.violinplot.html this is a more visually appealing demonstration of the mean and quartiles. At the same time you get to see all the data for each time period.

2) Label all the graphs! 

3) Scale the 'Performance compared to growth, last assessment'  graph in some creative way to control for the fact that it is easier to get from the 20th to the 30th percentile than from the 90th to the 99th. Also control for other characteristics that can impede growth so that we assign a growth rate that is normalized across students

4)Propose to schools of ways to capture electronically more student data. We could even go to schools and scan the student essays, apply some computer vision algorithm on them and then do text analytics on the digital form of the essays.

**Comment by kevinrobinson** [comment]
Thanks to Dimos at Code for Boston for this awesome feedback! :)

**Comment by kevinrobinson** [comment]
Related to feedback in https://github.com/studentinsights/studentinsights/issues/79#issuecomment-184983093

**Comment by alexsoble** [comment]
We're not pushing forward on the STAR pages right now, closing this issue
