### ISSUE TITLE
Fix bug with star_results being undefined

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#234]
From https://rollbar.com/somerville-teacher-tool/somerville-teacher-tool/items/11/, reproduced on https://somerville.studentinsights.org/schools/hea/star_reading#equal%3Agrade%3A5&equal%3Ahomeroom_name%3AHEA%20205 in production.

**Comment by kevinrobinson** [comment]
part of https://github.com/studentinsights/studentinsights/issues/2

**Comment by eudaimonious** [comment]
Getting an access denied on the rollbar...

**Comment by kevinrobinson** [comment]
@eudaimonious ah yeah sorry about that.  here's the raw info:

<img width="955" alt="screen shot 2016-04-05 at 9 38 46 pm" src="https://cloud.githubusercontent.com/assets/1056957/14303232/cd40d036-fb76-11e5-9a03-e91344bac44d.png">

I didn't invite folks initially, since conceivably the data here or in stack traces could reveal student information from the production deployment.  Let me see if there's a way to do that safely, would be much better for everyone to just be able to see those rollbar links :)

**Comment by kevinrobinson** [comment]
@alexsoble any thoughts on student privacy risks with inviting @eudaimonious or other awesome people to Rollbar?  I had initially thought safer to avoid, but not sure it actually matters, what do you think?

**Comment by alexsoble** [comment]
Going to close this since it's been inactive (my bad!) and since then we've downgraded the importance of the STAR page to beta/experimental.
