### ISSUE TITLE
Get the project work in vagrant 

### ISSUE THREAD

**Issue by ronny2205** [studentinsights/studentinsights#238]
Just a note:
I use vagrant environment that works with an existing postgres setup. 
In order to make the project run, I had to edit my local database.yml file by adding the following to both development and test sections:
username: [the setup username]
password: [the setup password]

**Comment by kevinrobinson** [comment]
@ronny2205 Awesome, thanks for adding this!  To clarify, what goes in `[the setup username]`, is it the particular usernames you had set up in your Vagrant environment?

Alternately, it'd be great to check in a Vagrantfile for this project and add this to the [Install dependencies](https://github.com/studentinsights/studentinsights#1-install-dependencies) section of the docs.  You're the first Vagrant user, so I'll follow your lead on what's most helpful here. :)

Thanks again!

**Comment by ronny2205** [comment]
@kevinrobinson,
Yes, [the setup username] is the particular usernames I had set up in my Vagrant environment.

**Comment by ronny2205** [comment]
I can try add a Vagrantfile as well

**Comment by kevinrobinson** [comment]
:+1:

**Comment by alexsoble** [comment]
@ronny2205 Is this issue still active?
