### ISSUE TITLE
Attach documents e.g., referrals, progress monitoring

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#24]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/337.

**Comment by kevinrobinson** [comment]
From talking it out with @jnowell, here's the rough product direction:

- The first use case is for administrators or teachers to upload a document (eg., a report or a parent letter or any other paper documents).
- The idea is that these will be uploaded one at a time, and will be for a particular student.
- We're not sure exactly on the user interface but will be, but will assume it's somewhere on the student profile page for now.
- The user interaction shouldn't need a full page reload (eg., Ajax-style upload).

**Comment by jonchar** [comment]
Thinking how to integrate attachments with the current student model: we want to allow multiple uploads per student correct?

I'm eyeing the [carrierwave](https://github.com/carrierwaveuploader/carrierwave/tree/0.11-stable) gem for handling uploads nicely.

Thoughts?

**Comment by jnowell** [comment]
Yeah, our thinking was for it to be multiple uploads per student. The carrierwave gem was the same gem I was looking at. I had begun some work on this locally, but then life got in the way and haven't been able to commit time to it last couple of weeks. I won't be able to make it tomorrow as I'm in California for work, but will be back in Boston next week so planning to stop by to the next meeting. Feel free to take the lead on it, Jon.

**Comment by jonchar** [comment]
Just thinking in the open for changes to the backend:

1. Create a db migration `rails g migration CreateStudentDocuments filename:string content_type:string file_contents:binary`
2. Also add a foreign key to the table referencing a `student_id`
3. Add a `student_document.rb` to `app/models/` with `belongs_to :student`
4. Change `student.rb` in `app/models/` to have `has_many :student_documents`

Then we should be set up to store documents and relate them to students. Front-end approach forthcoming...

**Comment by kevinrobinson** [comment]
@jonchar Sounds good, thanks for sharing your thoughts!

**Comment by jnowell** [comment]
Hey Jon,

Yeah, that's pretty much exactly what I had done, and consistent with the changes I had locally. I didn't have the file_contents as an attribute of the document, but now that I think of it, it makes sense to have that.

**Comment by jonchar** [comment]
Hey @jnowell, Great to know we were thinking the same. Next steps I'm looking at are:

1. Make a React component for uploading a file.
2. Pass the file to Rails, store it in the database.
3. Validate the reverse will work for retrieving uploaded documents.

Will we eventually want some sort of in-browser viewer for what gets uploaded? I'd imagine that would be more convenient than re-downloading, but maybe I'm thinking too far ahead.

**Comment by kevinrobinson** [comment]
@jonchar sounds awesome!  I think for the first iteration, having the user download the file is great.  Viewing the contents of particular file types (eg., PDFs or images) inline in the browser is a great idea and would be nice, but that's next-level so I'd table it until the first iteration is functional.

**Comment by alexsoble** [comment]
We have a early version of this in place where educators can attach links to external documents on the web to Insights notes.
