### ISSUE TITLE
3/29 Code for Boston agenda

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#240]
Last week: #208 (comment).

**Review priorities (umbrella issues):**
  * current: finish Student profile improvements
    * ???
  * next: Productionize visualizations of STAR academic progress
  * after: SPED referral form

**Help finish what's in progress:**
  * Finish any work-in-progress you own
  * Help anyone else with work-in-progress if you can (keeping in mind that sometimes piling on more people doesn't help)
  * Check out work that's left over from last week.
  * Check open pull requests
  * Umbrella issues - see if there's a clear piece you can get done on one of the open issues

**Start some new work:**
  * Fix an Open bug
  * Start on a help wanted issue
  * Start a brand new feature
  * Talk it out with Kevin if you have questions or if you're stuck

**Help new folks pitch in:**
  * Coordinating tonight: @erose
  * Talk about any questions from the project overview
  * Help them set up development environment
  * Show them the agenda issue and our workflow

**Comment by erose** [comment]
Questions for Kevin:

**Comment by kevinrobinson** [comment]
@erose Thanks for adding this!  I added #249 to capture an answer to your question about keyboard navigation too.

**Comment by kevinrobinson** [comment]
Also, I think if there's no new input then it's reasonable to use the same product prioritization from the last week. :)
