### ISSUE TITLE
Extract button UI

### ISSUE THREAD

**Issue by jochakovsky** [studentinsights/studentinsights#244]
In the student profile page, the button UI is defined in both take_notes.js and in record_service.js (and perhaps elsewhere?). There are some inconsistencies in styling between the two, such as the outline attribute being set to 0px on one but not the other.

Maybe create a new button component?

**Comment by kevinrobinson** [comment]
@jochakovsky You either read my [TODOs](https://github.com/studentinsights/studentinsights/blob/master/app/assets/javascripts/student_profile_v2/take_notes.js#L144) or my mind, and either way is great :)

This would be awesome and a most welcome contribution!  Let me know if there's anything I can do to help point you in the right direction or get this started.

**Comment by jochakovsky** [comment]
@kevinrobinson Yup, noticed the to-do comment :)

**Comment by erose** [comment]
Hi Josh, is this still live? I just ask because inhttps://github.com/studentinsights/studentinsights/pull/429 you're saying maybe let's not refactor after all.

If you've decided not to do it after all, let's document that and close the issue.

**Comment by jochakovsky** [comment]
@erose Yeah, I don't think I'm going to refactor. Closing the issue. Feel free to re-open if you feel it would be valuable.
