### ISSUE TITLE
Switch to database-level dependent: destroy cascades

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#246]
From looking at https://robots.thoughtbot.com/referential-integrity-with-foreign-keys, it seems we can also move `dependent: destroy` expressions here too.  I don't think we're super rigorous about that at the moment, but would be a good improvement after we land https://github.com/studentinsights/studentinsights/pull/241.

**Comment by alexsoble** [comment]
Talking this through with @kevinrobinson ... we don't have a high-priority reason to do this, so let's 🚫  the PR.
