### ISSUE TITLE
Fix bug with Risk Level 0 or N/A on student profile page

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#250]
See https://somerville-teacher-tool-demo.herokuapp.com/students/2/profile for an example of this bug.

<img width="1323" alt="screen shot 2016-03-30 at 11 01 18 pm" src="https://cloud.githubusercontent.com/assets/1056957/14164243/bb4f7440-f6cb-11e5-899d-f2c94a80220b.png">

Related to #108, so perhaps @BWieber you might have an idea about this?  I imagine there's just an `if` condition missing or something like that.

**Comment by BWieber** [comment]
Hi Kevin, 

I'll take care of this one - I imagine it's something simple :)

**Comment by BWieber** [comment]
Hi Kevin, 

I investigated this bug and it looks like there was already a fix for it: 

```
var RiskBubble = window.shared.RiskBubble = React.createClass({
    displayName: 'RiskBubble',

    propTypes: {
      riskLevel: React.PropTypes.number.isRequired
    },

    render: function() {
      return dom.span({},
        dom.span({
          style: styles.riskItem
        }, 'Risk Level'),
        dom.span({
          style: merge(styles.riskBubble, { backgroundColor: this.bubbleColor() })
        }, (this.props.riskLevel === null) ? 'NA' : this.props.riskLevel)
      );

    },

    bubbleColor: function() {
      if (this.props.riskLevel === null) return '#555555';
      if (this.props.riskLevel === 0) return '#bbd86b';
      if (this.props.riskLevel === 1) return '#62c186';
      if (this.props.riskLevel === 2) return '#ffcb08';
      if (this.props.riskLevel === 3) return '#f15a3d';
    }
  })
```

A null setting was already handled with a sweet ternary operator. Let me know if you find anything similar concerning the risk level. 

_Brandon_

**Comment by kevinrobinson** [comment]
@BWieber sweet, sounds good then!
