### ISSUE TITLE
Restore spec exercising react-select code for choosing an educator providing a service

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#262]
See https://github.com/studentinsights/studentinsights/blob/81fa04f858163c98d556acb2e79639c110f19c50/spec/javascripts/student_profile_v2/page_container_spec.js#L105

**Comment by alexsoble** [comment]
Closing since I don't see much forward motion on this. :D

**Comment by awalker4** [comment]
Yeah, my bad! I'd like to start contributing again at some point since I actually live in the area now. I'll have to see when I can find the time. I hear you guys haven't met at CfB recently?
