### ISSUE TITLE
Investigate student_school_years records referring to nonexisting student_ids

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#264]
This came up trying to run the migration to add foreign key constraints in https://github.com/studentinsights/studentinsights/pull/241.

```
PG::ForeignKeyViolation: ERROR:  insert or update on table "student_school_years" violates foreign key constraint "student_school_years_student_id_fk"
DETAIL:  Key (student_id)=(512) is not present in table "students".
```

In production, there is a gap in student primary keys (from 512-610):
```
irb(main):008:0> Student.all.map(&:id).sort.size
=> 518
irb(main):009:0> Student.all.map(&:id).sort.last
=> 617
```

The next check I ran was:
```
StudentSchoolYear.where(:student_id => (512..617)).size
=> 111
```

I had been hoping this was just a stray record or two and I could remove it manually, but then I stopped since this clearly needs a closer look.  I'm not sure there are actual any data quality issues, but we'll need to figure out what's up here and fixup in order to unblock https://github.com/studentinsights/studentinsights/pull/241.

cc @alexsoble

**Comment by kevinrobinson** [comment]
Just ran into https://github.com/studentinsights/studentinsights/issues/185, possibly related.

**Comment by alexsoble** [comment]
Before running migration to get rid of junk student school years:

`StudentSchoolYear.count # => 2824`

**Comment by alexsoble** [comment]
After running migration: 

`StudentSchoolYear.count # => 2725`

**Comment by alexsoble** [comment]
Data `IntegrityCheck` now runs without throwing any errors.    

👍

**Comment by kevinrobinson** [comment]
:tada: :smile:
