### ISSUE TITLE
Fix bug with horizontal scrolling on roster table

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#267]
It doesn't work to scroll horizontally for me at the moment, this must have regressed at some point.  Related to https://github.com/studentinsights/studentinsights/issues/88.

**Comment by awalker4** [comment]
Hey @kevinrobinson is this still an issue? Scrolling seems to work for me but I could be missing what the bug looks like.

**Comment by kevinrobinson** [comment]
@awalker4 Thanks for checking this out!  It still seems to be a problem to me, looking at https://somerville-teacher-tool-demo.herokuapp.com/homerooms/3.

It may be the `display:block` on `#roster-table`, which we might be able to remove and see if it helps.  In poking around in web inspector, removing that made scrolling work.  But then after refreshing the page scrolling just worked again, so I'm not sure but I suspect simplifying the CSS rules might help.

**Comment by alexsoble** [comment]
Roster table JS is getting rewritten entirely anyway so this may not be an issue on the new page.
