### ISSUE TITLE
Update AuditJS to 4.0.x

### ISSUE THREAD

**Issue by DarthHater** [studentinsights/studentinsights#2795]
Hi there!

I work on AuditJS, and we've released a newer version of it. Figured I'd pop in and give you a heads up!

The usage has changed a tiny bit, if you want help updating I'll gladly send you a PR!

https://www.npmjs.com/package/auditjs

Cheers

**Comment by kevinrobinson** [comment]
@DarthHater hello!  Sure, it sounds like you could help out over https://github.com/sonatype-nexus-community/auditjs/issues/192 and https://github.com/sonatype-nexus-community/auditjs/issues/193.

I'm going to close this issue as upgrading this particular dependency is not a major priority for our project right now.  Given there are diffs with thousands of lines of changes and no documentation, it's all risk with no upside.  If that changed I'd be excited to revisit, so will check back in later with what happens over in auditjs.

Thanks! 👍
