### ISSUE TITLE
Add DIBELS to ELA summary for K-3

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#291]
Students in grades K-3 don't have MCAS ELA growth but do have DIBELS scores. In the summary boxes at the top of Profile V2 let's make that substitution for students grades K-3.

**Comment by kevinrobinson** [comment]
And also show the graphs for both below regardless (for students that are say in 4th grade now but still have DIBELS data from last year).  @alexsoble I'm figuring the charts below are straightforward if we have the yearly data required for the summary section, but we should split that bit out if it's more involved, definitely lower priority like you suggested the other day.
