### ISSUE TITLE
Precompute data for school overview page

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#3]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/412

Speed things up!
Precompute assessment results, attendance, discipline incidents — anything that is updated in the database daily or less frequently, and merge in interventions data.

**Comment by kevinrobinson** [comment]
Starting point: https://github.com/studentinsights/studentinsights/compare/feature/more-students-and-homerooms?expand=1

**Comment by alexsoble** [comment]
This is happening now! It speeds things up tremendously, i.e. around 20x in the West Somerville case:

https://github.com/studentinsights/studentinsights/issues/332#issuecomment-209670375

Awesome work @kevinrobinson, thanks for building this and making the page way faster!
