### ISSUE TITLE
`rake db:setup` is broken

### ISSUE THREAD

**Issue by jochakovsky** [studentinsights/studentinsights#319]
Thank you @kbweaver for doing most of the work on this one.

When creating a database, precomputed_student_hashes_docs.key will have an integer type if you use the commands suggested in the docker readme: `# bundle exec rake db:setup db:seed:demo` But if you use the command suggested in README.md, `# bundle exec rake db:create db:migrate db:seed:demo`, it will have the correct Text data type.

It seems like db/migrate/20160403183327_increase_precomputed_student_hashes_doc_key.rb changes this column in a way that is not reflected in db/schema.rb, so does not get done when db:setup is run, which just runs db:schema:load and db:seed. Not too comfortable with rails, so I'm not sure what the best way is to proceed.

**Comment by jochakovsky** [comment]
A few maybe-related links:

https://github.com/rails/rails/issues/14169
https://github.com/rails/rails/blob/v4.1.14.1/activerecord/lib/active_record/schema_dumper.rb#L122-L128
http://www.lshift.net/blog/2013/09/30/changing-the-primary-key-type-in-ruby-on-rails-models/

Seems like Rails <5.0 may not play nicely with non-integer non-UUID primary keys.

**Comment by kevinrobinson** [comment]
@jochakovsky @kbweaver Thanks for your help with this, and sorry for leaving this in not a great state, I thought I had gotten it all buttoned up.  This should be completely fixed now via https://github.com/studentinsights/studentinsights/pull/320 and the follow-on work, but please let me know if you run into any other issues with this.
