### ISSUE TITLE
Improve labeling on Student Profile V2 Summary boxes

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#330]
Attended today's Student Support Team meeting at the Healey school to observe how they used Student Insights. One thing I noticed:

A UI issue caused some confusion during the meeting. One student had an "Absences count" of 3 noted in her summary box at the top of the profile. The staff wanted to double-check that number and so they looked at the student's activity feed. There were many more than 3 absences in the activity feed. It wasn't clear to the staff that the "Absences count" listed at the top referred only to absences in the current school year, not overall number of absences.

Clearly labeling which values refer to current school year only would be helpful here. May also be useful to segment the activity feed events by school year, with headers for each school year. Finally, we may also want some kind of label for the spark lines to make it clear that they are all-time trends as opposed to the current-school-year-only figures directly above them.

**Comment by erose** [comment]
Segmenting the feed events by school year should be done, I agree. It's #218.

**Comment by erose** [comment]
#218 will be fixed when #399 is merged.

**Comment by erose** [comment]
Note to self: we are now going with bar chart sparklines instead of arrows.

**Comment by erose** [comment]
Closing this in favor of #593.
