### ISSUE TITLE
Include DIBELS information under ELA tab

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#331]
Attended today's Student Support Team meeting at the Healey school to observe how they used Student Insights. One thing Uri Harel noticed:

DIBELS information should be included under the ELA tab in addition to the student activity feed.

**Comment by BWieber** [comment]
Hi Alex, 

After researching this issue for a bit, I found out that there is no graph for DIBELS data, or not, at least, one that I know about. Whenever DIBELS data is shown it says things like **STRATEGIC** and **INTENSIVE**, and renders nothing in the sections below. 

Here is the code for the rendering of the ELA Column:

```
renderELAColumn: function() {
      var student = this.props.student;
      var chartData = this.props.chartData;
      var columnKey = 'ela';

      return dom.div({ style: styles.columnContainer, onClick: this.onColumnClicked.bind(this, columnKey) }, dom.div({ style: merge(styles.tab, this.selectedTabStyles(columnKey)) }, "Reading"),
      dom.div({
        className: 'ela-background',
        style: merge(styles.column, styles.academicColumn, this.selectedColumnStyles(columnKey)),
        onClick: this.onColumnClicked.bind(this, columnKey)
      },
        this.wrapSummary({
          caption: 'STAR Reading',
          value: student.most_recent_star_reading_percentile,
          sparkline: this.renderSparkline(chartData.star_series_reading_percentile || [])
        }),
        this.wrapSummary({
          caption: 'MCAS ELA Score',
          value: student.most_recent_mcas_ela_scaled,
          sparkline: this.renderSparkline(chartData.mcas_series_ela_scaled || [], {
            valueRange: Scales.mcas.valueRange,
            thresholdValue: Scales.mcas.threshold
          })
        }),
        this.renderMcasElaSgpOrDibels()
      ));
    },
```

The code we're looking at primarily is: `this.renderMcasElaSgpOrDibels()`:

```
renderMcasElaSgpOrDibels: function () {
      var student = this.props.student;
      var chartData = this.props.chartData;
      var grade = student.grade;
      var dibels = _.sortBy(this.props.dibels, 'date_taken');

      var belowGradeFour = _.includes(['KF', 'PK', '1', '2', '3'], grade);
      var hasDibels = (dibels.length > 0);

      if (belowGradeFour && hasDibels) {
        var latestDibels = _.last(dibels).performance_level.toUpperCase();
        return dom.div({ style: styles.summaryWrapper },
          createEl(SummaryWithoutSparkline, { caption: 'DIBELS', value: latestDibels })
        );
      } else {
        return this.wrapSummary({
          caption: 'MCAS ELA SGP',
          value: student.most_recent_mcas_ela_growth,
          sparkline: this.renderSparkline(chartData.mcas_series_ela_growth || [])
        })
      }
    }
```


 In the case of a student below the 4th grade, their SGP data (which they _do_ have) is no longer shown on the chart, but their graph is rendered at the bottom of the page. This seems like odd behavior, and their DIBELS information should be included in addition to their SGP data. If there is any chart associated with DIBELS, let me know and I can get it linked up to the rest of graphs :) 

_Brandon_

**Comment by kevinrobinson** [comment]
@BWieber Awesome, thanks for looking into this!  The branching between DIBELS and ELA has to do with the specifics of these assessments - DIBELS is focused on early literacy skills like oral reading fluency, and so is only used with younger students.  MCAS doesn't start until the 3rd grade, and so student growth percentiles (SGP) are only first available in 4th grade.

So for younger students, DIBELS is really important, but for older students, it's not and SGP is more important for understanding their progress in ELA skills.  You can find out more by checking the [git blame](https://github.com/studentinsights/studentinsights/blame/4ec0e1149969a62c82fa6048b648d83bd2ed0a5e/app/assets/javascripts/student_profile/student_profile_page.js#L364) for the code you awesomely found, and then follow the issue trail to https://github.com/studentinsights/studentinsights/issues/291.

For graphs, one option is to do something like [this](https://github.com/studentinsights/studentinsights/blob/master/docs/readme_images/profile-mcas.png) which might not be in the codebase anymore but is still in git somewhere.  Or it might also be worth googling for how DIBELS scores are typically shown over time or asking some school amigos.

**Comment by erose** [comment]
Is CORE intentionally not on the same line as DIBELS in the Math tab?
<img width="222" alt="screen shot 2016-04-30 at 12 26 07 am" src="https://cloud.githubusercontent.com/assets/1514487/14933849/5602a862-0e6a-11e6-9a06-2c4b5a2b0baa.png">

**Comment by erose** [comment]
Hey @BWieber are you working on this right now? If so, can you assign yourself on github? -- it helps us tell what's free to work on, especially for new folks.

If not, no pressure. : > ].

**Comment by BWieber** [comment]
@erose Got it Eli ;)

**Comment by erose** [comment]
@BWieber: Hey, it's been a while so I'm going to unassign you from this. No worries. If you're still working on it, just pop back in and reassign yourself!

**Comment by kevinrobinson** [comment]
We're doing this with individual assessments as part of the reader profile work.
