### ISSUE TITLE
Bar charts instead of line charts for absences, tardies, discipline incidents

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#343]
Visited the 6th grade teacher team at the Healey school this morning to show them the latest iteration of Student Insights and get their feedback.

The teacher team found the peaks and valleys in the attendance/tardies charts confusing. It looked to them like the students were making progress at the end of each year when the line fell, because it wasn't obvious that the line represented cumulative values over each school year:

![absences line chart](https://cloud.githubusercontent.com/assets/3209501/14475304/57a4806c-00cf-11e6-84ef-9a22e0857a95.png)

The teacher team and Jill had an alternative suggestion: using bar charts. The bar could show the number of absences/tardies/discipline incidents as the height, with the month on the X-axis. This would allow educators to see change in absences or tardies over a single school year while making the data easier to read.

**Comment by erose** [comment]
I also found the "line graph representing cumulative data" thing very unintuitive. I didn't realize that's what the graphs were showing until I was working on them in the code. (though, unlike teachers I wasn't trying to get actual information out of them).

Alex I'm not sure from your verbal description what the bar chart would look like, but we can clear it up at CFB.

**Comment by alexsoble** [comment]
@erose Yeah! Basically just "bar charts with months as the X axis". Can draw at CFB.  😊  🎨  📷

**Comment by erose** [comment]
Oh, right.

**Comment by alexsoble** [comment]
Sat down with Uri Harel and the principal at West Somerville today to review the West Somerville data. Reinforced that this is an important change to make. 

The big drop at the end of each school year when the cumulative count sets back to zero — to the principal that looked intuitively like a big attendance improvement and she was wondering if those drops in attendance problems could be attributed to the intervention of a truancy officer.

**Comment by alexsoble** [comment]
Taking away the "suggestion" bit now that we've added this to scope.

**Comment by erose** [comment]
@alexsoble @kevinrobinson Shall I start working on a prototype implementation for this?

**Comment by kevinrobinson** [comment]
@erose Yeah if you're able to work on this go for it!

**Comment by erose** [comment]
Very rough prototype completed, I can show you guys tonight and we can see where to go from there!

**Comment by kevinrobinson** [comment]
awesome!

**Comment by alexsoble** [comment]
@erose I want to see!  😊
