### ISSUE TITLE
Fix bug with sorting students table by risk level in roster

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#344]
The roster table can't handle sorting `null` risk level:

![screen shot 2016-04-12 at 7 52 48 am](https://cloud.githubusercontent.com/assets/3209501/14475412/dc3c37de-00cf-11e6-8799-c69f00a46466.png)

**Comment by BWieber** [comment]
I'll jump on this ~

**Comment by alexsoble** [comment]
Fixed via @brisandbeans commits above!
