### ISSUE TITLE
Show grades in addition to school years on profile chart X-axis

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#345]
Visited the 6th grade teacher team at the Healey school this morning to show them the latest iteration of Student Insights and get their feedback.

They mentioned that instead of only showing school years on the X-axis of charts, it would be more intuitive for them if the charts included grade level information as well: "Grade 5, 2012-2013".

**Comment by erose** [comment]
On it.

**Comment by erose** [comment]
Eli and Kevin's notes from CFB: So this is being addressed mostly by #427, the only thing is that we don't know which grade the student was in which year. We can assume that if they were in grade 5 now, they were in grade 4 last year, etc., and it seems like it might not be that bad an assumption.

So we can go ahead and do that. But I wanted to check with you @alexsoble -- do you know if it's easy to get this data? Do you think it's better to assume or to try and do the import?

**Comment by erose** [comment]
Confirmed by John Breslin that a very low number of students get held back in K-8, and the relevant data is off in some scary place in the system, so we should just assume and provide a footnote saying "we assumed that...".

**Comment by erose** [comment]
Related to #510.

**Comment by erose** [comment]
<img width="1226" alt="screen shot 2016-05-24 at 8 43 52 pm" src="https://cloud.githubusercontent.com/assets/1514487/15524430/53e259d0-21f0-11e6-8130-b4721a195991.png">
<img width="1224" alt="screen shot 2016-05-24 at 8 43 36 pm" src="https://cloud.githubusercontent.com/assets/1514487/15524431/56b7cd48-21f0-11e6-8957-148ee403e4e9.png">

**Comment by iamctodd** [comment]
Here's a suggestion for adding some visual grade breakdowns for these graphs as well as callouts for any interventions that may have occurred. 
<img width="1073" alt="graph-1" src="https://cloud.githubusercontent.com/assets/1851211/15525070/b9f55d72-21f4-11e6-879a-af4fb4771cd3.png">

**Comment by erose** [comment]
@iamctodd: Nevermind! It's right here!

**Comment by alexsoble** [comment]
This was merged in here (#427) and here (#760).
