### ISSUE TITLE
Automate some IE QA

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#348]
For now, our practice is to check the demo site and production site in Internet Explorer whenever we push a change that affects layout. 

Good idea from @kevinrobinson via an in-person chat at Code for Boston #346: after deploy, send a script to go look at the web app in IE, take screenshots, and post in Slack.

**Comment by alexsoble** [comment]
This library may or may not be useful:

https://github.com/watir/watir

https://watir.com/

**Comment by sentientmachine** [comment]
Browserstack will cost $29.99 per month.  It allows you to create a virtual machine in Mac, Linux or Windows and put IE 11 in an automated way.  There is a 100 minute unlimited free trial.

Information about how to use their services is as follows:

https://www.browserstack.com/automate/python
https://www.browserstack.com/automate/ruby
https://www.browserstack.com/automate/java
https://www.browserstack.com/automate/node

**Comment by sentientmachine** [comment]
I got an example to work with Browserstack, pushed a branch:

sentientmachine:add_browserstack
