### ISSUE TITLE
Keep only most recent pre-computed queries

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#362]
The pre-computed query docs that cache information for the school overview page are indexed using a unique key made by concatenating timestamp + student_ids.

The timestamp in the key increments once per day, so the job builds new queries every day and stores the results alongside all past days' queries.

If drop the timestamp from the query key, the PrecomputedQueryDocs will update instead of inserting if the student ID strings are identical. 

This will stop this database table from growing so quickly, without losing any important information.

**Comment by alexsoble** [comment]
In `SchoolsController` the timestamp element of the key plays a useful role by making sure the precomputed doc is fresh (i.e. updated on the same day as the query):

```
    begin
      key = precomputed_student_hashes_key(time_now, authorized_student_ids)
      doc = PrecomputedQueryDoc.find_by_key(key)
      return JSON.parse(doc.json)['student_hashes'] unless doc.nil?
    rescue ActiveRecord::StatementInvalid => err
      logger.error "load_precomputed_student_hashes raised error #{err.inspect}"
    end
```

I wonder if we could use created_at / updated_at to achieve the same thing? Or a separate timestamp field that doesn't affect the key.

**Comment by kevinrobinson** [comment]
Sounds great!  In a similar spirit, we can purge any values here that are more than a week old.

**Comment by alexsoble** [comment]
👍

**Comment by alexsoble** [comment]
This is not a high-priority refactor right now compared to the other refactor issues we have open.
