### ISSUE TITLE
Fix missing Services / Notes in school overview

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#372]
Uri Harel spotted this one. In the School Overview page, it says that zero percent of Healey students have services or notes assigned to them.

We know that's not the case: they're in the database.

```
irb(main):003:0> Service.count
=> 12
irb(main):004:0> EventNote.count
=> 96
```

**Comment by kevinrobinson** [comment]
Addressed by https://github.com/studentinsights/studentinsights/pull/398.
