### ISSUE TITLE
Make "Group progress, since last assessment" graph more prominent

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#373]
This is the graph that everyone looks to and loves. Uri and Jill wanted to know about Healey 3rd grade reading progress — they found it here. Kathleen wanted to know about West Somerville 6th grade progress. Everyone loves this graph because it gives them a clear, powerful summary number about progress that they can't get their hands on quickly and easily right now.

**Comment by kevinrobinson** [comment]
Addressed in https://github.com/studentinsights/studentinsights/pull/395
