### ISSUE TITLE
Add students-in-filter-count for STAR reading / math pages

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#375]
Useful for the user to understand how the filters are working and also very useful for debugging filtering. 
#2.

<img width="532" alt="screen shot 2016-05-31 at 9 56 53 pm" src="https://cloud.githubusercontent.com/assets/1056957/15696015/9c274d92-277a-11e6-8576-d015466ad59b.png">

This is the relevant code that would need to be extracted: https://github.com/studentinsights/studentinsights/blob/master/app/assets/javascripts/school_overview/school_overview_page.js#L212

**Comment by ianaroot** [comment]
there are 40 students in the db, and all of them are end up as authorized_students in the serialized_data_for_star method, and all have a listed most_recent_star_math_percentile, but with no filtering this chart states "Students: 8". does anybody know where it's getting cut down to 8 students?

<img width="1280" alt="screenshot 2016-05-17 21 06 12" src="https://cloud.githubusercontent.com/assets/3813009/15344241/5ee97a98-1c73-11e6-9725-d325ae66901e.png">

**Comment by kevinrobinson** [comment]
@ianaroot hi!  Yeah, this is because not all students will have data points for STAR Math assessments.

This might be helpful: https://github.com/studentinsights/studentinsights/blob/master/app/assets/javascripts/components/star_charts_page.js#L85

**Comment by kevinrobinson** [comment]
@ianaroot @jonchar Also if you have ideas for how to improve how discoverable this is in the code here that'd be awesome, seems like it wasn't as clear to track down as we'd like.

And thanks! 👍

**Comment by ianaroot** [comment]
@kevinrobinson @jonchar this is the data set for this.props.students that we were looking at in my localhost
https://gist.github.com/ianaroot/234b6db963ae28ef13754a1b925ac6a2

**Comment by jonchar** [comment]
To recap from today's debugging session:

Filtering logic bug may be somewhere in `studentsWithRecentAssessments`.

@ianaroot dumped his localhost `this.props.students` from the STAR Math page.

Example anomalously excluded student:

Pocahontas Kenobi has a test within the date range displayed above the line chart. She also has a test before the date range, but does not appear in the visualization's list of students.

@kevinrobinson put the function into a separate file & added a test.

:+1:

**Comment by kevinrobinson** [comment]
From talking with @ianaroot in person, we figured out the "date range" shown in the UI is not the date range that we're filtering by, it's computed after the fact.  So a student with an assessment within the date range shown in the UI is not necessarily included.

This doesn't appear to be a code bug with `studentsWithRecentAssessments`, but a confusing and misleading label in the UI with "date range."  So we should finish verifying that the code works as expected, and then figure out how to improve the labeling in the UI.

**Comment by jonchar** [comment]
Should we close this and open a separate issue to deal with the ambiguity of who's eligible to be counted in the filters?
