### ISSUE TITLE
Clarify "Support staff" summary list in student profile

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#380]
Looking at the Student Profile with Kathleen Seward and the Healey 6th grade team last week, both asked what the list of staff members in the "Support staff" section of the student profile referred to. I assumed it had to do with services / interventions, but I didn't know how to answer them in a precise way. 

Double-checking in the codebase, it looks like "Support staff" combines educators associated with a student's EventNotes, Services, ProgressNotes, Interventions, and StudentNotes (the last three models are deprecated). This is confusing because the educator associated with a student via StudentNote or EventNote is just the SST / MTSS note-taker. That educator may not be actively providing services or supporting the student.

Clarifying the title to say "Staff providing services" and scoping the educators to educators associated to the student via a Service or Intervention will make this easier to understand and more accurate. It will also make it simpler to denormalize educators providing services in #307, because our plan is to denormalize educators providing services while keeping the educators / student notes associations in normal form. 

Part of #307.

**Comment by kevinrobinson** [comment]
this is a great improvement! 👍
