### ISSUE TITLE
Improve experience for answering "how has a student's attendance changed since intervention"

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#406]
From talking with @jsgeiser at Code for Boston.

It'd be nice in SST meetings, to be able to see how an intervention like attendance contract or attendance officer has impacted rate of absences.  The best way to do this now is to look at the student profile page, and then look at the full case history, but there's probably a better way to show this more directly in the section of the profile page focused on absences.

Right now, school staff have been pulling up the student profile page in X2 and scanning the list of absences visually.

An even further improvement, would be optimizing this for the flow of the SST meeting, where students with attendance concerns are discussed first (eg., sorting the overview page by number of absences).  Right now @jsgeiser is doing this and opening each student in a tab to look at them.  cc @alexsoble some overtones here with what we were talking about the other day about places where analytics might be most applicable.

**Comment by johnrobbjr** [comment]
@iamctodd I remember you were showing us a solution to a problem like this, where you had made designs for the graphs that highlighted when interventions were being made (possibly indicated by a vertical line?). Is that graphic somewhere on github? I'll refer to it here if it is. Thanks!

**Comment by kevinrobinson** [comment]
we did a bunch of this!
