### ISSUE TITLE
Behavior & attendance incidents graph: List month's incidents on mouseover.

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#407]
This is a further improvement to #343.

Talking with Jill Geiser today, she mentioned that it would be nice to display the list of a month's incidents when we mouseover on the column for that month.

For discipline incidents, we could also do the jump-to-incident feature (#196) here via tooltip.

**Comment by alexsoble** [comment]
👍 

Thanks for capturing @erose!

**Comment by erose** [comment]
Prototype version of this finished and merged in https://github.com/studentinsights/studentinsights/pull/412.
