### ISSUE TITLE
Add more structure to MTSS notes

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#408]
Today Jill Geiser mentioned that notes for a certain type of meeting (MTSS) play a fundamentally different role than other kinds of notes. They tend to be multi-paragraph and very long.

MTSS notes focus on problem students and will address several issues that a student is facing and which may require intervention. They need to come back and be reviewed at a later meeting. Right now, Jill says, a typical note will look something like:

> Speaks Spanish at home.
> Issue A -- (description of issue).
> Extra info. lorem ipsum dolor sic amet whole paragraphs of information not necessarily related to a given issue lorem ipsum dolor sic amet.
> Issue B -- (description of issue).
> Next steps:
> Person 1 is working on Issue B. Person 2 is working on Issue A.

i.e. the data is pretty structured but isn't being treated as such. Jill says she anticipates it being difficult to parse one of these notes, at a glance, when it comes up for review. In particular she wants to be able to answer the question "What is the status of Issue X? How did the next steps turn out?".

So, perhaps we should structure this data? We could include optionally many **issue, person, description, next step** fields. There also needs to be room for information not connected to a particular issue.

A question I wish I'd thought to ask is: is this a use case for the Services feature? If so, why aren't they being used right now for this?

**Comment by alexsoble** [comment]
Thanks for documenting this @erose!

The way this information might be captured using the tool as-is would be the "Take notes" feature. Under "What are these notes from?, there's an option to select "MTSS Meeting."

One question we can ask: if we normalize and structure the MTSS data (i.e., create an `issues` table, one `Student` has many `issues`), what will the district folks do with it? Would they want to query against it or visualize it or report it out in a particular way?

That's a question we should dig into with Jill. From your notes, it sounds like Jill is wondering if these notes will be difficult to read and review at MTSS meeting. A spitball thought: one way to fix the potential readability issue could be to add some more formatting options, like bigger headers, bullet points, etc. using something like Markdown or a WYSIWYG.

One thing I think we should do for sure before we write code here is go to an MTSS meeting, ask Jill to give the existing Notes / Services tools a whirl as she runs the meeting, and see what issues emerge — they may be the ones Jill mentioned above, they may be totally different ones, or we might find out that the existing app meets 95% of the use case and is a nice-to-have but not a priority issue.

**Comment by erose** [comment]
Hi Alex!

I'm pretty sure Jill was talking about her current use of the Notes feature at the MTSS meeting. (There's been one MTSS meeting so far where they used studentinsights).

So they've had one where they used these tools to create a note for a student; Jill was anticipating issues at the next meeting, when they would review them. I agree we should wait to see how that works before writing any code. If we do need to, yeah, some options for bold/italics/lists could maybe go a long way.

Question: is this the use case for Services?

**Comment by alexsoble** [comment]
Ah, thanks for the clarification!

How are you thinking Services might be used in the MTSS context? Besides the regular function of recording services for student if that comes up in the meeting?

**Comment by erose** [comment]
No, just the regular function. Jill was saying that, during the follow-up meeting, she would look at the previous meeting's notes with a view towards being able to say "Hey, Person 1, how's work on Issue A going?" So it seemed like they would solve that problem.

**Comment by alexsoble** [comment]
Yes! I think using the Services function during MTSS could be a great solution there.
