### ISSUE TITLE
Add validation to services dropdown of educators

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#414]
Now that we've implemented #307, educators can enter any string they like for the providing educator name when recording a new service.

Educator names come in from the Student Information System as `"LastName, FirstName"` and are stored that way in our database. 

Would be nice to validate that that outside service provider names are entered the same way. This will make the data easier to work with if we need to surface or query it down the line. 

This would include client-side validation that `provided_by_educator_name` includes the string `", "`. It would also add some helpful hints to the user if they've entered a name that's doesn't match the format.

**Comment by awalker4** [comment]
I'll see if I can do something for this!
