### ISSUE TITLE
Share Tablesort code between School Overview and Homeroom Roster

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#424]
Several excellent contributors have written code to make the table sorting work better in Student Insights: @dsbader, @brisandbeans, and @ronny2205 in particular! 

In #419 I organized the Tablesort extensions into a single folder under `javascripts`. Some of the extensions are being used only on the School Overview page, others on the Homeroom Roster page. Both pages have tables of students that are very similar and should share this code.

With #422, we now have some duplication: same table sorting feature, two different extensions, being used on the two different pages.

Would be much better to have one extension per table column, and have all extensions shared across both pages.

If I tagged you above (i.e. @dsbader @brisandbeans @ronny2205), this might be a great issue for you to work on! 

Code for Boston tomorrow (Tuesday) night as usual.  :0)

**Comment by kevinrobinson** [comment]
Close https://github.com/studentinsights/studentinsights/pull/604
