### ISSUE TITLE
Cosmetic issues with Math & Reading charts

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#426]
Some charts have the same title twice.
![screen shot 2016-04-25 at 3 48 32 pm](https://cloud.githubusercontent.com/assets/1514487/14796823/55ce2bd4-0afd-11e6-84b4-8e4b7333a515.png)

And the MCAS ELA and STAR Reading charts are a little too big vertically for the box they are in -- the top values get cut off.
![screen shot 2016-04-25 at 3 50 14 pm](https://cloud.githubusercontent.com/assets/1514487/14796846/76103338-0afd-11e6-9ac0-c3c1401d7fdb.png)

**Comment by erose** [comment]
Hey @ianaroot! Last time we met you were doing some work on this. If you plan to in the future (no pressure) then please assign yourself on Github, that way other people can not duplicate work.

**Comment by ianaroot** [comment]
i'm not gonna be in tonight, and haven't made any actual progress on the
issue, but would happily work on it again in the future. should i still
assign myself, or leave it unassigned in case somebody wants to work on it
tonight?

**Comment by QuinnLee** [comment]
I will take a stab at this.

**Comment by QuinnLee** [comment]
Will remove the subtitles in the charts too.
