### ISSUE TITLE
Problem running docker-compose up

### ISSUE THREAD

**Issue by MarcyNash** [studentinsights/studentinsights#430]
1.  Running   **docker-compose up**   the following errors occurred:

    Gem::RemoteFetcher::UnknownHostError: no such name https://rubygems.org/gems/wkhtmltopdf-binary-0.9.9.3.gem)
 
2.  The script continued and then this error occurred:

    An error occurred while installing wkhtmltopdf-binary (0.9.9.3), and Bundler cannot continue.
    Make sure that `gem install wkhtmltopdf-binary -v '0.9.9.3'` succeeds before bundling.
←[31mERROR←[0m: Service 'rails' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 5

3.  Running   **gem install wkhtmltopdf-binary -v '0.9.9.3'**   returned:

    bash: gem: command not found

**Comment by erose** [comment]
Thanks for reporting this Marcy, I've added it to the Docker docs, and hope we see you tomorrow!
