### ISSUE TITLE
Clarify ability to add free-text in educator services dropdown

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#439]
Feedback from Kathleen Seward, principal at the West Somerville Neighborhood School:

When adding a Service for a student, Kathleen wanted to put the name of an outside service provider who works with students at West Somerville, but isn't actually on staff at the school.

She didn't see that person's name in the autocomplete, so assumed she would not be able to add that staff member and put her own name instead. 

The autocomplete can accept free-text input. But since that's not immediately clear to our user, we need to brainstorm and implement design changes that will make it obvious and intuitive.

**Comment by awalker4** [comment]
We could have the first row of the autocomplete just mirror what you're typing. If no other names are a match, you'll only have the one option. Quick example:

![example](https://cloud.githubusercontent.com/assets/3846783/14942294/53901854-0f86-11e6-8311-64f95295b15f.png)

**Comment by alexsoble** [comment]
@awalker4 This looks like a really good idea to me!

**Comment by alexsoble** [comment]
@awalker4 Could be a fun fix to work on during Code for Boston.

**Comment by erose** [comment]
Hey @awalker4! Mirror thing looks pretty cool. If you're working on this, assign yourself.

**Comment by awalker4** [comment]
@erose Awesome, I'll look into it! I don't see any option to assign myself though.

**Comment by erose** [comment]
It's a *drumroll.........* permissions problem! You should see the option now.
