### ISSUE TITLE
Research: Clarify "restricted" note concept

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#450]
Uri:
> There are some notes that are uber restricted (especially 51a and medical info) and get us into student privacy laws/HIPPA.  Possibly a quick fix:  if the word RESTRICTED begins a note, then when teachers see it, it appears to them as "Restricted Note - Please see your administrator for more information."  A little more complex fix - there's a checkbox called Restricted near the note, which embeds a  restricted code into the note field

Alex:
> A) Could you say a little bit about the use case for a Restricted note, as opposed to just some guidelines that we add to the app saying, "Don't write anything in these notes that has to do with XYZ?" In what situation is it important to enter a note but make sure that classroom teachers can't see it, i.e. who will end up looking at the note down the line? 
> B) Could you clarify what the Restricted button would do? Who can see a Restricted note? If Kathleen adds a note, can her AP see it? Can district wide administrators like yourself and Vince see it? Kenya?
> C) Could you add a section to the User Manual clarifying for teachers and principals what kinds of notes should be Restricted? What are the specific criteria? 
> In other words: (A) will help us understand if we should build this or maybe just add guidance about what to enter / not enter, (B) will let me know how to code the permissions if we build the Restricted note feature, and (C) will be important help text to show users about when to use it.

**Comment by kevinrobinson** [comment]
This might involve not doing any software changes, but just noting it as something in the air for this milestone. @alexsoble

**Comment by alexsoble** [comment]
@kevinrobinson Nice, thanks for documenting this! I'll be curious from Uri whether or not building this out is higher priority over expanding to > 2 schools.

**Comment by kevinrobinson** [comment]
Yep!  Just trying to capture all the things out of email, maybe prematurely :)

**Comment by alexsoble** [comment]
No such thing as prematurely! This is great.

**Comment by alexsoble** [comment]
Had a great discussion with Uri and @erose today where we concretized this feature. 

My notes (all quotations from Uri Harel):

## What are restricted notes?

* "Usually comes from the principal"
* "Data point that's sensitive"
* "Certain health data can not be seen by a teacher"
* "51A"
* "Immigration status changing"
* "Some of that data cannot be put in the system"

## What is the use case / rationale?

"Think of the case of a turnover principal. Jill files a 51A or there's a drug situation. You don't want the teacher necessarily to see that. If Jill doesn't put it in, next year a new admin comes in, a new guidance counselor comes in, and they don't have the information."

## Who can see restricted notes?

* PRINCIPAL
* AP
* GUIDANCE COUNSELORS
* DISTRICT-LEVEL ADMIN

## Can classroom teachers enter restricted notes?

* "No, mostly an administrative thing."
* Uri is thinking about in the future developing PD modules for teachers on how to use Student Insights, would include guidance about what to enter / not enter in the Notes section

## How do we explain when to use a Restricted Note?

* "No hard and fast rules . . ."
* Uri can provide some examples in the User Manual, just like he did for regular non-Restricted Notes
