### ISSUE TITLE
Provide user manual directly from product

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#451]
This is subject to change, but we should make the awesome help in the user manual available to users right in the product at the point they're entering data (particularly the notes and services instructions).

**Comment by erose** [comment]
Wow, I never knew this document existed! It's really cool to see all the different things that Notes/Services get used for and to see what the features we're working on look like from the teacher's perspective.

It is cool if I share this with new folks? (Looks like it might have a bit of real student data in it).

**Comment by kevinrobinson** [comment]
@erose It's brand new!  :) Good eyes on that, thanks!  I thought it was fully scrubbed so I removed the document and will re-scrub so we can share with everyone.

**Comment by kevinrobinson** [comment]
This will need to be scrubbed.

**Comment by alexsoble** [comment]
Steps!

+ [ ] Scrub user manual, add to `docs` as Markdown  
+ [ ] Design: "someone sitting in a meeting, not sure what they should" 
+ [ ] Implement

**Comment by erose** [comment]
Design mockup. Here's one thought: (clicking on a question-mark bubble would open a help tooltip).

<img width="1251" alt="screen shot 2016-05-14 at 11 03 19 am" src="https://cloud.githubusercontent.com/assets/1514487/15269123/8179e96a-19c3-11e6-8da5-eb28dd7dcbc3.png">

And another take: adding some friendlier text to the "Which service?". Clicking on it would open the same help tooltip.
<img width="1221" alt="screen shot 2016-05-14 at 11 05 55 am" src="https://cloud.githubusercontent.com/assets/1514487/15269134/e0e11950-19c3-11e6-808c-a0cdd4a3c223.png">

@kbweaver Any design feedback on this?

**Comment by erose** [comment]
Note to self: a similar thing exists on the roster page.
<img width="1079" alt="screen shot 2016-05-15 at 8 01 08 pm" src="https://cloud.githubusercontent.com/assets/1514487/15277618/cec3555c-1ad7-11e6-80f7-975122366d7b.png">

**Comment by alexsoble** [comment]
@erose Nice! I like how the question marks are prominent and purple, draws the eyes. And I like the "help me decide" text a lot too. You can ignore a floaty question mark but you can't ignore "help me decide."
