### ISSUE TITLE
Style change intentional?

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#457]
@alexsoble Before commit https://github.com/studentinsights/studentinsights/commit/9814eda3b6b37d7caa762b08be2e212e0ecb9457, the "Overview" page and graph headers looked like this:

<img width="420" alt="screen shot 2016-05-02 at 1 55 42 pm" src="https://cloud.githubusercontent.com/assets/1514487/14962592/981e50ac-106d-11e6-894e-25d8447cb603.png">

<img width="675" alt="screen shot 2016-05-02 at 1 54 15 pm" src="https://cloud.githubusercontent.com/assets/1514487/14962567/7b95e184-106d-11e6-9d50-38213c61291b.png">

Now they look like this:
<img width="323" alt="screen shot 2016-05-02 at 1 57 45 pm" src="https://cloud.githubusercontent.com/assets/1514487/14962640/ddffd7ee-106d-11e6-9f64-04681a0a9dc0.png">

<img width="503" alt="screen shot 2016-05-02 at 1 58 02 pm" src="https://cloud.githubusercontent.com/assets/1514487/14962649/e8177660-106d-11e6-8adc-f4664bd93830.png">

Was the change intentional?

**Comment by alexsoble** [comment]
@erose Definitely not intentional! I was trying to reorganize the CSS to simplify and organize, without any side-effects beyond the About page. Clearly I didn't succeed with the second part!
