### ISSUE TITLE
Write spec for AcademicSummary.js

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#458]
We're doing some nontrivial computation here so better check that it's correct.

**Comment by BWieber** [comment]
Hi Eli, 

By spec do you mean test? if so I'd like to take a stab at it - maybe we can do it together? I've wanted to start writing JS tests. I have a good background in writing Rails RSpec tests, so hopefully some of those skills translate over :)

**Comment by erose** [comment]
Yep, these are JS tests with a framework called Jasmine. Sure, I'm always down to pair program!

For a reference right now, you can look at `spec/javascripts/student_profile/student_profile_header_spec.js` for a simple example.

**Comment by alexsoble** [comment]
👍 👍 👍

**Comment by BWieber** [comment]
Found out that this is from and old PR 👍
