### ISSUE TITLE
How to run JS tests from the command line?

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#468]
Because of Docker, reloading the web page to run browser-based tests can be slow. It seems like I should be able to run tests on the command line with `rake teaspoon`, but when I do this it just tries to download Selenium from two places and can't.

**Comment by erose** [comment]
Also, I've noticed there's the `coverage` folder, which I'm now curious about. Do I access this from the Teaspoon browser page? How?

**Comment by erose** [comment]
Aha, in the `.travis.yml` I see:

```
  - mkdir travis-phantomjs
  - wget https://studentinsights-public.s3.amazonaws.com/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
```

I'll work on dockerizing this.

**Comment by alexsoble** [comment]
@erose Run JS tests from the command line:

```
teaspoon
```

No need to call `rake`. Maybe the double-downloading of Selenium was because both rake and teaspoon were trying to import dependencies.

**Comment by alexsoble** [comment]
@erose To see the coverage report, open `coverage/index.html` in a browser — gives you a pretty output with the % of lines hit by specs for each file.

This only covers the back-end Ruby/Rails code, not the JS code.

**Comment by erose** [comment]
@alexsoble Running even just `teaspoon` doesn't work for me (and still does the double-downloading thing); I think because I'm running this inside Docker. Y'all who are developing on your local machines must have phantomJS installed already, but our Docker image does not.

So I think this is really a Docker issue. Hence closing this and created #472 .

(Re: coverage, ah, I see. My issue was trying to open `coverage/index.html` through the Rails app).
