### ISSUE TITLE
5/10 Code for Boston Agenda

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#475]
Previous issue: #428

**Whole group**:
Doing the whole-group CFB project update tonight will be @erose.

**Team flow:**
*Start off the night with this stuff.*
* Review [milestones](https://github.com/studentinsights/studentinsights/milestones) - help improve it!
* Quick state-of-the-project, talk about what's going on in school-land.
* Quick sync up, who's working on what, who *doesn't* know what they're working on right now?
* Process thoughts and possible experiments.
  * Assign yourselves to issues on Github that you're working on! (~~Permissions problems?~~ Can be solved by adding people as collaborators. Tie into https://github.com/studentinsights/studentinsights/pull/462?)
  * [dive-in](https://github.com/studentinsights/studentinsights/issues?q=is%3Aopen+is%3Aissue+label%3Adive-in) label -- the problem this is intended to solve is that new people can have a hard time identifying what's a good point for them to jump in at. So the idea is to use it for issues that take 1) not much our-project-specific knowledge and 2) can be worked on in small chunks. I'm thinking bug fixes and design prototyping. Concerns are that it overlaps with [help wanted](https://github.com/studentinsights/studentinsights/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22).

*Coordinating new folks tonight*: @erose.
* See [CONTRIBUTING.md](https://github.com/studentinsights/studentinsights/blob/master/CONTRIBUTING.md).

(hi everyone & @kevinrobinson i changed the issue format a bit, let me know what you think!)

**Comment by erose** [comment]
This is my personal list of things I'd like to get done tonight.

* Get feedback on https://github.com/studentinsights/studentinsights/pull/401 and merge it if no big changes need to be made.
* Get @awalker4's pull request, https://github.com/studentinsights/studentinsights/pull/464, and @kbweaver's pull request, https://github.com/studentinsights/studentinsights/pull/349, merged.
* Discuss importing new data for https://github.com/studentinsights/studentinsights/issues/345 and https://github.com/studentinsights/studentinsights/issues/229. How will it work? What can I do to help?
* Work on spec for `AcademicSummary.js` with @BWieber! (https://github.com/studentinsights/studentinsights/issues/458)
* Discuss #472 and figure out if Dockerizing this is a good thing to do.

*Technical things I would like to understand about the project tonight (and document, if possible):*
* What is the difference between `student.rb` and `student_row.rb`?
* When are we using CSS/SCSS vs. when are we using js styles?

**Comment by awalker4** [comment]
Now that we can assign/tag issues, should we untag 'help wanted' once we've taken something?

**Comment by erose** [comment]
@awalker4: Nah, I think keeping that metadata around is helpful. If you're looking for new issues you can filter by label="help wanted" assignee:none.

**Comment by alexsoble** [comment]
@erose 

> What is the difference between student.rb and student_row.rb?

`student.rb` is the model for a student in the district. It inherits from `ActiveRecord::Base`, so it's backed by information in the database. It has class methods (`self.active`) that concern collections of students, and instance methods (`latest_mcas_mathematics`) that concern a single student.

**Comment by alexsoble** [comment]
@erose

> What is the difference between student.rb and student_row.rb?

`student_row.rb` is a model that represents a row in a CSV export from Somerville's Aspen X2 student information system. Some of those rows will enter Student Insights, and the data in the CSV will be written into the database (see `name_view_attributes`, `demographic_attributes`, `school_attribute`).

But not every student row enters the database. We are importing data into the app one school at a time as we deploy to more schools. So for example, a student row representing a high school student won't become a `Student` object because we're not importing data for high school students.

**Comment by erose** [comment]
@alexsoble Lovely, makes sense. I'll add these as comments.
