### ISSUE TITLE
Clean up SCSS & CSS files.

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#478]
TODO: Include a bunch of stuff in a "shared" scss folder.

What is the purpose of `stylesheets/style.scss`?
Is `_school_year_box.html.erb` used anymore? Looks like it was for the old student profile page? Can we kill it?
What is `no_homerooms.erb`?

New conventions: scope page-specific SCSS's by their page ID, React component SCSS's by their component name camel-cased, and shared we don't know.

**Comment by kevinrobinson** [comment]
@erose `style.scss` is like a manifest pulling in several other files - it's not necessary `per se` and could be merged into `application.scss` or changed however else we think makes sense to simplify.

Also, I think `no_homerooms` was something that could happen in certain cases if the educator didn't have a  homeroom assigned.  My quick read is that the [route](https://github.com/studentinsights/studentinsights/blob/2b8581e75641ea1acb58e9a8c8361e240867ecc4/config/routes.rb#L14) and view aren't used anymore, so seems safe to remove.

**Comment by erose** [comment]
Note to self: right now, we load `application.css` which loads `style.scss` and thereby loads everything.

**Comment by erose** [comment]
@kevinrobinson: Looks like `no_homerooms.erb` is used here:

https://github.com/studentinsights/studentinsights/blob/master/app/controllers/application_controller.rb#L35

So I'm not going to mess with it or its styles.

**Comment by erose** [comment]
@kbweaver: We should also figure out when things will use `window.shared.styles`. It's being declared in [app/assets/javascripts/helpers/theme.js](https://github.com/studentinsights/studentinsights/blob/26d07d578dc2d9735331659b402a3664072185f1/app/assets/javascripts/helpers/theme.js) right now.

A lot of things declare their own `styles` object at the top level, I think.

**Comment by alexsoble** [comment]
@erose `no_homerooms.erb` is a very tiny template for a very tiny edge case in which there are literally no homerooms in the database.

I think this issue is a good one, but let's break it down into smaller / more actionable steps?
