### ISSUE TITLE
MixPanel?

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#481]
The file `app/assets/javascripts/helpers/mixpanel_utils.js` is entirely devoted to Mixpanel, which appears to be tracking & analytics stuff. We also call it in a few other places -- STAR Reading, STAR Math, Roster, School Overview Dashboard.

Are we still using this or do we plan to use it? If so, can we see the tracking stuff? (Or is that PII?)

**Comment by erose** [comment]
@alexsoble You seem to be online right now, do you know the answer?

**Comment by alexsoble** [comment]
@erose Yes, it's used for analytics — are educators actually using the tool? Which educators? Which pages? We should document.

**Comment by erose** [comment]
@alexsoble: Access please!

**Comment by alexsoble** [comment]
@erose Granted! I wonder if it's possible / simple to make some of the analytics data public? Aggregate site visits for example.
