### ISSUE TITLE
5/17 Code for Boston Agenda

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#496]
Previous issue: #475

**Whole group**:
Doing the whole-group CFB project update tonight will be @erose.

**Team flow:**
*Start off the night with this stuff.*
* Review [milestones](https://github.com/studentinsights/studentinsights/milestones) - help improve it!
* Quick sync up, who's working on what, who *doesn't* know what they're working on right now?
* Process thoughts and possible experiments.
  * Assign yourselves to issues on Github that you're working on! (~~Permissions problems?~~ Can be solved by adding people as collaborators. Tie into https://github.com/studentinsights/studentinsights/pull/462?)

*Coordinating new folks tonight*: @erose.
* See [CONTRIBUTING.md](https://github.com/studentinsights/studentinsights/blob/master/CONTRIBUTING.md).

**Comment by erose** [comment]
This is my personal list of things I'd like to get done tonight.

* Get @awalker4's pull request, https://github.com/studentinsights/studentinsights/pull/464 merged. In order to do this we need to work on a spec first.
* Work on spec for `AcademicSummary.js` with @BWieber! (https://github.com/studentinsights/studentinsights/issues/458)
* Get `react-modal` or a similar modal dialog box framework working.

**Comment by kbweaver** [comment]
Note to @kevinrobinson from @erose and myself: we've discovered that the `react-modal` component seems to require `window.react` when our version of React sets `window.React`. We think we can work around this by adding a `window.react = window.React` somewhere after React is included but before the other React libs. Is there a better way to solve this? Also, next time you're here we might want to pick your brain about the Rails asset pipeline :)
