### ISSUE TITLE
Add 'Additional Notes' to Sped Referral

### ISSUE THREAD

**Issue by eudaimonious** [studentinsights/studentinsights#497]
This is part of https://github.com/studentinsights/studentinsights/issues/8.

The Sped Referral pdf has a place holder for additional notes but we're not currently putting these in there. The additional notes are the notes that are handwritten by the teacher. Check out the mockup at https://github.com/studentinsights/studentinsights/pull/165/files

**Comment by BWieber** [comment]
Cool, @eudaimonious @kevinrobinson, I'll take this one up 👍

**Comment by erose** [comment]
@BWieber: Hey, it's been a while so I'm going to unassign you from this. No worries. If you're still working on it, just pop back in and reassign yourself!

**Comment by alexsoble** [comment]
Closing since this is superseded by the new student report.
