### ISSUE TITLE
Group Academic Assessments in SPED Referral pdf

### ISSUE THREAD

**Issue by eudaimonious** [studentinsights/studentinsights#499]
This is part of https://github.com/studentinsights/studentinsights/issues/8.

The Academic Assessments section in the pdf is randomly sorted. Instead, group these test results by test and subject. Keep the ACCESS tests at the top because they're of most importance to our users. That might happen if you're alphabetizing anyway.

**Comment by kevinrobinson** [comment]
Closed by https://github.com/studentinsights/studentinsights/pull/574
