### ISSUE TITLE
Call MixPanel with isDemoSite = True instead of isDemoSite = undefined

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#515]
Right now the `isDemoSite` parameter we pass to Mixpanel can be one of two values: `false` and `undefined`.

<img width="1000" alt="screen shot 2016-05-19 at 2 53 15 pm" src="https://cloud.githubusercontent.com/assets/1514487/15405794/71ba9ad0-1dd1-11e6-82ea-99248c4444db.png">

I assume `undefined` means "true", but obv. it should actually be `true`.

**Comment by alexsoble** [comment]
`undefined` === Staging site I believe

**Comment by erose** [comment]
Okay, so `DEMO_SITE` should be `false` for staging. I can confirm that the config var `DEMO_SITE` is not set on staging right now, so it makes sense that would be undefined.

I assume that `false` means production right now. Maybe let's report `staging`, `production`, `demo` instead of true or false?

I'm wondering if `undefined` really is only staging. [Mixpanel][1] reports 44 unique `undefined`s in the past few days -- where would we be getting all those unique visitors to staging?

[1]: https://mixpanel.com/report/867931/segmentation/#action:segment,arb_event:PAGE_VISIT,bool_op:and,chart_type:pie,from_date:-29,ms_checked:(false:!t,undefined:!t),ms_values:!(false,undefined),segfilter:!((dropdown_tab_index:0,property:(name:isDemoSite,source:properties,type:boolean),selected_property_type:boolean,type:boolean)),segment_type:boolean,to_date:0,type:unique,unit:day

**Comment by alexsoble** [comment]
> I assume that false means production right now. Maybe let's report staging, production, demo instead of true or false?

👍  👍  👍 

> I'm wondering if undefined really is only staging. Mixpanel reports 44 unique undefineds in the past few days -- where would we be getting all those unique visitors to staging?

Hm. I wonder how Mixpanel defines a unique visitor. I also wonder if some of the undefineds could possibly coming from folks running Student Insights on local machines?

**Comment by erose** [comment]
Closed by https://github.com/studentinsights/studentinsights/commit/fd39d8319028f0990fca61dd86d704c96ab13423.
