### ISSUE TITLE
Run `rake db:migrate` on the demo site automatically when new commits are pushed.

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#516]
Could have avoided #495.

**Comment by alexsoble** [comment]
@erose This strategy looks promising: https://github.com/gma/heroku-deploy-rails/blob/master/deploy.sh

**Comment by alexsoble** [comment]
@erose Ooooh . . . except ^ more of a manual strategy than an automatic one. 😕

**Comment by erose** [comment]
You're saying that's intended to be run manually and doesn't work for the automatic deployment we have now?

We could use a [custom buildpack](http://gunpowderlabs.com/blog/automatically-run-migrations-when-deploying-to-heroku/).

**Comment by alexsoble** [comment]
Yes, that's what I mean.

We could! Worth looking at!
