### ISSUE TITLE
When entering an educator name for a Service, autocomplete doesn't work when you've typed a comma.

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#518]
If a valid educator's name is "Principal, Laura" and I start typing that in, the autocomplete window will suggest her name to me **up until** I type the comma. Then it stops.

**Comment by awalker4** [comment]
I was running into this with my autocomplete changes. Is this the only name that seems to be an issue?

**Comment by erose** [comment]
I think it's any name.

**Comment by awalker4** [comment]
Cool, I think I found a suspect. Check [this out](http://api.jqueryui.com/autocomplete/#option-source) (Under the String section). Typing "Teacher" into the box will send off a GET to _/educators/services_dropdown/?term=teacher_. I'm willing to bet that _/educators/services_dropdown/?term=teacher, test_ will cause issues. I'll leave it be for now so maybe someone new can jump in at CFB!

**Comment by alexsoble** [comment]
@awalker4 @erose The `filtered_names` method in `EducatorsController` line 30 may be relevant here.
