### ISSUE TITLE
5/24 Code For Boston Agenda

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#531]
Previous issue: #496

**Whole group**:
Doing the whole-group CFB project update tonight will be ???

**Team flow:**
*Start off the night with this stuff.*
* Review [milestones](https://github.com/studentinsights/studentinsights/milestones) - help improve it!
* Quick sync up, who's working on what, who *doesn't* know what they're working on right now?
* Process thoughts and possible experiments.
  * Assign yourselves to issues on Github that you're working on!
  * Review Apps!

*Coordinating new folks tonight*: @erose.
* See [CONTRIBUTING.md](https://github.com/studentinsights/studentinsights/blob/master/CONTRIBUTING.md).

**Comment by erose** [comment]
My personal agenda for tonight:

  * Get design feedback on https://github.com/studentinsights/studentinsights/pull/427.

**Comment by kbweaver** [comment]
Things I want to get done:

- Work towards getting #528 shipped. Needs code review and another pass at manual testing in IE 11. I plan on doing some light usability testing as well, but I don't think this needs to be a blocker; we can always iterate based on the feedback.
- Submit PRs for additional work to close out #228 (ability to delete notes and a refactor to remove some deprecated routes that will no longer be in use after #528 is deployed).

**Comment by awalker4** [comment]
I'm hoping to knock out a spec for #514 and get that in. Loving the new deployments! Seems like it will make reviewing so much nicer.

**Comment by johnrobbjr** [comment]
Aiming to get mockups for #88 completed tonight
