### ISSUE TITLE
Allow school administrators to designate some notes as 'Restricted'.

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#532]
We've concretized the feature in https://github.com/studentinsights/studentinsights/issues/450, so now we should move on to implementing it, I think? Here's Alex's summary of the new feature.

## What are restricted notes?

* "Usually comes from the principal"
* "Data point that's sensitive"
* "Certain health data can not be seen by a teacher"
* "51A"
* "Immigration status changing"
* "Some of that data cannot be put in the system"

## What is the use case / rationale?

"Think of the case of a turnover principal. Jill files a 51A or there's a drug situation. You don't want the teacher necessarily to see that. If Jill doesn't put it in, next year a new admin comes in, a new guidance counselor comes in, and they don't have the information."

## Who can see restricted notes?

* PRINCIPAL
* AP
* GUIDANCE COUNSELORS
* DISTRICT-LEVEL ADMIN

## Can classroom teachers enter restricted notes?

* "No, mostly an administrative thing."
* Uri is thinking about in the future developing PD modules for teachers on how to use Student Insights, would include guidance about what to enter / not enter in the Notes section

## How do we explain when to use a Restricted Note?

* "No hard and fast rules . . ."
* Uri can provide some examples in the User Manual, just like he did for regular non-Restricted Notes

**Comment by johnrobbjr** [comment]
Some sketches for a potential v2 for later reference

![img_20160531_202441](https://cloud.githubusercontent.com/assets/9868315/15694703/17fd2bd8-276e-11e6-9748-099d6f2064a1.jpg)
