### ISSUE TITLE
Landing Page Simplifying

### ISSUE THREAD

**Issue by pappacorleone** [studentinsights/studentinsights#538]
Landing page could use less text and should emphasize login (the key call to action). 

@pappacorleone submitting alternate wireframes

**Comment by pappacorleone** [comment]
Created wireframe for alternate landing page emphasizing call to action.

**Comment by alexsoble** [comment]
@pappacorleone Agreed that emphasizing login is a strong move!

**Comment by erose** [comment]
Hi, you should be able to assign yourself to this once you accept my GitHub invitation to be a "collaborator".

**Comment by alexsoble** [comment]
This issue seems dormant besides the wireframe. I think a PR putting more emphasis on the login fields would be great, but since this isn't an active priority or being developed I'm closing it to reduce issue clutter.
