### ISSUE TITLE
Make the User Manual service categories match the actual buttons

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#543]
Right now they don't line up 100%. 

Buttons:

+ Counseling, in-house
+ Counseling, outside
+ Reading intervention
+ Attendance Officer
+ Attendance Contract
+ Behavior Contract

User manual categories:

+ Reading Teacher
+ Behavior/Attendance Contract
+ Attendance Officer
+ Counseling

**Comment by erose** [comment]
Yeah these should align. I can guess what some of the terms mean, but don't know enough to write a description/don't know what's important to emphasize. I don't know:
  * Attendance Officer
  * Counseling outside vs inside

Did Uri come up with the button names? If so, seems like I can just ask him what the help text should be by email today or by phone later on this week.

**Comment by alexsoble** [comment]
Let me take a pass with a PR that tweaks the user manual so that it matches these a little more closely, we can run it by Uri when we talk.

**Comment by alexsoble** [comment]
Closed via #557.
