### ISSUE TITLE
Code For Boston Agenda 5/31

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#547]
**Whole group**:
Doing the whole-group CFB project update tonight will probably be me. If you want to do it, though, go ahead! Less scary than it looks.

**Team flow:**
*Start off the night with this stuff.*
* Quick sync up, who's working on what, who *doesn't* know what they're working on right now?
* Process thoughts and possible experiments.
  * Assign yourselves to issues on Github that you're working on!
  * `reach` -- new issue label. (also known as "moonshots"). These are things that aren't top priority right now, but will have big user impact. As opposed to fixing bugs, these types of issues will 1) take longer, 2) carry more ownership, 3) be self-contained, i.e. be easier to jump into because they won't require a lot of context.
  * Who doesn't have collaborator permissions?

Working on a `reach` is a good way to have a really visible impact -- you can point to it later and be like, "I did that!". It's also a good way to contribute even if you can't be here every week. (Almost all of the work I get done for CFB is at home).

Lots of people have been working on `reach` things already (for just a few examples, Margaret with SPED packet, Kevin with editing/deleting notes, Eric with BrowserStack screenshots) -- this is just to formalize the idea so newer folks can get into one of these easily.

Here are all the `reach` issues: https://github.com/studentinsights/studentinsights/issues?q=is%3Aopen+is%3Aissue+label%3Areach

*Coordinating new folks tonight*: @erose.

**Comment by erose** [comment]
Things I personally would like to get done tonight:
  * Think about https://github.com/studentinsights/studentinsights/pull/546 with @kbweaver.
  * Figure out what @jonchar learned re: https://github.com/studentinsights/studentinsights/pull/545, get it merged if possible?
  * Work on tests for https://github.com/studentinsights/studentinsights/pull/514 with @awalker4, get it merged. (Hi Austin! If you can make it, that is -- no pressure. We could even do that remote pairing thing, just let me know).
  * Merge https://github.com/studentinsights/studentinsights/pull/507 if @eudaimonious is around.

Technical questions I'd like answered:
  * how is current_educator set?
  * when is authorize! called? (e.g. in `event_note.rb`)

**Comment by jonchar** [comment]
I'd like to get a better understanding of the filtering referenced in #375 so we can document it and easily leverage it for the experimental STAR reading/math pages.

**Comment by alexsoble** [comment]
@erose `current_educator` is set by Devise: https://github.com/plataformatec/devise#controller-filters-and-helpers

It's the same thing as `current_user` in the Devise docs.

**Comment by alexsoble** [comment]
@erose Can you say more about your `authorize!` question? Not sure I'm understanding what you're asking.

**Comment by alexsoble** [comment]
@jonchar Do you mean that you want to dive into the code behind the filtering feature at CFB tonight, or you want a better explanation of the filtering feature in #375?

**Comment by jonchar** [comment]
@alexsoble I'd like to dive into and understand the filtering code.

**Comment by alexsoble** [comment]
@jonchar 👍  👍

**Comment by kbweaver** [comment]
- Review PR #536 and maybe merge.
- Make a pull request to remove some deprecated code that's no longer needed now that #528 is deployed.
- Talk with @erose about #546.
