### ISSUE TITLE
Implement bar-chart sparklines for behavior data.

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#548]
The "at-a-glance" section of the behavior data column uses line graph sparklines, but the charts below are bar graphs. We switched them, and now we'd like to switch the sparklines over as well.

I think the original sparklines are implemented in D3. Poke me if you're interested in working on this!

**Comment by iamctodd** [comment]
Here: http://omnipotent.net/jquery.sparkline/#s-about

**Comment by erose** [comment]
Duplicated in https://github.com/studentinsights/studentinsights/issues/593.
