### ISSUE TITLE
Implement style changes to tables to make them consistent

### ISSUE THREAD

**Issue by johnrobbjr** [studentinsights/studentinsights#553]
In issue #88, I created a consistent design of tables between the classroom roster table and the overview page table. These are style changes that are outlined in the image below:

![issue-88_02](https://cloud.githubusercontent.com/assets/9868315/15695380/8c486d26-2774-11e6-95f3-e187d0af421a.png)

**Comment by kevinrobinson** [comment]
we did a bunch of this!
