### ISSUE TITLE
Set null: false for authorization attributes on Educator

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#561]
These ones should be null: false'd:

+ schoolwide_access
+ grade_level_access
+ restricted_to_sped_students
+ restricted_to_english_language_learners
+ can_view_restricted_notes

Without database-level validation against `nil`, we effectively have a three-boolean system for authorization (`true`, `false`, `nil`) which is worse than a regular old two-boolean system.

**Comment by CBillings92** [comment]
Looking for my first issue to get my feet wet on the project and this seems like it could be a good straight forward issue unless I'm completely misreading it. 

Could you elaborate on null: false'd ? Not familiar with the verbiage!

**Comment by alexsoble** [comment]
Hi @CBillings92! Thank you for joining the project and looking for an area to contribute! Unfortunately I don't think this issue is a good candidate for you to work on because this commit is going to close it: https://github.com/studentinsights/studentinsights/commit/56e9fde685806f7b8d4986e102040a8eddd5d1dd. 

Take a look at the issues labeled `help wanted`, we've got 32 open at the moment. Browse for one that strike you as a good fit with your skills and interests and feel free to ask questions if the issue documentation is spare. 

`null: false` is how Rails expresses non-null constraints at the database level, meaning that if a record has no data for a column that is `null: false` it can't be saved.

**Comment by CBillings92** [comment]
Perfect. Thanks for the thoughtful response and advice!

**Comment by alexsoble** [comment]
@CBillings92 😊
