### ISSUE TITLE
Document engineering decisions around how we create pages.

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#579]
For example, I didn't understand that there's one `main.js` per page until recently.

**Comment by kevinrobinson** [comment]
@erose 👍 This is awesome to be thinking of!  One thing to consider is the balance between writing things down as a way to remember things and help other folks on the project learn, and capturing the entirety of context and decisions that are involved for the project.  It'll be awesome to do this in a way that supports the kind of learning we want to encourage on the project.  Let me know if there's anything particular I can help with!
