### ISSUE TITLE
Design - Create User Interview Guide

### ISSUE THREAD

**Issue by johnrobbjr** [studentinsights/studentinsights#585]
Create a document to guide user interviews to answer any questions we may have.

Questions should aim to extract user behaviors while using the application, and eventually drive prioritization of issues and design decisions down the road.

**Comment by iamctodd** [comment]
I'm happy to give this a review once you've got a first version

**Comment by alexsoble** [comment]
Was this issue closed by #586 @johnrobbjr?

**Comment by johnrobbjr** [comment]
@alexsoble not yet, that pull request was for adding the document, but the full interview guide has not been written yet. I hope to get to it soon once life gets a bit less hectic!

**Comment by alexsoble** [comment]
This issue seems dormant, closing.
