### ISSUE TITLE
Gemfile's Ruby version out of sync

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#59]
The Gemfile has `ruby '2.2.3'` but when I went through the setup instructions for Docker development on OS X, I ended up with a ruby version of `2.2.4`.

This means that the setup instructions don't work as written (you run into an error when running `docker-compose up`). Once you change the version to the correct one it works fine. (But I didn't want to commit this change).

We're pulling from [this](https://github.com/docker-library/ruby/blob/9b1f77c11d663930f4175c683b1c5f268d4d8191/2.2/Dockerfile) Dockerfile, `ruby 2:2`, which has `2.2.4`, but I guess it was `2.2.3` when that Gemfile was authored.

The easy fix would be upgrading to `2.2.4` -- would this work, or be convenient?

**Comment by kevinrobinson** [comment]
@erose Thanks for bringing this up, it'll be good to improve this friction. :)

You're spot on about this working previously, and then at some point aftereward the Docker Hub Ruby image, which is only tagged at 2.2, published 2.2.4.  I updated all the Ruby dependencies to 2.3.0 in this PR, which also has steps for getting things working locally:https://github.com/studentinsights/studentinsights/pull/60

**Comment by kevinrobinson** [comment]
@erose Closing this, since https://github.com/studentinsights/studentinsights/pull/60 should address it, and please re-open if there's still issues.
