### ISSUE TITLE
Why do we use codes for note & service types?

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#590]
We own these codes, right? Why don't we just pass the string names down in (e.g.) the event note object, instead of having to thread the index through everything?

**Comment by alexsoble** [comment]
@erose By codes do you mean the Rails-assigned IDs?

**Comment by erose** [comment]
Nah, I mean (e.g. for notes) `300` mapping to "MTSS Meeting", `301` mapping to "SST Meeting", etc.

I bet in a moment I'm going to go "ohhhh, of course." Is it because they might change on the server side? Are we getting these from the server or are they constants within the JS?

**Comment by erose** [comment]
@alexsoble: ???

**Comment by kevinrobinson** [comment]
@erose Good question!  The id field is used as a stable unique key for referring to service types and note types.  The name or text is user-facing, so by keeping that separate we can change the text as much as we like and key references to that record are unaffected.

For render interfaces in the [UI code](https://github.com/studentinsights/studentinsights/blob/f2ca10cf1a5a12e055ace9a2d87c2fcb446330d3/app/assets/javascripts/student_profile/take_notes.js#L104), we want to place different services or notes in a particular order, and use the id to do that.  And ultimately the UI code needs to communicate back to the server about "here's the kind of note the user entered" and it uses the key to do that.

**Comment by alexsoble** [comment]
Thanks for answering this @kevinrobinson and sorry for leaving you hanging @erose!
