### ISSUE TITLE
Implement bar chart sparklines for Attendance & Behavior column

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#593]
In the Attendance & Behavior column, we currently use line-graph sparklines:
<img width="244" alt="screen shot 2016-06-27 at 3 00 16 pm" src="https://cloud.githubusercontent.com/assets/1514487/16392032/dd337358-3c77-11e6-817c-5b448014454a.png">

But line graphs don't really make sense for the data, which is cumulative per year. We already changed the main graphs to bar charts for this reason, but now we need to change the sparklines in the columns to bar charts as well.

Seems like they should look like the other sparklines, which are implemented in D3. But we could think about other options too.

**Comment by alexsoble** [comment]
This sounds great @erose!

One thought here: for the sparklines, I think some sense of scale for the x-axis will be important. Do the bar chart trends represent the last 6 months, or school year, or the student's entire career ... ? Without some labeling or context on the x-axis it would be hard for the user to know.

**Comment by erose** [comment]
@alexsoble: I agree. Same situation as for the existing line chart sparklines, right? So maybe we should look at adding context to those as well.

<img width="224" alt="screen shot 2016-06-28 at 3 01 10 pm" src="https://cloud.githubusercontent.com/assets/1514487/16428721/268e2880-3d41-11e6-9dba-70b422541552.png">
