### ISSUE TITLE
Grade sort on School Overview page plays badly with "KF".

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#598]
This isn't visible on demo because AFAIK we only have grades 3-5, but the string value "KF" appears in West Somerville Neighborhood School's data, and it:
- sorts after `8` when it should be before `1`.
- somehow creates more than two states to the Grade sort column, so I can click it three times and get three different outputs.

**Comment by alexsoble** [comment]
Fixed this during the Student Table JSX rewrite to cut out Tablesort.
