### ISSUE TITLE
Investigate educators missing from X2 export CSV

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#6]

**Comment by alexsoble** [comment]
Searched through staff table data dumps for the missing educators.

Turned out they both have `null` values for `STF_ID_LOCAL`, i.e. the district-assigned staff ID.

Will reach out to our district partners on Monday (school's out today), want to find out:

+ what the correct local IDs are for the missing educators
+ if this is a known issue
+ if missing local IDs could cause problems, or if `null` staff local IDs are harmless in X2

**Comment by alexsoble** [comment]
Kenya Avant-Ransome and Mary Skipper are also missing local ID values in the data dump.

**Comment by alexsoble** [comment]
Not quite closed yet! 

But almost there.

Reached out to John Breslin with the missing IDs issue, he is going to correct those data points in X2. 

There are about 300 staff entries in X2 with missing local IDs. John said this is because of an issue with the data links between the HR system and X2. They are working on fixing that issue but for now when I run into a missing local ID for an educator who needs to use Student Insights I'll contact John and he can fix.

**Comment by kevinrobinson** [comment]
@alexsoble Nice progress!  Do you think these findings are worth adding to a user-manual kind of doc?

**Comment by alexsoble** [comment]
@kevinrobinson Yes, in particular I think this would go into an "On-boarding New Schools" checklist... We will want to scan for this kind of data issue before we onboard each new school.

**Comment by alexsoble** [comment]
@kevinrobinson Pulled this out into #278.

**Comment by alexsoble** [comment]
Updated missing educator IDs in the console instead of with a migration so as not to expose district assigned IDs in a public repo.
