### ISSUE TITLE
Demo site is broken.

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#625]
Upon logging in I'm taken to https://somerville-teacher-tool-demo.herokuapp.com/schools/1, which is a 404 page.

<img width="811" alt="screen shot 2016-08-21 at 1 58 59 pm" src="https://cloud.githubusercontent.com/assets/1514487/17838932/6da04ab0-67a7-11e6-99d7-32abe995ae15.png">

**Comment by alexsoble** [comment]
First issue was that `rake db:migrate` hadn't been run against the demo site. 

Now running into a redirect loop issue.

**Comment by alexsoble** [comment]
Pushed, migrated, re-seeded, demo site looking good.
