### ISSUE TITLE
Standardize how we handle dates in profile_details.js

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#632]
Dates are being handled in several different ways within the `ProfileDetails` class. They are sent from the server as Rails dates w/ timezones, and as [Y, M, D] arrays. They are being parsed as native JS dates with `new Date` and with Moment.js in the same file. 

Would be helpful to reduce this complexity as much as possible, starting with the client-side parsing, so that we can debug date problems with more consistency.

**Comment by Jngai** [comment]
@alexsoble FYI I dealt with a lot of ruby date/timezones and js dates in my last project so this is up my alley after service if its a priority.

**Comment by alexsoble** [comment]
Talked about this with @Jngai in our video call — this area of the code isn't really breaking or surfacing bugs, so let's close this and focus our energy on areas where we've seen bugs or issues, like the data import process and the Services area.
