### ISSUE TITLE
Add explicit Show More button to Admin Dashboard

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#644]
You can click on any educator row in the Admin Dashboard to see its Show Page. Adding an explicit link that says "Show More" may make this easier to navigate. @kevinrobinson if I recall correctly, on our call the other week the click-row-to-show mechanism wasn't obvious.

**Comment by kevinrobinson** [comment]
Yeah UX-wise it might be worth merging show+edit into a single edit page, but I haven't looked at the gem to know if that's simple or a good idea in the code.
