### ISSUE TITLE
All absences from students in production are being grouped into the current day.

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#656]
This is in the client, not the data. I think the format of `created_at` changed? Investigating...

**Comment by kevinrobinson** [comment]
@erose This looks good to me, following the links in the Rollbar dashboard: https://rollbar.com/somerville-teacher-tool/somerville-teacher-tool/  Can you confirm when you get a chance?

**Comment by erose** [comment]
Looks good!
