### ISSUE TITLE
Inconsistent absence, tardies, discipline data between overview and profile

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#673]
This affects principals and district-level admin.  It's a JS bug and not a data quality issue.  It will probably roll over in a few days when the next "school year" starts.

Possibly related or separate, the number at the top of the profile page is inaccurate for these as well.

**Comment by kevinrobinson** [comment]
cc @erose

**Comment by alexsoble** [comment]
I poked around the site to try to see if this was still an issue. Because it's the summer and no one is absent or tardy, all students have "0" absences and tardies right now so it's a bit hard to tell. Closing for now.
