### ISSUE TITLE
Answer Uri's question about attendance events summary

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#686]
> Also, wondering if you could look into one potential bug….when we bring up a student, it’s showing 3 Absences for the School Year even though he hasn’t had any so far.  I think it’s counting starting in June from last year.  Can you take a look?

# More context 

+ The Attendance column up top is saying "3" for absences
+ `StudentProfilePage#renderAttendanceColumn`
+ This might not but be a "bug" per se but rather highlights a potential design or labeling improvement

**Comment by alexsoble** [comment]
Looking at these lines in `renderAttendanceEventsSummary`:

```
var cumulativeQuads = QuadConverter.cumulativeByMonthFromEvents(attendanceEvents);
var value = (cumulativeQuads.length > 0) ? _.last(cumulativeQuads)[3] : 0;
```

Looks like this is displaying the total number of attendance events in the most recent month with non-zero attendance events.

So for example, this viz —

![screen shot 2016-09-14 at 4 04 50 pm](https://cloud.githubusercontent.com/assets/3209501/18529999/fdb3c05a-7a94-11e6-86fa-7a73e445d59f.png)

— means that the student had 3 absences in the last month with non-zero absences (which in this case is May), whereas Uri is expecting it to say something like "zero" since it's a new school year and there haven't been any absences yet.

I think changing the UI to match Uri's intuition makes the most sense. Any feedback/input/design ideas @erose @kevinrobinson?

**Comment by alexsoble** [comment]
My suggestions:

— Change the code so that it looks up the # of attendance events for the current month, regardless of whether that value is zero or not

— Add labels: "Discipline this month: 0, Absences this month: 0, Tardies this month: 0"

**Comment by kevinrobinson** [comment]
@alexsoble 👍 those all sound like great improvements to me!  Also this is related to https://github.com/studentinsights/studentinsights/issues/673, but I think that issue appears to have resolved itself via the passage of time.

**Comment by alexsoble** [comment]
@kevinrobinson Hmmmm yes! I think "inconsistency" will be easier to identify and fix as we add more labels that help pin down what each number represents.
