### ISSUE TITLE
"Parent Logs" section for notes that track conversations with parents

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#692]
Classroom teacher suggestion: Add a "parent logs" section for notes that track conversations with parents. This would be parallel to the "Notes" and "Services" section, but specifically focused on parent interactions.

**Comment by kevinrobinson** [comment]
This feature is already there, right?  Good learning from that user that they didn't learn or discover it!

<img width="499" alt="screen shot 2016-09-23 at 7 58 17 am" src="https://cloud.githubusercontent.com/assets/1056957/18784941/836d0d30-8163-11e6-9967-b15d6d96e952.png">

<img width="452" alt="screen shot 2016-09-23 at 7 58 26 am" src="https://cloud.githubusercontent.com/assets/1056957/18784943/8776180e-8163-11e6-8bb5-c22961455e5a.png">

**Comment by alexsoble** [comment]
@kevinrobinson Omgggggggggg you're right!
