### ISSUE TITLE
Add student address and home phone number to profile page

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#693]
Classroom teacher suggestion: this would make it easier to get in touch with parents.

**Comment by Jngai** [comment]
I am interested in this issue. Mind if I take it?

**Comment by jhilde** [comment]
Glad you're interested Judy! That data currently exists in X2 but not in the Student Insight's database. So it will require coordination with the district's IT admin. 

Feels like we should bundle other data to expose from X2. 

Might be good to start from a UX perspective to figure out where additional data elements should go

**Comment by jhilde** [comment]
@Jngai I misspoke, student address is currently part of the X2 export, telephone number is not.

**Comment by Jngai** [comment]
Great! I think I know the solution for this. I will work on this later.

**Comment by Jngai** [comment]
<img width="1264" alt="screen shot 2017-08-15 at 1 52 37 pm" src="https://user-images.githubusercontent.com/1547934/29329743-df49d766-81c4-11e7-994c-4b1ca8c0d161.png">
The address is spilling over a bit. Any inputs?

**Comment by alexsoble** [comment]
Closed by @Jngai in #964!
