### ISSUE TITLE
Ability to select an end date for services

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#695]
Classroom teacher mentioned that this would be useful when back-filling services data.

**Comment by awalker4** [comment]
I noticed that when you discontinue a service it shows duration down to the minute. Does that mean that we could satisfy the back-fill use case with a duration field? If we just add an end date we wouldn't get any hour/minute data.

**Comment by alexsoble** [comment]
Closed by @Jngai in #1105!
