### ISSUE TITLE
Make student profile responsive to grade level

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#700]
When reading teacher logs into 2nd grader's profile she says, "Oh there's no math or reading" — because there's no MCAS / STAR math or reading results for 2nd graders. 

2nd grader's profile should highlight DIBELS and maybe ACCESS, no need for STAR/MCAS sections.

**Comment by jhilde** [comment]
Responsiveness to high school students will be added in #1078. Figured I'd add that context to this issue.

**Comment by kevinrobinson** [comment]
This varies a bit now in a bunch of different ways, across districts too.
