### ISSUE TITLE
Include descriptions about what the DIBELS performance levels mean

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#701]
Include descriptions about what the DIBELS performance levels mean. (i.e. what does "STRATEGIC" mean?) Include raw integer scores for DIBELS along with performance levels. That could let educators see DIBELS change over time.

**Comment by pauledwardmitchell** [comment]
It looks like how the raw integer scores for DIBELS correspond to the three intervention categories changes as students progress through the grades... (page 4 [here](https://dibels.uoregon.edu/docs/DIBELSNextFormerBenchmarkGoals.pdf)) ... not sure how to reflect this in this feature @alexsoble

**Comment by kevinrobinson** [comment]
this is stale now, but for individual assessments this is visible first to project leads as thresholds, and part of work on the reader profile
