### ISSUE TITLE
Investigate & fix Jill bug report about Excel download

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#711]

**Comment by alexsoble** [comment]
From Uri:

> Hi Alex – Just got an email from Kenya and another admin that the Download for Excel button in the dashboard just brings up an empty window….just tried it.  Wondering if there’s a broken link.

**Comment by alexsoble** [comment]
I'm thinking this is a Chrome / IE feature compatibility issue, because Excel download is working fine for me in Chrome but seems to throw an error when I try to simulate it in IE using Browserstack.

**Comment by alexsoble** [comment]
# Currently reading 

+ http://stackoverflow.com/questions/16078544/export-to-csv-using-jquery-and-html

+ http://stackoverflow.com/questions/7405345/data-uri-scheme-and-internet-explorer-9-errors

**Comment by kevinrobinson** [comment]
Addressed by https://github.com/studentinsights/studentinsights/pull/713 and follow ons.
