### ISSUE TITLE
Design and UX feedback

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#79]
From Code for Boston!

Hi there, my name is Mohan Wang and there are some suggestions for this website. 
First of all, when I tried to back to the home page, the only way is click go back button. So I suggest add a navigation bar on the top of every page, and there are Home, Profile, or some other kinds of category in this bar. In this way, users can go to any page they want very quickly.
Secondly, for the search bar. Users can type in the students' name in this bar, but for other kind of thing it does not work. For example, I tried to type in Level 7, it could not show anything for me. I would like to use the search bar to search anything I want, that would be very helpful I think.
Third, for the student's profile page. Each box about the information which "2015-2016" and "2014-2015",  all of those show me too much detail, I mean they look very long in a page. I suggest you could add an up or down arrows in the blue area, so users can open or close each box very easily. In this way, designers can make the page very clear.
Fourth, in the room page. When I tried to move my mouse on the student's name and the information after the name, it jumped to different pages, and made me very confused. I suggest add a small tip when users move their on the different area in this page. For example, when users move mouse on student's name, the tip shows "go to Profile", or when users move the mouse on the information after the name, the tip shows "go to Home". And also I have a second solution, which is the color of name and the information after the name is different, so users could know they maybe have different function.
All in all, in my opinion, I think the good user experience is never let users guess what is the function for a bar/button or where is the button I am looking for. And also make the page very clear. I like this website's visual design, the color is friendly. Hopefully my suggestions could help you improve the website.
BTW, if you have more questions or anything, I would like to hear the feedback from you :) 

^ this was all from Mohan, thanks so much for the input :) - @kevinrobin

**Comment by kevinrobinson** [comment]
Hi there,
This is Mohan again :) Here are some suggestions for the charts.
First, most hints of the "Student scores, all the time" are very clear. The only issue I found out is there is no number on the coordinate axis. For example, the axis Y should have 0-100, so users can see the results very fast. And in this way, the number on the axis Y can help users understand the meaning about the number "-67 to 11". And also the same issue in the "Student progress, since last assessment".
Second, when I took a look on this chart, I'm not sure which line is the median change line. I confused about the black line and the blue line, I don't know the meaning of both of them. I guessed maybe one of them is zero line. I suggest note the "0" under the black line, so that will be very clear.
Third, for the "Group quartiles each period, all-time" chart, OMG, this is very beautiful, however, forgive me please, the first time when I look at this chart, I totally lost. I have to let Kevin give me some hints so I could guess what is the meaning of the lines. I suggest you could note some tips for the chart, for example, the name for axis Y and axis X. And also the tip box under the chart, such as the high line meaning, the middle line meaning, the green points meaning, etc. So users can understand the chart very quickly.
Thanks :)

**Comment by alexsoble** [comment]
Thanks for this detailed feedback Mohan!

**Comment by kevinrobinson** [comment]
Mohan, this is great thanks!  I added a note to your feedback on the charts to https://github.com/studentinsights/studentinsights/issues/2, which we'll probably focus on more next month.

Here's thoughts on your other points:
- for navigation, @erose awesomely made the logo clickable here: https://github.com/studentinsights/studentinsights/pull/81.  Additional navigation might be useful, but hasn't come up at all in user testing so we'll wait to learn more for now.
- the search bar improvements are great, but probably out of scope for now.  we're really focused only on the use case of "I know a student's name and I want to jump directly to their profile."  I fixed the bug related to typing full names that came up last night in https://github.com/studentinsights/studentinsights/pull/85
- for the long vertical column of information, we're working to improve that in the profile v2 page, tracked here: https://github.com/studentinsights/studentinsights/issues/5
- Making the mouse interactions consistent between the overview and classroom roster pages is a great idea, I added a separate issue to do that here: https://github.com/studentinsights/studentinsights/issues/88

Since you're not on Github, I'll ping you with an update over email, and will close out this larger feedback issue.  Thanks again for your feedback, and please let us know if you have any other thoughts!
