### ISSUE TITLE
Fix MCAS "ELA" vs. "English Language Arts"

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#82]

**Comment by kevinrobinson** [comment]
@alexsoble This is what I noticed first looking in chat, assuming it was a separate issue:

```
def assessments_by_school_year(assessment_id)
  sas = StudentAssessment.select {|sa| sa.assessment_id == assessment_id }
  sas.group_by(&:school_year_id).map {|key, values| { year_name: SchoolYear.find(key).name, count: values.size } }.sort_by {|h| h[:year_name] }
end

MCAS_MATH = 19
MCAS_ELA = 5
pp assessments_by_school_year(MCAS_ELA);nil
pp assessments_by_school_year(MCAS_MATH);nil
```

shows a discrepancy that I now figure is related to this issue.

**Comment by alexsoble** [comment]
@kevinrobinson Yup. Fixing now!

**Comment by alexsoble** [comment]
1. Merged in #97.
2. Ran import path again to pull in ELA results correctly. 
3. On the school overview dashboard, number of Healey students without MCAS ELA dropped by 11%. So around 11% of students had new MCAS results that weren't being pulled in from X2 to Student Insights because of this issue.
4. @kevinrobinson, is the discrepancy you ran into resolved now in production?

**Comment by kevinrobinson** [comment]
@alexsoble yep, looks great, nice fix!

**Comment by kevinrobinson** [comment]
@alexsoble Also, I rebuilt the demo DB as well a few minutes ago.  This is closed out now, yar?

**Comment by alexsoble** [comment]
Yes!
