### ISSUE TITLE
Generate fake attendance events within correct school year

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#835]
Currently the generation of fake student data includes generation of attendance events (absences and tardies). These events are generated randomly across 5 years (from 2010) but the records are created with the current school year as the school year for ALL attendance events regardless of date.

_demo_data/fake_student.rb_

**Comment by kevinrobinson** [comment]
@jhilde Good catch!  👍

Feel free to ping me or @alexsoble if you want to pair on fixing this up, or a hand reviewing anything.

**Comment by Jngai** [comment]
I can dive into this next.

**Comment by alexsoble** [comment]
This issue isn't relevant any more because we dropped the `school_years` and `student_school_years` tables in June: #938.
