### ISSUE TITLE
Student Report UI thoughts/suggestions

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#864]
This is a parking lot for ideas and suggestions about the Student Report PDF for now, will break this out in more specific & actionable ideas once we start hearing back from Uri & Jill...

+ Deprecated Intervention records aren't included in the report. Not sure if we should include them, or just finally migrate that model once and for all (#385).
+ Might be nice to separate out the different assessment groupings visually a bit more -- more spacing or some kind of `<hr>` element? Different types of assessments appear very close together on the page
+ At some point we'll want to change the BETA Sped Report button to BETA Student Report or just Student Report . . . 

@kevinrobinson @jhilde feel free to add here as ideas come to mind, then we'll synthesize with Jill & Uri!

**Comment by jhilde** [comment]
Going to close this out.

**Comment by alexsoble** [comment]
👍
