### ISSUE TITLE
Design - Make interactions and visual design consistent between overview table and classroom roster table

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#88]
These are slightly different.  I don't have a strong opinion on the design choice here, but these should converge.  My only initial thought is that we should use real HTML links where possible.

Thanks Mohan for the input here from https://github.com/studentinsights/studentinsights/issues/79#issue-134148692!

#### [Overview page table](https://somerville-teacher-tool-demo.herokuapp.com/schools/1)
<img width="1261" alt="screen shot 2016-03-02 at 6 03 56 pm" src="https://cloud.githubusercontent.com/assets/1056957/13478875/3969c862-e0a1-11e5-8675-800ad4f183d8.png">

#### [Classroom roster table](https://somerville-teacher-tool-demo.herokuapp.com/homerooms/1)
<img width="1006" alt="screen shot 2016-03-02 at 6 04 17 pm" src="https://cloud.githubusercontent.com/assets/1056957/13478879/41765fb6-e0a1-11e5-9e48-1a09487cf996.png">

**Comment by kevinrobinson** [comment]
Adding some notes from @johnrobbjr and Kemal's great feedback [here](
https://docs.google.com/presentation/d/1t7bXVaFCDU_1d0vxxnqnQ7lMBnXa8oRyYRyMLtwx0hU/edit#slide=id.g11c1c42e02_3_0).


The faded grey list items make for great scannability, can we expand this to other areas on the table? (e.g. red for list items in bottom 10th percentile)
Add subtle alternating colored rows (e.g. #fff & #f7f7f7) for horizontal scanning
Q: Are all of these columns necessary for this table?
<img width="499" alt="screen shot 2016-03-02 at 12 44 25 pm" src="https://cloud.githubusercontent.com/assets/1056957/13469255/820d9508-e074-11e5-9ea6-7533c0c961e3.png">

**Comment by kevinrobinson** [comment]
@johnrobbjr I'd love to address this, and maybe this would be a good project for you and Kemal to help with, since it requires less context and ramp-up than other changes.

For this table I think it's important to keep in mind that there's a more primary way to filter with the UI elements above.  So I think additional color encoding is slightly less important than it would be without that.  That being said, I'd love to use some more color encodings here and would welcome mocks that tried to incorporate this and row striping, while also improving the visual clarity.

As for which columns are necessary, probably not.  The goal here was to take the most improtant items from the filtering mechanism above.  The best candidates to cut would probably be MCAS scores or the demographic columns (which are also wide).  I think it'd be great to simplify this, but would be concerned about taking more away just for clarity, as long as it fits without horizontal scrolling.

I think in reality, the most common use case here is filtering above, and then scrolling through names.  I'm not sure the columns will be as heavily used, but they also don't seem to be doing much harm (given we make some visual improvements like the great ones you suggested).

**Comment by johnrobbjr** [comment]
![issue-88_01](https://cloud.githubusercontent.com/assets/9868315/15344630/443a48d2-1c76-11e6-9fcb-bfc2464241b9.png)

Playing around with ideas today (see above), trying to pull the best aspects from both current graphs. I'll look into other ways to display columns other than the actual since space is the main pain point on this issue.

**Comment by johnrobbjr** [comment]
Next up I'm going to figure out which columns will be included in the homepage, and which will be included in the room-specific page. Then add some spacing to the mockup and post that here.

**Comment by alexsoble** [comment]
@johnrobbjr Neat, thanks for taking on this work!

**Comment by johnrobbjr** [comment]
![issue-88_02](https://cloud.githubusercontent.com/assets/9868315/15695299/b4a25468-2773-11e6-9edf-55d157fb3f5f.png)

I'm not sure which columns should be included in the dashboard/homepage, someone who is more familiar with what data is more important to administrators might have good insight into that.

Besides that, this styling should be able to be applied to both tables. Any feedback would be greatly appreciated, let me know if any further redlines need to be added for implementation.
