### ISSUE TITLE
Student Report share highcharts code with student profile

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#880]
Currently the javascript for the student report is copied and pasted from student_profile/profile_bar_chart.js into student_profile/pdf/student_profile_pdf.js. 

This code should be merged to be shared between the profile and the student PDF report.

**Comment by kevinrobinson** [comment]
👍 sounds like a good plan!

One first step could be to factor those methods out into a separate file as functions on a `GraphHelpers` object, and then call them from both `profile_bar_chart` and `student_profile_pdf`.  Second, to check whether the other options for the charts should be shared between the PDF code and [profile_bar_chart#116](
https://github.com/studentinsights/studentinsights/blob/8f9695e834c91ae3e18e93943910372cb06a6bb1/app/assets/javascripts/student_profile/profile_bar_chart.js#L116).

**Comment by jhilde** [comment]
Shipped with #873.
