### ISSUE TITLE
Handle students who become inactive

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#9]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/447.

## Notes

+ Only active students come through the X2 export
+ When they become inactive, we want to destroy their records or give them an inactive status
+ One way to do this would be to detect which students are no longer in the export file
+ But better would be to get the actual Active/Inactive data from X2

**Comment by alexsoble** [comment]
As a first step, dove a bit into the contents of the `STD_ENROLLMENT_STATUS` column. 

Here are the different column values present in X2:

### Enrollment statuses

"Active"
"Graduate"
"Withdrawal-24"
"SummerWithdrawal-20"
"Withdrawal-20"
"Withdrawal-23"
"Withdrawal"
"Not Attending"
"Withdrawal-22"
"DropOut"
"DropOut-36"
"DropOut-35"
"SummerDropOut-36"
"SummerWithdrawal-22"
"Withdrawal-21"
"SummerWithdrawal-21"
"SummerGraduate"
"SummerWithdrawal"
"SummerDropOut-34"
"Excluded"
"SummerWithdrawal-24"
"DropOut-34"
"Attainment"
"DropOut-30"
"SummerDropOut-35"
"PreRegNew"
"DropOut-31"
"SummerDropOut-30"
"SummerAchievement"
"Achievement"
"SummerWithdrawal-23"
"Services-41"
"SummerMaxAge"
"MaxAge"
"DropOut-32"
""
"DropOut-33"
"SummerAttainment"
"SummerDeceased"
"Deceased"
"SummerExcluded"
"SummerDropOut-32"
"Certificate"
"SummerDropOut-33"
"SummerDropOut"

**Comment by alexsoble** [comment]
Based on the categories above, looks like we want to:

+ keep and update the record in Student Insights if student is "Active" 
+ destroy the record in Student Insights if student belongs to one of the other categories

**Comment by alexsoble** [comment]
On second thought, that may not be the behavior we want...

If a student graduates or transfers, for example, we may want to keep the records of services and notes that have been entered into the system at MTSS or SST meetings. 

Best thing to do is consult with Uri and Jill at Somerville Public Schools about their preferences for how to handle this.

**Comment by kevinrobinson** [comment]
Good point!

Here's a thought from the train: What if the import always imported all
students, but took the 'active' bit too? Then we could show only active
students in the Student Insights product. That moves towards having less
logic during import. A cost is that it may increase query times if there
are more student rows, but we already have work queued up to precomputing
those queries.

**Comment by alexsoble** [comment]
@kevinrobinson Yup!

**Comment by alexsoble** [comment]
Merged in and productionized after removing non-null constraint (#277).

**Comment by alexsoble** [comment]
One small remaining issue worth noting: there are 23 students on the production site who have an `enrollment_status` of `nil`. Looking up these students against the X2 database, a clear pattern emerged: none of these students are at the Healey school anymore. 

These must be students who were at the Healey school when the project began, but have since transferred out, so that when we run `thor import:start --school HEA` they are no longer in scope and their `enrollment_status` attribute does not get updated.

This is not worth fixing because:

1. these students' information is not surfaced on the school overview page (`student.enrollment_status != "Active"`), and
2. as we onboard more schools onto the tool, the number of students in this category will fall.

**Comment by kevinrobinson** [comment]
@alexsoble awesome!  This sounds like some great digging and a good path forward.  :+1:

One future thought is that since a fully stateless import process has a lot of simplicity benefits, we could always import students who have an `enrollment_status` of nil, which would bring staging one step closer to production and remove more logic from import process (where as much of the Aspen-sourced data in Student Insights is identical to the Aspen data each day as possible).
