### ISSUE TITLE
Investigate nil STAR assessment data

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#91]
I'm not sure if this is related to the work in https://github.com/studentinsights/studentinsights/pull/83, https://github.com/studentinsights/studentinsights/issues/1 or a separate issue.  I noticed it working on improvements to the profile v2 page, specifically for this student (need authorization): https://somerville.studentinsights.org/students/59/profile?column=ela

<img width="369" alt="screen shot 2016-02-17 at 5 15 49 pm" src="https://cloud.githubusercontent.com/assets/1056957/13126822/1d200da4-d59a-11e5-9321-81172904312a.png">

This is coming from STAR assessments with `percentile_rank` set to nil.  I'm not sure yet if this is expected and the controller or UI should interpret these data points differently, or if this is a bug somewhere in the import process.  First steps of investigation:

```
def nil_star_assessments(assessment)
  all_stars = StudentAssessment.all.select {|sa| sa.assessment_id == assessment.id };nil
  nil_stars = StudentAssessment.all.select {|sa| sa.assessment_id == assessment.id && sa.percentile_rank.nil? };nil
  
  {
    nil: nil_stars.size,
    total: all_stars.size,
    percent: (100 * nil_stars.size.to_f / all_stars.size).round.to_s + '%'
  }
end


irb(main):066:0* pp math: nil_star_assessments(Assessment.find(21));nil
{:math=>{:nil=>764, :total=>2199, :percent=>"35%"}}
irb(main):067:0> pp ela: nil_star_assessments(Assessment.find(9));nil
{:ela=>{:nil=>775, :total=>2532, :percent=>"31%"}}
```

@alexsoble have you run into this before, or do you know if it's a new issue?

**Comment by kevinrobinson** [comment]
We could filter these out in the controller or UI, but I think it's worth digging more here.

**Comment by alexsoble** [comment]
@kevinrobinson Will dig in!

**Comment by alexsoble** [comment]
Confirming that this is a data problem.

Digging into the example above, the student has 7 STAR assessment results. 4 non-nil STAR results map to 4 assessment results in our raw STAR data files. 3 nil STAR results do not map to real assessments and should be deleted.

To confirm this hypothesis, I ran a fresh STAR data import to a staging environment. I then ran the following query against the fresh import environment and the production environment:

```
PRODUCTION
Assessment.find_by_family('STAR').student_assessments.where(percentile_rank: nil).count
=> 775

FRESH DATA PULL
Assessment.find_by_family('STAR').student_assessments.where(percentile_rank: nil).count
=> 0
```

This means the production environment contains some junk STAR data. These data points don't have `percentile_rank` results but they do have other data like `growth_percentile` and `scaled_score`. This makes me suspect that this data from another source that was incorrectly assigned to the STAR assessment sometime in the past. The nil data points are not recent and a fresh data pull does not include any nil data points.

Will write a migration to fix this issue.

**Comment by kevinrobinson** [comment]
@alexsoble awesomeness!

Not sure if this a crazy idea or not, but... :)  Do you think it would make sense to destroy all the tables that are imported each night, to prevent this kind of drift altogether?  Or do the import tasks optimize to not import all of Aspen each night?

**Comment by kevinrobinson** [comment]
@alexsoble this looks great for reading!

<img width="451" alt="screen shot 2016-03-02 at 9 29 50 am" src="https://cloud.githubusercontent.com/assets/1056957/13463250/6335d8ea-e059-11e5-9a3c-be2aa7e992d0.png">

Looks like the `.find` above was only matching on the first STAR, so the same fix would do the trick for Math too:

```
irb(main):006:0> Assessment.where(:family => 'STAR').flat_map do |a|
  {
    subject: a.subject,
    nil_count: a.student_assessments.where(percentile_rank: nil).count
  }
end
=> [{:subject=>"Reading", :nil_count=>0}, {:subject=>"Mathematics", :nil_count=>764}]
```

**Comment by alexsoble** [comment]
@kevinrobinson Yup, saw that, fixing now

**Comment by alexsoble** [comment]
@kevinrobinson Good ideas, worth thinking about!

**Comment by kevinrobinson** [comment]
:+1: awesome, you are speedy!

**Comment by alexsoble** [comment]
@kevinrobinson The page is looking better now!

**Comment by kevinrobinson** [comment]
awesome, thanks for digging into this!

**Comment by alexsoble** [comment]
@kevinrobinson Thanks for noticing and documenting it!
