### ISSUE TITLE
Profile v2 - Improve header styling

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#93]
This is part of https://github.com/studentinsights/studentinsights/issues/5.

@BWieber here's a suggestion for a discrete piece of work we could use your help with.  Let me know what you think!

### Designs
The initial styling on the profile v2 page is functional but not exactly nice-looking yet. :)  Here's the current state:
<img width="1275" alt="screen shot 2016-02-17 at 5 27 20 pm" src="https://cloud.githubusercontent.com/assets/1056957/13127112/b7ce9900-d59b-11e5-8df1-73e9479b671e.png">

@alexsoble's initial design idea was something more like this (from https://github.com/studentinsights/studentinsights/files/122155/profile.redesign.v2.3.pdf):
<img width="1274" alt="screen shot 2016-02-17 at 5 24 47 pm" src="https://cloud.githubusercontent.com/assets/1056957/13127106/add973a2-d59b-11e5-9479-af43d4e0cdab.png">

## Starting points
So it'd be great to improve this!  I [factored out this code](https://github.com/studentinsights/studentinsights/pull/92) to its own component, so you have a nice clear space to work in.  I also added some comments to the [pull request](https://github.com/studentinsights/studentinsights/pull/92/files) about what's going on and pointers to starting places.

## Steps
+ [x] Let's keep the links blue rather than changing them to black
+ [x] https://github.com/studentinsights/studentinsights/pull/108 - Make the grade level text look nicer, like "5th grade"
+ [x] https://github.com/studentinsights/studentinsights/pull/101 - Add the bullets in between (can try a [Unicode character](http://www.fileformat.info/info/unicode/char/2022/index.htm))
+ [x] https://github.com/studentinsights/studentinsights/pull/101 - Improve horizontal spacing between each item to match the mock
+ [x] https://github.com/studentinsights/studentinsights/pull/108 - Add Risk level text using the real value
+ [x] https://github.com/studentinsights/studentinsights/pull/108 - Use [flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes) to move the risk level text to the right of the page
+ [x] https://github.com/studentinsights/studentinsights/pull/108 - Add in the colored circle styling (can use [this](https://github.com/studentinsights/studentinsights/blob/master/app/assets/stylesheets/table.scss#L54) as inspiration, from [here](https://somerville-teacher-tool-demo.herokuapp.com/homerooms/2))

These can all be a part of one pull request - it might be helpful for you to keep each step as a separate commit, but it's up to you whatever you think works best.  If you have any other ideas I'd love to check them out, feel free to try them out and submit those as well.  And please let me know any feedback you have on whether this is helpful as a starting point or if there's anything I can clarify more.

I'll be out of town tomorrow through the weekend so I'll check in Monday and can review anything you'd like.  And I'm happy to chat more with you over email or Slack next week, or work on it together next Tuesday at Code for Boston so we can get this shipped!

Thanks for your help!

**Comment by kevinrobinson** [comment]
@BWieber also, here's some links about Chrome DevTools, which are the amazing debugging tools @erose mentioned the other week: https://developer.chrome.com/devtools

**Comment by kevinrobinson** [comment]
@BWieber I updated the items here based on your awesome work, let me know if I missed anything, or if there's anything else I can help out with!

**Comment by BWieber** [comment]
Hi Kevin! 

Taking a look at this (I forgot about this issue!), the #108 PR actually finishes this issue up! If you'd like the styling to be adjusted a bit, let me know and I'll get right into it! 

_Brandon_

**Comment by kevinrobinson** [comment]
@BWieber yeah, this looks like it does it, except for swapping out the float for [flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes).  I think let's merge that PR as-is, and if you want to flexbox-ify I'm happy to help out with that or point you in the right direction, flexbox is worth learning about for any front-end development. :)

**Comment by kevinrobinson** [comment]
This issue was stale, this work has been done.
