### ISSUE TITLE
Make Event Note Types district-level configurable

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#970]
Pulling out of https://github.com/studentinsights/studentinsights/pull/969#issuecomment-323437525:

Some of the Event Note Types are Somerville-specific. So one of the changes we'll need to make to accommodate the second district is make Event Note type configurable. 

One route would be to have all district's Types hanging out in the database together, and then configure which district gets sent which `EventNoteType` options at the Rails level. 

Another way would be to do `SchoolDistrict has_many EventNoteTypes`, and store the relationship in the database.

**Comment by kevinrobinson** [comment]
We did some of this!  There's lots of bits in `per_district.rb` and `PerDistrict.js` and for this particular case we use the same `event_note_type` definitions across all districts, and then only show different ones in different cases.  The whole thing runs on separate instances still for strong isolation between districts, and matched to the cost and cadence of onboarding new districts.
