### ISSUE TITLE
dead link in Readme

### ISSUE THREAD

**Issue by renemarcelo** [studentinsights/studentinsights#98]
This project is great. I'm also interested in seeing design history mentioned at https://github.com/studentinsights/studentinsights#more-information but dropbox link may be broken/unavailable.

**Comment by alexsoble** [comment]
Good catch @renemarcelo, thanks for the issue! 

@AmirHadjihabib Do you know what happened to this Dropbox site? Did it get lost in the post-CFA transition or are these materials still hanging around somewhere? If so would be nice to add them directly into the repo or README so that we can lose the dependency on Dropbox or another outside system.

**Comment by kevinrobinson** [comment]
@renemarcelo If you'd like any specific information feel free to ask here or drop into [chat](https://github.com/studentinsights/studentinsights#more-information).

**Comment by renemarcelo** [comment]
Thank you @kevinrobinson !

**Comment by kevinrobinson** [comment]
@renemarcelo I ran into https://github.com/codeforamerica/somerville-teacher-tool/issues/63 looking at another issue, which might have helpful background for you.

Separately, I've removed the dead link for now in https://github.com/studentinsights/studentinsights/pull/164.  @AmirHadjihabib if you have a Dropbox link or can help investigate that'd be awesome and we'll add it back in.

@renemarcelo I'm going to close this dead link issue - if it's critical for you please just reopen and say so. :)  We were talking separately at Code for Boston this week about how to give designers and product folks more context, so they can build a shared understanding quickly and help contribute their expertise.  If you have suggestions for what you'd like to see in that regards, please open a new issue describing that and I'll be happy to flesh that out in writing more next week.  And thanks for your help!
