### ISSUE TITLE
Fix student names endpoint timeout

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#993]
Getting this error from Logentries: 

```
at=error code=H12 desc="Request timeout" method=GET path="/students/names" host=somerville.studentinsights.org 
```

**Comment by alexsoble** [comment]
Strategy . . . gonna cache JSON that powers the searchbar in the database instead of checking authorization for every single student against the current educator.

**Comment by alexsoble** [comment]
Still throwing lots of errors, let's see if this helps:

```
heroku run:detached rake chores:update_searchbar_data_for_educators_who_log_in
```

**Comment by jhilde** [comment]
@alexsoble Wanted to checkin to see how this is coming. Looks like you were moving the updating of the students for the search bar out of the importer and into a separate job. 

Looking into the issue #1023, it appears to me that it is this code that's taking 3+ hours to execute, causing the timeout. 

Unfortunately, this means that high school teachers who had students transfer into our out of sections don't see the correct roster for their section in Student Insights. 

Looks from your code that the call to Educator.save_student_searchbar_json for each educator should be eliminated? And the rake chores:update_searchbar_data_for_educators_who_log_in should be added to the scheduled nightly jobs?

**Comment by alexsoble** [comment]
Hey @jhilde! Hmmmm, what data source are you looking at that shows it takes 3+ hours to execute?
 I'm hoping this will give us a little more data: https://github.com/studentinsights/studentinsights/pull/1050

But overall, yes you're 100% right . . . now that we have a task that's precomputed for most of the educators, we don't need to run `save_student_searchbar_json` for every educator on every import. Good catch, thanks for keeping an eye out here!

**Comment by jhilde** [comment]
Hey @alexsoble, I just looked through logentries to see when each importer began and subtracted. Nothing fancy. I have lots of ideas on doing some more logging on imports but I'll save that for another day soon.

IMHO, it looks like we're trying to reuse the logic in educator.is_authorized_for_student by calling it once per student per educator. I think the reuse of the logic is noble and definitely makes sure the permissions are in sync. For example when I added section permissions, I didn't need to know anything about the json for search bar. But for performance, I might argue that the logic should be duplicated to reduce the overhead of LOTS of redundant queries per educator.

**Comment by jhilde** [comment]
If we wanted to maintain the goodness of centralizing that logic, perhaps we could consider switching to caching the list of students an educator has access to in the database during import. We would probably also want to do something a bit wiser with district_wide and school_wide people so we don't pollute the database too much.

Just some thoughts...

**Comment by alexsoble** [comment]
This isn't timing out anymore!

**Comment by jhilde** [comment]
🎊
