### ISSUE TITLE
Fix (Internet Explorer?) issue with column selection 

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#995]
From Uri:

"The only thing that’s not working is the selector that lets you choose what columns you want to see.  I’ve unselected columns but nothing happens."

**Comment by alexsoble** [comment]
Yup it's an IE issue, confirmed in Browserstack: 

```
SCRIPT438: Object doesn't support property or method 'assign' 
```

**Comment by alexsoble** [comment]
Just musing out loud, IE-specific full-stack system tests (new Rails word for integration or feature tests) could be a helpful thing to write at some point.

**Comment by kevinrobinson** [comment]
@alexsoble This looks like id didn't get reported in Rollbar, which seems surprising to me.  Is that what you see, and any ideas why that might be?

**Comment by alexsoble** [comment]
@kevinrobinson I see it in Rollbar: https://rollbar.com/somerville-teacher-tool/somerville-teacher-tool/items/43/

**Comment by kevinrobinson** [comment]
@alexsoble ah wow thanks!

It doesn't show up on the dashboard for me, and I didn't get an individual email for me, but I see a bunch of things here: https://rollbar.com/somerville-teacher-tool/somerville-teacher-tool/items/ that I didn't realize were things.  I must have to muck with my notifications or email filters, so thanks!
